### ISSUE TITLE
The difference between os configure JSON config and config.json is not clear

### ISSUE THREAD

**Issue by pimterry** [balena-io/balena-cli#1002]
<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_elab)

**Comment by pdcastro** [comment]
I believe this has been improved with PR #1507 
Also, revisiting the `balena config *` and `balena os *` commands is the subject of the CLI Configuration project that we are now specifying, to improve the "balenaOS configuration story" using the CLI.
