### ISSUE TITLE
Docker seems to be unavailable. Is it installed and running?

### ISSUE THREAD

**Issue by richardlevano** [balena-io/balena-cli#1017]
balena-cli v9.0.2
Ubuntu x86

Following https://www.balena.io/open/docs/getting-started
when I run :
balena deploy myApp --logs --source . --emulated

I get :
Docker seems to be unavailable. Is it installed and running?

I use Ubuntu and Docker is installed and docker run hello-world run just fine.

Any help is appreciated.

**Comment by richardlevano** [comment]
Never mind I fixed it. All I needed to do is manage docker as a non-root user
https://docs.docker.com/install/linux/linux-postinstall/#manage-docker-as-a-non-root-user

**Comment by thgreasi** [comment]
Hi @richardlevano 
Thanks for sharing back your findings :+1: 

Having a non-root docker group with your user in there is a best practice that not only reduces security risks but also makes docker play nicely with other tools, like the balena-cli.
Docker also provides a repository & a convenience setup script for ubuntu that handles most of the setup, including the creation of the docker user group, but adding your user in the generated group (`sudo usermod -aG docker your-user` for future reference) is still required.
See: https://docs.docker.com/install/linux/docker-ce/ubuntu/#install-using-the-convenience-script
