### ISSUE TITLE
Cannot run balena local logs 

### ISSUE THREAD

**Issue by horia-delicoti** [balena-io/balena-cli#1024]
- **Cli version: 9.1.2**
- **Operating system and architecture: Ubuntu 16.04 x86_64**

The `if not the case` situation shouldn't be that I am not trying to burn an SDCard.
```
⇒  balena local logs 192.168.x.xxx     
You don't have enough privileges to run this operation.
Try running this command again prefixing it with `sudo`.

If this is not the case, and you're trying to burn an SDCard, check that the write lock is not set.
...
```
also
```
sudo balena local logs 192.168.x.xxx
sudo: balena: command not found
```

**Comment by pimterry** [comment]
@horia-delicoti you do need to run this command with sudo, unfortunately. The error at the end there means that your root user's PATH doesn't include the `balena` binary. You need to either change the PATH used, link `balena` into somewhere that's already in your path, or specify the full path to `balena` when sudoing.
