### ISSUE TITLE
Problem in 9.2.0

### ISSUE THREAD

**Issue by BlackoJack** [balena-io/balena-cli#1028]
- **Cli version: 9.2.0
- **Standalone install: no & yes
- **Node version: 11.1.0
- **Npm version: 6.4.1
- **Operating system and architecture: Manjaro Linux 18 x64 & Ubuntu 18.04 bionic x64

[black@black-PC ~]$ balena os configure ~/resin.img --app rdaa_test --version 2.26.0
Configuring operating system image
Promise.resolve(...).get is not a function

If you need help, don't hesitate in contacting us at:

  GitHub: https://github.com/balena-io/balena-cli/issues/new
  Forums: https://forums.balena.io

  In Cli version 9.1.4 its all ok

---

*Please keep in mind that we try to use the issue tracker of this repository for specific bug reports & CLI feature requests. General & troubleshooting questions are encouraged to be posted to the [balena forums](https://forums.balena.io) where the community can both contribute and benefit from the answers.*

*Before submitting this issue please check that this issue is not a duplicate. If there is another issue describing the same problem or feature please add your information to the existing issue's comments.*

**Comment by dfunckt** [comment]
This seems related to 8291c96e69407.

**Comment by dfunckt** [comment]
Fixed in v9.2.2
