### ISSUE TITLE
Balena sync not working with short uuid

### ISSUE THREAD

**Issue by acostach** [balena-io/balena-cli#1044]
- **Cli version: 9.3.6**
- **Standalone install: installed with npm**
- **Node version: v8.10.0**
- **Npm version: 3.5.2**
- **Operating system and architecture: Ubuntu 18.04.1 LTS 64**

---
balena ssh works with both short & long uuid
balena sync works **only** with long uuid, fails with short uuid:

$ balena sync 9793441 -s . -d /usr/src/app
BalenaDeviceNotFound: **Device not found: 9793441**

$ balena sync 97934417b6d3830879c146ae6531bfe5 -s . -d /usr/src/app
Getting information for device: 97934417b6d3830879c146ae6531bfe5
Got application container info.
Synced /usr/src/app on **9793441**.

**Comment by thgreasi** [comment]
Hi,
Thanks for bringing this up.
It seems that the issue caused because the short uuid you are providing is inferred as a number.
This is definitely something we can and should handle, just like we do in the rest actions of the CLI.

**Comment by pdcastro** [comment]
It looks like this issue became obsolete as the `balena sync` command was removed in CLI v11 (released back in June). The functionality was replaced with the ["live push" feature](https://www.balena.io/blog/living-on-the-edge-with-livepush-and-other-cli-improvements/), which is enabled by default with the "balena push <ip-address>" command.
