### ISSUE TITLE
Adding custom device fails, because the device slug is not contained in the list of supported devices

### ISSUE THREAD

**Issue by zrzka** [balena-io/balena-cli#1049]
Check [this forum thread](https://forums.balena.io/t/connect-custom-device-to-balena-io/4513). User tried to add custom device to balena and it doesn't work because the slug for the device not being contained in the list of supported devices and [this error](https://github.com/balena-io/balena-cli/blob/6070ee0f83364df91409a3fdc141ce9cdb131a05/lib/utils/promote.ts#L201) is triggered. User did propose a workaround:

> I guess I could fake being another device by setting the slug accordingly, are there better solutions?

Which seems to be the only way now.

cc @pdcastro

**Comment by thgreasi** [comment]
This probably needs an architecture call @zrzka .
Can you open one for this?

**Comment by thgreasi** [comment]
cc: @shaunmulligan

**Comment by thgreasi** [comment]
As discussed in the architecture call of 2018-12-11
The proper way to do this is to use the slug for a generic device type that matches the device's architecture. At the moment there is `generic-aarch64` which should be used for custom device types of ARMv8 architecture.
See: https://api.balena-cloud.com/device-types/v1/generic-aarch64

You can find the complete list of supported device types at:
See: https://api.balena-cloud.com/device-types/v1/

PS: The `generic` device type is marked as `isDependent` and doesn't show in the "Create application" modal and is only meant to be used for that use case and not for custom devices.
See: https://api.balena-cloud.com/device-types/v1/generic

**Comment by zrzka** [comment]
@thgreasi thank you for taking care of this!
