### ISSUE TITLE
Standalone executables and documentation: rename 'darwin' or 'OSX' to MacOS

### ISSUE THREAD

**Issue by pdcastro** [balena-io/balena-cli#1080]
Standalone executables are currently named 'balena-cli-version-darwin-x64.zip', and the standalone documentation refers to OSX. Rename both to 'MacOS', which is Apple's official name for the OS and more readily identifiable to many users.

**Comment by jarrah31** [comment]
I agree, it shouldn't be called Darwin if it's for MacOS as it certainly confused me. Had to google which led me to this Issue.

**Comment by pdcastro** [comment]
Resolved in CLI v11: https://github.com/balena-io/balena-cli/releases
