### ISSUE TITLE
balena push fails for a private device

### ISSUE THREAD

**Issue by floion** [balena-io/balena-cli#1084]
- **Cli version:**
9.3.6
- **Standalone install:** yes
- **Node version:**
- **Npm version:**
- **Operating system and architecture:**

balena push 192.168.0.150
[Info]    Starting build on device 192.168.0.150
[Info]    Creating default composition with source: .
[Build]   [main] Step 1/8 : FROM balenalib/val100-node:10-stretch-run
Build error

If you need help, don't hesitate in contacting us at:

  GitHub: https://github.com/balena-io/balena-cli/issues/new
  Forums: https://forums.balena.io

---

*Please keep in mind that we try to use the issue tracker of this repository for specific bug reports & CLI feature requests. General & troubleshooting questions are encouraged to be posted to the [balena forums](https://forums.balena.io) where the community can both contribute and benefit from the answers.*

*Before submitting this issue please check that this issue is not a duplicate. If there is another issue describing the same problem or feature please add your information to the existing issue's comments.*

**Comment by imrehg** [comment]
Not a CLI issue, no such base image.
