### ISSUE TITLE
Reboot command throws error

### ISSUE THREAD

**Issue by zariye** [balena-io/balena-cli#1086]
When doing `balena device reboot <DEVICE UUID>` on a multi-container application I get a timeout with the following message

> network timeout at: https://api.balena-cloud.com/supervisor/v1/reboot

still the device does a reboot as expected.

For reference: 

- **Cli version:** 9.12.0

- **Standalone install:** no

- **Node version:** v8.9.4

- **Npm version:** 6.7.0

- **Operating system and architecture:** macOS High Sierra 10.13.6, 64-Bit

**Comment by srlowe** [comment]
Unable to reproduce on CLI v12.55.0
