### ISSUE TITLE
Add a command, for mapping local ports to device ports over the VPN/proxy

### ISSUE THREAD

**Issue by richbayliss** [balena-io/balena-cli#1087]
# Overview

It would be great to add a command to the CLI in order to map local ports to remote ports on the device.

E.g.

    $ balena map -p 8080:{uuid}:80 -p ...

This would allow users to access port 80 listening on the device, by connecting to `127.0.0.1:8080`

# Security

Currently, only some ports are allowed to be accessed, so maybe this mechanism should include a new means to add mapped ports to an allow whitelist etc.

**Comment by dansku** [comment]
This project would be very useful for connecting to a X11 application over VNC+tunnel

https://github.com/balena-io-playground/balena-x11-example/

**Comment by pdcastro** [comment]
@richbayliss, isn't this what the `balena tunnel` command does? Perhaps you had created this issue before implementing `balena tunnel`? In which case, this issue could be closed. :-)

**Comment by pdcastro** [comment]
Confirmed that this was implemented as `balena tunnel`.
https://www.flowdock.com/app/rulemotion/resin-frontend/threads/ERbiRP6yZKxlcccfIybRg1Stcnv
