### ISSUE TITLE
Add a --config option to balena rm <id>

### ISSUE THREAD

**Issue by pdcastro** [balena-io/balena-cli#1093]
As requested by @thgreasi:

> * Add a `--config` option to `balena rm <id>`
>
> Consider also:
> * Allow `balena rm <idOrName>`
> `balena rm MyApp myenvar` sounds good but
> `balena rm <uuid> myenvar` sounds like a completely different thing

Thread with more details:
https://www.flowdock.com/app/rulemotion/r-resinos/threads/qdUvxai2LdzyzGqcA59-kdTzySq

**Comment by thgreasi** [comment]
Already merged PR https://github.com/balena-io/balena-cli/pull/1460 did add `balena rm <id> --config`, so I'm closing this.
