### ISSUE TITLE
Balena device not working when device UUID has a 0 as first character

### ISSUE THREAD

**Issue by t16n** [balena-io/balena-cli#1108]
- 9.12.1
- no
- v10.15.0
- 6.4.1
- macOS 10.14.3

When the device UUID has a 0 as the first character the balena device cli command is not working.
For example:

> balena device 0733307
> 
> returns:
> BalenaDeviceNotFound: Device not found: 733307

Putting the device id in String quotes did not help.
(balena device "0733307" / balena device '0733307')

**Comment by pdcastro** [comment]
@t16n, thanks for reporting this issue! It has been fixed in release 9.12.7. You can check the version you are running with the `balena version` command, and the CLI can be updated by re-running the installation steps: https://www.balena.io/docs/reference/cli/
