### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by AaronOoooo** [balena-io/balena-cli#1117]
- **Cli version:**
- **Standalone install:** yes
- **Node version:** v11.10.0
- **Npm version:** 6.8.0
- **Operating system and architecture:** MacBook, v 10.13.6
---
After running **balena push BalenaDash**, this error message appears: 

**Packaging the project source...No such file or directory: /Users/xxxxxx/Library/Saved Application State/com.apple.Notes.savedState**

I've checked, and the file does exist in that location. Any help is much appreciated.

**Comment by pdcastro** [comment]
@AaronOoooo, it looks like this issue fell through the cracks, and no one replied to it at the time -- sorry for that.  I would hazard a guess that what went wrong is that it is necessary to execute a `cd` command to the project folder before running `balena push`, something like:
```
cd balena-dash

balena push BalenaDash
```

There is another open issue, #1421, for improvements to be made to the CLI to detect that the current folder "doesn't look right", and print a more user-friendly error message. Other than that, as it looks like this is more of a troubleshooting matter than a CLI bug, if something is still not working I suggest reaching out in the [balenaCloud forum](https://forums.balena.io/c/balena-cloud), which is monitored by the balena support team who will be happy to help you further. Thank you for trying out balena's platform!
