### ISSUE TITLE
Feature request: balena envs should show application and device service vars

### ISSUE THREAD

**Issue by nazrhom** [balena-io/balena-cli#1123]
The `balena envs` command currently does not show application and device service vars. 
This was mentioned in https://github.com/balena-io/balena-cli/issues/855 but that issue was closed as it regarded support for multi-container apps in general. Opening to track this separately.

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_hoe3)

**Comment by pdcastro** [comment]
Loosely related to #1153

**Comment by pdcastro** [comment]
This issue was resolved in CLI v11.20.0 (12 Dec 2019).
