### ISSUE TITLE
document that balena sync doesn't work with multicontainer

### ISSUE THREAD

**Issue by shaunmulligan** [balena-io/balena-cli#1139]
Since we are deprecating `balena sync` we haven't build multicontainer support for it. 

links to https://github.com/balena-io/docs/issues/1043

**Comment by mdtusz** [comment]
What will be the recommended workflow for local development using multicontainer systems? This is something we've struggled with since the beginning.

Is it on the roadmap for a vm-able balena image that can support bind-mounts? Having to continually do a full docker-build and deploy makes the dev process very slow.

**Comment by pdcastro** [comment]
> _What will be the recommended workflow for local development using multicontainer systems?_

@mdtusz, the current balena-cli version (10.0.0) has this deprecation notice for `sync`:
```
$ balena help sync
Usage: sync [uuid]
-------------------------------------------------------------------------
Deprecation notice: please note that `balena sync` is deprecated and will
be removed in a future release of the CLI. We are working on an exciting
"live push" alternative: https://github.com/balena-io-modules/livepush
-------------------------------------------------------------------------
```

I am not aware of plans for a "vm-able balena image that supports bind mounts"... I am aware of `balena push <device_ip_address>` (not to be confused with `balena local push`) and the "live push" project mentioned in the deprecation message above, which I hear is coming soon and promises to speed up the develop-test-develop iterations. Maybe @shaunmulligan has something to add?

**Comment by pdcastro** [comment]
Documentation for `balena sync` no longer exists, hence closing this issue. The new recommended workflow is to use `balena push`. The "live push" feature (live filesystem watching) is enabled by default.
