### ISSUE TITLE
Deprecate old CLI commands.

### ISSUE THREAD

**Issue by shaunmulligan** [balena-io/balena-cli#1141]
We need to mark the following CLI commands as deprecated:
- sync
- local push
- quickstart (we might be able to just remove this one instantly)

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_ig7v)

**Comment by jlucidar** [comment]
why `local push` will be marked as deprecated ? What is the new proper way to push a new image to a local device ?

**Comment by shaunmulligan** [comment]
@jlucidar the new proper way is doing `balena push <deviceIP>` that now supports multicontainer, private registries, build-time secrets. It also now has its containers started directly by the supervisor, so you will have access to all `BALENA_` env vars and the supervisor local API.

We will also be extending it soon with a `--live` flag that will do fast syncing, you can follow the development of that here: https://github.com/balena-io/balena-cli/pull/1076

**Comment by jlucidar** [comment]
@shaunmulligan Cool ! So it means that we will be able to pass args with the --build-args flag and add ARG to our dockerfiles ? :dancing_men:

**Comment by shaunmulligan** [comment]
@jlucidar no, i don't think that is implemented yet I think @pdcastro or @CameronDiver know more about that.

**Comment by pdcastro** [comment]
'quickstart' command deleted (reason for "change-type: major") and deprecation notices added for the 'sync' and 'local push' commands: PR https://github.com/balena-io/balena-cli/pull/1152
The new CLI version is 10.0.0. Hmm it feels like such a nice new major version should have been the result of a more exciting change than "removal of the 'quickstart' command"... :-)
