### ISSUE TITLE
Nested .gitignore / .dockerignore files are not interpreted correctly

### ISSUE THREAD

**Issue by pdcastro** [balena-io/balena-cli#1148]
One of the CLI users has kindly provided a detailed description of a case where relative paths and wildcards in nested .gitignore and .dockerignore files are not interpreted as expected, with CLI version 8.0.0 and above:

https://github.com/Krismix1/balena_cli_test

This issue is closely related to #1032, but could be addressed independently in relation to the treatment of relative paths (versus the separate matter of whether .ignore should apply to different files or at a different image build stage as .dockerignore).

The known workaround is to move the nested .gitignore or .dockignore files up towards the root of the tree (or at the root of each service in a multi-service app), and modify the matching patterns to include the names of subfolders.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_ibv7)

**Comment by wlisac** [comment]
I just ran into this while building a Swift-based project with nested package dependencies.

+1 for this issue (and/or ideally https://github.com/balena-io/balena-cli/issues/1032).

**Comment by jimsynz** [comment]
Just got bitten by this too, since I'm working on a multi container app and the `.dockerignore` files are in each service's subdirectories.

**Comment by bekriebel** [comment]
I'm evaluating Balena right now and just hit this issue with a go project. If [this project](https://github.com/sirupsen/logrus) is included in a `vendor directory`, the way the `.gitignore` is being read is making the whole logrus folder not get included and failing the build.

**Comment by pdcastro** [comment]
CLI release v11.34.0 introduces a new flag for the push / build / deploy commands: `--nogitignore` or `-G`. Quoting `balena help push`:
```
$ balena help push
...
DOCKERIGNORE AND GITIGNORE FILES
By default, both '.dockerignore' and '.gitignore' files are taken into account
in order to prevent files from being sent to the balenaCloud builder or Docker
or balenaEngine (balenaOS device).

However, this behavior has been DEPRECATED and will change in an upcoming major
version release. The --nogitignore (-G) option should be used to enable the new
behavior already now. This option will cause the CLI to:

* Disregard all '.gitignore' files at the source directory and subdirectories,
  and consider only the '.dockerignore' file (if any) at the source directory.
* Consequently, allow files to be sent to balenaCloud / Docker / balenaEngine
  even if they are listed in '.gitignore' files (a longstanding feature request).
* Use a new '.dockerignore' parser and filter library that improves compatibility
  with "docker build" and fixes several issues (mainly on Windows).
* Prevent a warning message from being printed.

When --nogitignore (-G) is provided, a few "hardcoded" dockerignore patterns are
also used and "merged" (in memory) with the patterns found in the '.dockerignore'
file (if any), in the following order:

    **/.git
    < user's patterns from the '.dockerignore' file, if any >
    !**/.balena
    !**/.resin
    !**/Dockerfile
    !**/Dockerfile.*
    !**/docker-compose.yml

If necessary, the effect of the '**/.git' pattern may be modified by adding
"counter patterns" to the '.dockerignore' file, for example '!service1/.git'.
For documentation on pattern format, see:
- https://docs.docker.com/engine/reference/builder/#dockerignore-file
- https://www.npmjs.com/package/@balena/dockerignore
```
And similar for `balena help build` and `balena help deploy`.
Give it a try: feedback is still welcome! The plan is for the `--nogitignore` option to become the default behavior in the next major version release (v12).

Some notes:
* The matching pattern format is not the same between `.gitignore` and `.dockerignore` files. A brief summary of the differences can be found at: https://www.npmjs.com/package/@balena/dockerignore#whats-different-from-ignore-
* While multiple `.gitignore` files are allowed (in subdirectories), this is not the case for `.dockerignore`: only one `.dockerignore` file is allowed, at the "project root".
  * This is the case even for multi-service / multi-container applications: the one `.dockerignore` file should be at same level as the `docker-compose.yml` file (if any), and service names may be listed in the one `.dockerignore` file. The `**` pattern may also be used to recursively match multiple subdirectories, and may be prefixed by the service name for this to effectively apply per service.
  * The fact that nested `.dockerignore` files are not allowed, and that `.gitignore` files are disregarded, effectively solves this GitHub issue.
* balena application deployments with `git push` (instead of `balena push`) is unchanged: `git push` disregards `.dockerignore` files.
* The balenaCloud builder is also unchanged. Like the Docker daemon or balenaEngine, the balenaCloud builders disregard `.dockerignore` or `.gitignore` files. All filtering happens at the client side: git client, balena CLI, or docker CLI.

**Comment by jimsynz** [comment]
@pdcastro this is awesome work.  Does this also address the scenario where you have multiple dockerignore files in different subdirectories?

**Comment by pdcastro** [comment]
> Does this also address the scenario where you have multiple dockerignore files in different subdirectories?

As currently implemented, only a single `.dockerignore` file is considered at the project root. Any additional `.dockerignore` files (in subdirectories) are disregarded, even in the case of a multicontainer / microservices app. It is of course possible to have service-specific ignore patterns, all together in the one single `.dockerignore` file, by prefixing the patterns with the service name. For example, in this project tree:

```
myApp
 |- .dockerignore
 |- file.txt
 |- service1/file1.txt
 |- service2/file2.txt
```
With these `.dockerignore` contents:
```
**/*.txt
!service1/**/*.txt
!service2/file2.txt
service2/start.sh
```

The first pattern (`**/*.txt`) matches all files with `txt` extension in all subdirectories except under the `service1` subdirectory (second pattern) and except for `service2/file2.txt` (third pattern). The fourth pattern matches `start.sh` for `service2` only.

**Comment by jimsynz** [comment]
@pdcastro thanks, yes I knew that. I was hoping that we could improve DX slightly by automatically consolidating those dockerignore files when we find them.

**Comment by pdcastro** [comment]
> I was hoping that we could improve DX slightly by automatically consolidating those dockerignore files when we find them.

@jimsynz, @nslocum, fair enough: see #1870. As CLI v12 stopped looking into `.gitgnore` files, the spotlight shone on the `.dockerignore` support.

**Comment by pdcastro** [comment]
Closing this issue with [the release of CLI v12](https://github.com/balena-io/balena-cli/wiki/CLI-v12-Release-Notes), but it looks like it is not the end of the story: see #1870. Also, CLI v12.1.0 introduced a `--gitignore` (`-g`) option for v11 compatibility in case your project isn't ready (the plan is to remove this option in CLI v13).

**Comment by pdcastro** [comment]
CLI **v12.2.0** introduces the `--multi-dockeringore` (`-m`) option that allows each service to specify its own `.dockerignore` file, in the way that the "standard" `docker-compose` tool works:
```
$ balena help push
...
The --multi-dockerignore (-m) option may be used with microservices (multicontainer)
applications that define a docker-compose.yml file. When this option is used,
each service subdirectory (defined by the `build` or `build.context` service
properties in the docker-compose.yml file) is filtered separately according to
a .dockerignore file defined in the service subdirectory. If no .dockerignore
file exists in a service subdirectory, then only the default .dockerignore
patterns (see below) apply for that service subdirectory.

When the --multi-dockerignore (-m) option is used, the .dockerignore file (if
any) defined at the overall project root will be used to filter files and
subdirectories other than service subdirectories. It will not have any effect
on service subdirectories, whether or not a service subdirectory defines its
own .dockerignore file. Multiple .dockerignore files are not merged or added
together, and cannot override or extend other files. This behavior maximises
compatibility with the standard docker-compose tool, while still allowing a
root .dockerignore file (at the overall project root) to filter files and
folders that are outside service subdirectories.
...
```

**Comment by jimsynz** [comment]
This is awesome work @pdcastro!

![thanks!](https://media.giphy.com/media/S7Jns3yD0qzbRpM7H5/giphy.gif)
