### ISSUE TITLE
User wants to use CLI to apply custom network modifications on the master image

### ISSUE THREAD

**Issue by gelbal** [balena-io/balena-cli#1162]
User wants to modify the balenaOS image file with their custom cellular modem connection config. Ideally the user wants the master image to already include these files/modifications, and then burn that to the SD card from etcher.

Relevant support thread:
https://jel.ly.fish/#/72e0dbf8-b146-417c-9de3-6a7abb6d68b5

--- 

I guess similar to how `balena config generate` works to create a custom config.json file.

**Comment by richbayliss** [comment]
Feature added in #1576
