### ISSUE TITLE
balena push should support pushing to <hostname>.local

### ISSUE THREAD

**Issue by shaunmulligan** [balena-io/balena-cli#1168]
it should be possible to push to a localMode device without specifying the device IP, it should be possible to just specify the mdns name, e.g.:
```
balena push mydevice.local
```

**Comment by pdcastro** [comment]
Duplicate of #1161

**Comment by shaunmulligan** [comment]
@CameronDiver and @pdcastro I will close this now as its implemented. Feel free to reopen if needed
