### ISSUE TITLE
`balena push` should preserve symlinks

### ISSUE THREAD

**Issue by pdcastro** [balena-io/balena-cli#1169]
As reported in the following forum thread, `balena push` is not preserving symlinks when pushing to a local-mode device:
https://forums.balena.io/t/symlinks-break-when-pushing-with-local-mode-on-macos/5992

I suspect (unconfirmed) that the problem is in this `tarDirectory` function:
https://github.com/balena-io/balena-cli/blob/v10.0.0/lib/utils/compose.coffee#L126-L156

... in which case it would also apply to pushing to the balenaCloud image builders.

**Comment by pdcastro** [comment]
Note: the forum thread linked above includes a workaround using a tar gz file.

**Comment by wlisac** [comment]
@pdcastro The behavior of not preserving symlinks can actually be incredibly helpful and solves a common challenge with Docker of not being able to easily include external files in a build context.

I'm leveraging the existing behavior (of not preserving symlinks) to override some of my app's dependencies during local development. These dependencies are elsewhere on the filesystem and symlinked in the current app folder. Note that these dependencies are normally pulled from git repos during most builds, but the ability to override during development is so helpful.

Balena then treats these symlinks like normal folders at build time, which is what I was hoping for.

Here are some links that expand on some more use cases:
- https://github.com/moby/moby/issues/6094
- https://superuser.com/questions/842642/how-to-make-a-symlinked-folder-appear-as-a-normal-folder
- https://stackoverflow.com/questions/27068596/how-to-include-files-outside-of-dockers-build-context

**Comment by cnrmck** [comment]
@wlisac Then for people who do use symlinks within the directory structure that they push, how do you propose they maintain those symlinks?

**Comment by pdcastro** [comment]
I suppose we would "think twice" before making a change that breaks backwards compatibility (even having Docker compatibility as a strong argument), so I imagine (to be decided) we would end up with a command-line option to allow users to choose the behaviour they want (whether or not to preserve symlinks).

**Comment by pdcastro** [comment]
Hang on... I was somehow assuming that the standard Docker implementation (the `docker build` command) preserved symlinks, and the main reason to modify the behavior of `balena push` (with a command-line option) would be to achieve Docker compatibility in that regard. But I was testing it today and found that neither the COPY nor the ADD instructions in a Dockerfile preserve symlinks with the `docker build` command and the standard Docker daemon (version 18.06.1-ce on a Mac). The links provided by @wlisac also seem to confirm this.

I also confirmed that [balenaEngine](https://www.balena.io/engine/) (balena's implementation of the Docker daemon) behaves the same way. Even if the CLI preserved the symlinks when creating the tar stream that it sends to balenaEngine / Docker daemon, the engine/daemon then makes a copy of the linked file when executing the COPY or ADD instructions during image build time, so that the final image does **not** preserve the symlink.

So it is looking like this issue is not reasonably actionable on the CLI for `balena push`, because it would also require modifying [balenaEngine](https://www.balena.io/engine/) in a way that breaks compatibility with standard Docker. If you feel that the Docker folks are wrong to have [argued against and resisted implementing this feature for 5+ years](https://github.com/moby/moby/issues/6094) and that balenaEngine should break away implement slightly incompatible COPY and RUN Dockerfile instructions, :-) I invite you to open an issue in the [balenaEngine repo](https://github.com/balena-os/balena-engine/issues) and make your case there first. When balenaEngine implements it, we can then revisit this CLI issue and implement it here too.

**Comment by pdcastro** [comment]
> _Then for people who do use symlinks within the directory structure that they push, how do you propose they maintain those symlinks as symlinks?_

Given my previous comment, here's a workaround that I had also shared in [the original forum post](https://forums.balena.io/t/symlinks-break-when-pushing-with-local-mode-on-macos/5992/11) (copying it here for people landing on this issue from a web search).

A tgz file can be created with the symlinks, and a RUN instruction in the Dockerfile can be used to extract the symlinks on the device. Something along the lines of:
```
# create a tgz with the symlinks
find . -maxdepth 1 -type l | xargs tar cvzf mylinks.tgz
balena push 10.0.0.65
```
The Dockerfile should then extract the symlinks:
```
# Dockerfile
...
COPY mylinks.tgz ./
RUN tar xvzf mylinks.tgz
...
```

**Comment by pdcastro** [comment]
Closing (at least for now) because the requested feature appears to require changes to [balenaEngine](https://www.balena.io/engine/) that would break compatibility with the standard Docker daemon for the behaviour of the Dockerfile COPY and ADD instructions, as explained in my previous comments above.
Feel free to reopen this issue if this understanding / assumption does not seem right, or for some other good reason. :-)

**Comment by pdcastro** [comment]
> [...] neither the COPY nor the ADD instructions in a Dockerfile preserve symlinks with the `docker build` command and the standard Docker daemon (version 18.06.1-ce on a Mac).

I was recently asked about this again and I can confirm that it remains the behavior of `docker build` in November 2021, with Docker version `20.10.8`. Here's the test:

```
$ mkdir test-symlinks
$ cd test-symlinks
$ echo hi > hi.txt
$ ln -s hi.txt src.txt
$ ln -s src.txt src-src.txt
$ cat >Dockerfile <<EOF
> FROM busybox
> COPY src.txt src-src.txt .
> RUN cat src-src.txt
> RUN ls -l
> EOF

$ ls -l
total 16
-rw-r--r--  1 paulo  staff  90 20 Nov 22:29 Dockerfile
-rw-r--r--  1 paulo  staff   3 20 Nov 22:28 hi.txt
lrwxr-xr-x  1 paulo  staff   7 20 Nov 22:28 src-src.txt -> src.txt
lrwxr-xr-x  1 paulo  staff   6 20 Nov 22:28 src.txt -> hi.txt

$ docker --version
Docker version 20.10.8, build 3967b7d

$ docker build --progress plain --no-cache -t test-symlinks .
...
#5 [1/5] FROM docker.io/library/busybox@sha256:e7157b6d7ebbe2cce5eaa8cfe8aa4fa82d173999b9f90a9ec42e57323546c353
...
#6 [2/5] WORKDIR /home/root
...
#8 [3/5] COPY src.txt src-src.txt .
...
#9 [4/5] RUN cat src-src.txt
#9 0.291 hi
...
#10 [5/5] RUN ls -l
#10 0.302 total 8
#10 0.302 -rw-r--r--    1 root     root             3 Nov 20 22:28 src-src.txt
#10 0.302 -rw-r--r--    1 root     root             3 Nov 20 22:28 src.txt
#10 DONE 0.3s
...

$ docker run -it --rm test-symlinks ls -l /home/root
total 8
-rw-r--r--    1 root     root             3 Nov 20 22:28 src-src.txt
-rw-r--r--    1 root     root             3 Nov 20 22:28 src.txt

$ docker run -it --rm test-symlinks cat /home/root/src-src.txt
hi
```

Both in the output of the RUN instructions (`docker build`) and in the final image (`docker run`), we see that `src.txt` and `src-src.txt` become the _final target_ of the symlink (the contents and the file size of `hi.txt`), rather than being the symlinks themselves. Regarding the file sizes:
* `hi.txt`: file size is 3, the number of characters in string `'hi\n'`.
* `src.txt`: when it is a symlink, the file size is 6, the number of characters in string `'hi.txt'`.
* `src-src.txt`: when it is a symlink, the file size is 7, the number of characters in string `'src.txt'`.
