### ISSUE TITLE
`balena tunnel` fails with "Unable to connect: 404 Not Found" (ssh_exchange_identification)

### ISSUE THREAD

**Issue by pdcastro** [balena-io/balena-cli#1173]
Users who asked for advice on how to use standard ssh port forwarding (ssh -L) with a remote device where a direct connection is not possible (e.g. private IP addresses or blocked port numbers) were advised of the following pattern:
```
# all commands below to be run your laptop/desktop computer

balena tunnel <deviceUUID> -p 22222:4321
ssh -L 1111:www.google.com:443 -p 4321 root@127.0.0.1
curl -ik https://127.0.0.1:1111
```

In the example above, `balena tunnel` uses the balena VPN to expose the device's port 22222 (the port used by the device's sshd server) on the local machine (laptop/desktop) as port 4321. Then the `ssh` command connects to that port (127.0.0.1:4321), and the `-L` option opens port 1111 also on the local machine (laptop/desktop). When curl opens a connection to 127.0.0.1:1111, the data is tunnelled to the balenaOS device, where a connection to www.google.com:443 is established “on demand”, and traffic is forwarded between Google and curl on the laptop/desktop via the balenaOS device.

That example has always worked for me, but at least two users have come across the following errors:

On one terminal:
```
$ balena tunnel <deviceUUID> -p 22222:4321
[Info]    Tunnel to <deviceUUID>
[Info]     - tunnelling localhost:4321 to device:22222
[Info]    Waiting for connections...
```
On another terminal:
```
$ ssh -L 1111:www.google.com:443 -p 4321 root@127.0.0.1
ssh_exchange_identification: Connection closed by remote host
```
Back on the first terminal:
```
[Error]   127.0.0.1:50480 => 127.0.0.1:4321 ===> 10.240.0.215:22222 :: Unable to connect: 404 Not Found
```
* Users report that `balena ssh xxx -s` works.
* Users report that "public key authentication works because ssh to the host works".
* Users report that leaving out the `-L` option to ssh results in the same error. 
* Users confirmed that the `sshd` server on the device was indeed listening on port 22222, as reported by `netstat`.
* Users report that tunnelling port 80 instead of 22222 results in the same error.

I think (not confirmed) that `ssh_exchange_identification` is a distraction or consequence, and the key error to be investigated is the `Unable to connect: 404 Not Found` message which comes from the following line of code:

https://github.com/balena-io/balena-cli/blob/v10.1.0/lib/utils/tunnel.ts#L112

Issue originally reported at:
* https://forums.balena.io/t/ssh-port-forwarding/5772/31
* https://github.com/balena-io/balena-cli/issues/1155

**Comment by pdcastro** [comment]
@wrboyce, @richbayliss, as the experts in this area, any thoughts?

**Comment by russelhowe** [comment]
This was me, I made a silly error. I used the abbreviated device UUID as shown in the balena web UI, not the full UUID. `balena ssh` works fine with an abbreviated UUID, `balena tunnel` does not.

**Comment by pdcastro** [comment]
@russelhowe, @magiconair, FYI, CLI version 10.4.0 allows an abbreviated UUID to be used with the `balena tunnel` command. Previously, the use of an abbreviated UUID may have been the reason for the "Unable to connect: 404 Not Found" (ssh_exchange_identification) error.

**Comment by pdcastro** [comment]
I understand this issue was caused by the use of an abbreviated UUID, which is only supported with CLI version 10.4.0 and later. Closing it. If you find that his issue should be reopened, please leave a comment.
