### ISSUE TITLE
`balena push myApp` hangs on Windows

### ISSUE THREAD

**Issue by pdcastro** [balena-io/balena-cli#1182]
`balena push myApp` on Windows: after the build log stream indicates successful completion by printing the unicorn, the CLI hangs there and does not terminate by itself, until CTRL-C is typed.

Before a fix in version 10.1.1, hitting CTRL-C would also cause the release status to be changed from successful to cancelled, resulting in such a cancelled-not-really release to be deployed to devices. This was reported in this forum thread: https://forums.balena.io/t/how-to-prevent-my-container-from-being-deleted-ever/6159/10
After version 10.1.1, hitting CTRL-C no longer reverts the successful status. But it should not be necessary to hit CTRL-C in the first place.

**Comment by jezmck** [comment]
Same issue here.

**Comment by pdcastro** [comment]
In this possibly related report, the user sees "half a unicorn": https://www.flowdock.com/app/rulemotion/user_happiness/threads/AO_B2KN7yKdvXmWON1v3hkKsEDf

**Comment by pdcastro** [comment]
This issue was fixed in CLI release v11.21.3 ([releases](https://github.com/balena-io/balena-cli/releases)).
