### ISSUE TITLE
PiHole doesn't block ads, nor respond on port 80

### ISSUE THREAD

**Issue by jezmck** [balena-io/balena-cli#1210]
- **Cli version:** 10.10.1
- **Standalone install:** (unsure what this means)
- **Node version:** v10.15.3
- **Npm version:** 6.4.1
- **Operating system and architecture:** Windows 10 & RasPi 3b+

---

Following https://www.balena.io/blog/deploy-network-wide-ad-blocking-with-pi-hole-and-a-raspberry-pi/ to the letter results in a pihole which seems to be deployed fine, but refuses connections on port 80, and doesn't appear to block ads (tested with https://blockads.fivefilters.org/?pihole).

**Comment by pdcastro** [comment]
@jezmck, thank you for your interest and for reporting this issue. balena's support team, the contributors to balena's Pi-Hole blog/tutorial, and the wider community will not normally be checking this GitHub repository, which we mainly use to track specific balena CLI bugs or CLI feature requests. For this reason, I would kindly suggest that you re-posted this question on the balena forums, where I should think you will quickly get a reply: https://forums.balena.io/search?q=pi-hole%20
Thanks again!
