### ISSUE TITLE
User can't ssh to local mode device on windows 10

### ISSUE THREAD

**Issue by thgreasi** [balena-io/balena-cli#1211]
- **Cli version:** 10.8.0
- **Standalone install:** yes/no
- **Node version:**
- **Npm version:**
- **Operating system and architecture:** Windows 10

---

The following error is printed
```
λ balena local ssh 192.168.1.49
? Select a container /local-app (cf5******)
sh: $(if [ -f /usr/bin/balena ]; then echo "balena"; else echo "docker"; fi): No such file or directory
Connection to 192.168.1.49 closed.
```

**Comment by pdcastro** [comment]
@CameronDiver is rewriting the `local ssh` command for CLI version 11 (coming soon). Meanwhile, as a workaround, I'd suggest using plain ssh + balena-engine, as follows:
```
# on your laptop/desktop
$ ssh -p 22222 root@192.168.1.49

# then on the device host OS
# list the running containers
$ balena-engine ps

# open a shell on container 'main_1_1'
$ balena-engine exec -it main_1_1 /bin/sh
```
Generally, standard `ssh`, `scp` and `rsync` can be used with balena devices. See this forum comment that covers the cases of development vs production images, and local vs remote devices: https://forums.balena.io/t/rsync-over-balena-ssh-tunnel/6228/4?u=pdcastro
