### ISSUE TITLE
User wants to see the device last online timestamp in the CLI

### ISSUE THREAD

**Issue by thgreasi** [balena-io/balena-cli#1216]
Consider including it in the `balena device <uuid>` details, since it now only presents whether it's online or not.

See: https://jel.ly.fish/#/89f5e32e-a7d6-4e8c-beed-3b0bcfb6dd63

**Comment by mcamou** [comment]
This would be a good thing to have.

**Comment by pdcastro** [comment]
> just saw that it's already implemented :)

Thanks for pointing it out @mcamou, 😁   so we can close the issue :)

It's this `LAST SEEN:` field:

```
$ balena device b187...
...
IS ONLINE:          true
LAST SEEN:          2021-01-27T00:24:42.943Z
...
```
