### ISSUE TITLE
Show more detailed errors when build fails on a local device using "balena local push"

### ISSUE THREAD

**Issue by sradevski** [balena-io/balena-cli#1217]
User used `balena local push` to push code to a local device. They expected to see why a build failed when using `DEBUG=1`, but they got:
```
[Build] [imx219_driver] Step 9/12 : COPY --from=builder /usr/src/app/example_module_jetson-tx2*.prod /usr/src/app
Build error
```
The docker error seems to be due to using a wildcard in a "COPY --from" another image. The Docker error is not transmitted through the CLI though, only the generic error.

- **Cli version:**
- **Standalone install:** Irrelevant
- **Node version: ** Irrelevant
- **Npm version: ** Irrelevant
- **Operating system and architecture: ** Irrelevant

---

*Please keep in mind that we try to use the issue tracker of this repository for specific bug reports & CLI feature requests. General & troubleshooting questions are encouraged to be posted to the [balena forums](https://forums.balena.io) where the community can both contribute and benefit from the answers.*

*Before submitting this issue please check that this issue is not a duplicate. If there is another issue describing the same problem or feature please add your information to the existing issue's comments.*

**Comment by pdcastro** [comment]
More information from the user:
CLI v10.10.1, node v8.10.0
command line: `DEBUG=1 balena local push [ip-address]`

Note it seems to be "balena local push" rather than "balena push".

**Comment by pdcastro** [comment]
It has been clarified that error regarded the "balena local push" command rather than "balena push" (I've updated the issue title and description), and the user has confirmed that "balena push" provides a more informative error message than "balena local push". Given that "local push" will be deprecated in v11, we may choose to offer "balena push" (and its cool new beta feature, the `--live` option) as the "solution" for this issue.

**Comment by pdcastro** [comment]
The `local push` command was removed in CLI v11, replaced with the ["live push" feature](https://www.balena.io/blog/living-on-the-edge-with-livepush-and-other-cli-improvements/) which is enabled by default with the `balena push <ip-address>` command. See also: [Deploy to your Fleet](https://www.balena.io/docs/learn/deploy/deployment/) documentation.
