### ISSUE TITLE
User's emulated build hangs after installing qemu

### ISSUE THREAD

**Issue by thgreasi** [balena-io/balena-cli#1235]
- **Cli version:** 10.9.4 & 10.13.1
- **Standalone install:** yes & no
- **Node version:** v10.15.3
- **Npm version:**
- **Operating system and architecture:** Ubuntu 18.04

---

```
DEBUG=1 balena build . -a MyApp --emulated --logs
[Debug] Parsing input...
[Debug] Loading project...
[Debug] Resolving project...
[Info] Compose file detected
[Debug] Creating project...
[Info] Building for aarch64/jetson-tx2
[Build] Building services...
[Build] v4l2loopback_module Preparing...
[Build] camera Preparing...
[Build] recognizer Preparing...
[Build] ui Preparing...
[Build] kiosk Preparing...
[Info] Installing qemu for aarch64 emulation...
null
```

**Comment by thgreasi** [comment]
@pdcastro I might be missing something, but I don't see a v4.0.0 qemu release in https://github.com/balena-io/qemu/releases

**Comment by pdcastro** [comment]
Qemu v4.0.0 is there, you just need to click the "Next" button a few times to navigate a few release pages down. Not quite sure why it's not ordered by release number, perhaps it's ordered by commit timestamp and the the commit was created a long time ago. A direct link to the release:
https://github.com/balena-io/qemu/releases/tag/v4.0.0-balena

**Comment by pdcastro** [comment]
I and colleagues have so far been unable to reproduce this issue. The following attempt, for example, does not reproduce the issue:

* Ubuntu 18.04.2 VM from here: https://www.osboxes.org/ubuntu/
* Docker 18.09.2 installed with `apt-get install docker.io`
* Jetson TX2 test app (balena-cloud.com) called “test-tx2”
* Dockerfile using a `balenalib/jetson-tx2-alpine` base image:
```
FROM balenalib/jetson-tx2-alpine
RUN uname -a
CMD while : ; do echo "echo $(uname -a)"; sleep ${INTERVAL=5}; done
```
* [balena-cli v10.13.4](https://github.com/balena-io/balena-cli/releases/download/v10.13.4/balena-cli-v10.13.4-linux-x64.zip) (standalone zip installation)
```
root@osboxes:~/qemu-test# ../balena-cli/balena build -a test-tx2 --emulated —logs
[Info]    Creating default composition with source: /root/qemu-test
[Info]    Building for aarch64/jetson-tx2
[Build]   Building services...
[Build]   main Preparing...
[Info]    Installing qemu for aarch64 emulation...
[Info]    Emulation is enabled
[Build]   main Step 1/4 : FROM balenalib/jetson-tx2-alpine
[Build]   main  ---> cd8157dc492b
[Build]   main Step 2/4 : COPY [".balena/qemu-execve","/tmp/qemu-execve"]
[Build]   main  ---> 56a0b4e300c9
[Build]   main Step 3/4 : RUN ["/tmp/qemu-execve","-execve","/bin/sh","-c","uname -a"]
[Build]   main  ---> Running in 3b5cef2c0a45
[Build]   main Linux e3f7b372240f 4.18.0-15-generic #16~18.04.1-Ubuntu SMP Thu Feb 7 14:06:04 UTC 2019 aarch64 Linux
[Build]   main Removing intermediate container 3b5cef2c0a45
[Build]   main  ---> 60b0165fb5f6
[Build]   main Step 4/4 : CMD while : ; do echo "echo $(uname -a)"; sleep ${INTERVAL=5}; done
[Build]   main  ---> Running in 2716d0eccf69
[Build]   main Removing intermediate container 2716d0eccf69
[Build]   main  ---> bef816a33637
[Build]   main Successfully built bef816a33637
[Build]   main Successfully tagged qemu-test_main:latest
[Success] Build succeeded!
```

**Comment by pdcastro** [comment]
Unable to reproduce, and a few qemu/emulation related fixes were made in CLI v11. If you are still facing this issue, please add a comment and we will reopen the issue and investigate it further.
