### ISSUE TITLE
balena apps has empty device & online device counts

### ISSUE THREAD

**Issue by thgreasi** [balena-io/balena-cli#1238]
Placeholder issue
See: https://www.flowdock.com/app/rulemotion/r-product/threads/ng1cG4x88xdPYR67_L6wFJa3Khh

**Comment by pdcastro** [comment]
* Implemented by PR #1239
* Related to issue #1241

**Comment by thgreasi** [comment]
Oh my... I was again using connects-to instead of resolves... Sorry @pdcastro
