### ISSUE TITLE
balena preload: "Release not found" when the commit value is "latest"

### ISSUE THREAD

**Issue by pdcastro** [balena-io/balena-cli#1243]
CLI counterpart to the balena-preload issue: https://github.com/balena-io/balena-preload/issues/204

`balena preload --commit latest` fails with "Release not found"

Known workaround: specify a commit hash value instead of the word "latest", e.g.:

`balena preload --commit 267408b`

This is believed to have been introduced by the following PR merged around 10 May 2019, and would affect several CLI versions that were installed via "npm install" since that date:
https://github.com/balena-io/balena-preload/pull/201/files

**Comment by Page-** [comment]
@pdcastro the correct way to do it would be to use `balena preload` since if you don't specify a commit then it'll default to the application commit which will be the current release (and also the latest unless using staged-releases to delay roll outs)

**Comment by pdcastro** [comment]
Thanks @Page-. I've tested omitting the `--commit` option and in this case the CLI presents an interactive menu with releases to choose from, including an option labeled "latest". If I select the "latest" option then indeed it works, but it's a different behaviour than `--commit latest` because the latter does not invoke an interactive menu and thus can be scripted.

If I edit the CLI’s `package.json` to pin `balena-preload` to version 8.1.1, then `--commit latest` does not raise any errors, nor raises an interactive menu. That’s how I narrowed the issue down to that PR. @zvin has pointed out that `--commit latest` selects the "application commit", not necessarily really the "latest" release:
https://github.com/balena-io/balena-cli/blob/master/lib/actions/preload.coffee#L289

**Comment by Page-** [comment]
Yeah, I was basing it on if you don't pass a commit to balena-preload, but the cli interacts heavily with the balena-preload internals whilst mid-process so it doesn't act in the same way when going via the cli

**Comment by pdcastro** [comment]
@zvin, reopening the issue because I am still getting "`Release not found`" with CLI v10.13.5 and `balena-preload` v8.1.4 if I use `--commit current`:
```
$ ./bin/balena-dev preload test.img --app test-rpi --commit current
Building Docker preloader image. [========================] 100%

| Creating preloader container
- Starting preloader container
| Fetching application test-rpi
| Reading image information
Release not found: fbeae9ac25cbf6c808f7d1905c26a38c
```
However it works if I use `--commit latest`:
```
$ ./bin/balena-dev preload ~/Downloads/dev-test-rpi-raspberrypi3-2.32.0+rev1-dev-v9.14.0.img --app test-rpi --commit latest
Building Docker preloader image. [========================] 100%

/ Creating preloader container
/ Starting preloader container
- Fetching application test-rpi
/ Reading image information
\ Resizing partitions and waiting for dockerd to start
Pulling 1 image [========================] 100%
- Cleaning up temporary files```
```

**Comment by zvin** [comment]
@pdcastro https://github.com/balena-io/balena-cli/pull/1248
