### ISSUE TITLE
macOS CLI installer can't be opened because it is from an unidentified developer

### ISSUE THREAD

**Issue by pdcastro** [balena-io/balena-cli#1251]
The native / executable CLI installer for macOS is interrupted by a dialog that says the installer _"can't be opened because it is from an unidentified developer"._ We are investigating how to get the installer digitally signed in our continuous integration builds. Meanwhile, the following screenshots show how to get past that pop-up dialog:

![gatekeeper1](https://user-images.githubusercontent.com/15091591/58212295-3aa93200-7ce6-11e9-8a84-640a10aa61ba.png)
Open System Preferences by clicking on the Apple menu at the top left corner of the screen:

<img width="235px" alt="apple_menu" src="https://user-images.githubusercontent.com/15091591/58212302-3e3cb900-7ce6-11e9-9fae-d531d23d67b6.jpg"/>
<img width="672" alt="system_preferences" src="https://user-images.githubusercontent.com/15091591/58212308-439a0380-7ce6-11e9-8113-ae3e7620e318.png"/>

![security_and_privacy](https://user-images.githubusercontent.com/15091591/58212316-472d8a80-7ce6-11e9-8b6a-a87857c88e05.jpg)
![gatekeeper2](https://user-images.githubusercontent.com/15091591/58212321-4ac11180-7ce6-11e9-9d6c-a04eabaa06f1.png)

**Comment by pdcastro** [comment]
"Signing Your Apps for Gatekeeper": https://developer.apple.com/developer-id/

**Comment by zrzka** [comment]
Related issue https://github.com/balena-io/balena/issues/1605
