### ISSUE TITLE
Support environment variables with balena push <deviceip>

### ISSUE THREAD

**Issue by CameronDiver** [balena-io/balena-cli#1255]
Currently the only way to change environment variables on a local push is to change the docker-compose file, which isn't ideal.

These can be done outside of the secrets/args work, as they don't use the same infrastructure.

---

*Please keep in mind that we try to use the issue tracker of this repository for specific bug reports & CLI feature requests. General & troubleshooting questions are encouraged to be posted to the [balena forums](https://forums.balena.io) where the community can both contribute and benefit from the answers.*

*Before submitting this issue please check that this issue is not a duplicate. If there is another issue describing the same problem or feature please add your information to the existing issue's comments.*

**Comment by danielmahon** [comment]
This is great! 🎉 

I'm sure you've already thought about it, but it would also be helpful to allow a file path to be passed. So you could get something like:
```
$ balena push 10.0.0.1 --env ./.env --env my-service:./my-service/.env
//or
$ balena push 10.0.0.1 --envfile ./.env --envfile my-service:./my-service/.env
```

**Comment by CameronDiver** [comment]
This is a great idea, and in fact something @shaunmulligan has been talking about for a while.

The only thing that worries me is keeping things cohesive between our different deployment mechanisms - e.g. if we support env files with a push to a local device, the why not on a push to the cloud for example, or on `balena deploy`.
