### ISSUE TITLE
Balena push should convert windows line endings to unix

### ISSUE THREAD

**Issue by CameronDiver** [balena-io/balena-cli#1273]
Based on this thread: https://forums.balena.io/t/pihole-webinterface-not-reachable/12491/24 it can clearly cause some confusion in users. Given it's such a simple task I think the CLI should do it (with a switch to turn it off, in case some users code relies on windows line endings for whatever reason).

---

*Please keep in mind that we try to use the issue tracker of this repository for specific bug reports & CLI feature requests. General & troubleshooting questions are encouraged to be posted to the [balena forums](https://forums.balena.io) where the community can both contribute and benefit from the answers.*

*Before submitting this issue please check that this issue is not a duplicate. If there is another issue describing the same problem or feature please add your information to the existing issue's comments.*

**Comment by pdcastro** [comment]
Note: the current implementation, released in CLI version 1.25.0 (a semver 'minor' release), is "conservative" in relation to backwards compatibility, introducing a new command-line option `--convert-eol` (eol = end of line) that needs to be explicitly used in order for CRLF → LF (Windows → Unix) conversion to take place. But even if that option is not used, CRLF is still detected and warning messages are printed:
```text
[Warn] CRLF (Windows) line endings detected in file: <path>
...
[Warn] Windows-format line endings were detected in some files. Consider using the `--convert-eol` option.
```

We are planning to make `--convert-eol` the default behaviour in the next 'major' (semver) release of the CLI (likely v12).
