### ISSUE TITLE
Cannot SSH into device with fully numerical short UUID

### ISSUE THREAD

**Issue by imrehg** [balena-io/balena-cli#1302]
- **Cli version:** 11.0.7
- **Standalone install:** no
- **Node version:** v11.15.0
- **Npm version:** 6.9.0
- **Operating system and architecture:** ArchLinux

`balena ssh SHORTUUID -s` to one of my devices don't work as I would expect. The short UUID is `2851996` and other devices I can reach with short UUID, also `balena device` works with the same short UUID.

```
~> balena device 2851996
== RED CLOUD
ID:                 1624128
DEVICE TYPE:        raspberry-pi
STATUS:             idle
IS ONLINE:          true
IP ADDRESS:         192.168.1.171
APPLICATION NAME:   gitlabpi
UUID:               285199648cc26e08d5991fed5f461c9f
COMMIT:             647ef8a47cdd6b8c2b5dd263e71fcfad5dc17943
SUPERVISOR VERSION: 9.14.0
IS WEB ACCESSIBLE:  false
OS VERSION:         balenaOS 2.32.0+rev1
DASHBOARD URL:      https://dashboard.balena-cloud.com/devices/285199648cc26e08d5991fed5f461c9f/summary

~> balena ssh 2851996 -s
BalenaDeviceNotFound: Device not found: 2851996

Additional information may be available by setting a DEBUG=1 environment
variable: "set DEBUG=1" on a Windows command prompt, or "export DEBUG=1"
on Linux or macOS.

If you need help, don't hesitate in contacting our support forums at
https://forums.balena.io

For bug reports or feature requests, have a look at the GitHub issues or
create a new one at: https://github.com/balena-io/balena-cli/issues/

exit 1
```

I think it is because the short UUID is fully numerical, and thus it is understood as device ID instead of UUID? Trying different shortening of the UUID, as soon as it's hex, not fully numerical, it works (ie. shortening the full UUID `285199648cc26e08d5991fed5f461c9f` to `285199648` still fails, but including the next char `285199648c` then works....

```
~> balena ssh 285199648 -s                       
BalenaDeviceNotFound: Device not found: 285199648

Additional information may be available by setting a DEBUG=1 environment
variable: "set DEBUG=1" on a Windows command prompt, or "export DEBUG=1"
on Linux or macOS.

If you need help, don't hesitate in contacting our support forums at
https://forums.balena.io

For bug reports or feature requests, have a look at the GitHub issues or
create a new one at: https://github.com/balena-io/balena-cli/issues/

exit 1
~> balena ssh 285199648c -s
=============================================================
    Welcome to balenaOS
=============================================================
root@2851996:~# 
```

---

*Please keep in mind that we try to use the issue tracker of this repository for specific bug reports & CLI feature requests. General & troubleshooting questions are encouraged to be posted to the [balena forums](https://forums.balena.io) where the community can both contribute and benefit from the answers.*

*Before submitting this issue please check that this issue is not a duplicate. If there is another issue describing the same problem or feature please add your information to the existing issue's comments.*

**Comment by pdcastro** [comment]
Discussion thread: https://www.flowdock.com/app/rulemotion/resin-frontend/threads/5Ix7ioFp6eL3kHzZ8Og5Ny6QSZU
