### ISSUE TITLE
11.2.1 balena preload fails

### ISSUE THREAD

**Issue by mlilien** [balena-io/balena-cli#1306]
- 11.2.1
- Standalone install: yes
- Linux debian / amd64

Building Docker preloader image. [                        ] 0%
TypeError: stat.isSocket is not a function
    at onstat (/snapshot/balena-cli/node_modules/balena-preload/node_modules/tar-fs/index.js:103:14)
    at /snapshot/balena-cli/node_modules/balena-preload/node_modules/tar-fs/index.js:32:39
    at zalgoSafe (pkg/prelude/bootstrap.js:261:10)
    at pkg/prelude/bootstrap.js:901:9
    at pkg/prelude/bootstrap.js:337:5
    at pkg/prelude/bootstrap.js:315:14
    at FSReqWrap.wrapper [as oncomplete] (fs.js:603:17)
[ERROR] failed to execute task "base_preload-application:": exited with non-zero status code 1

**Comment by pdcastro** [comment]
Thank you for reporting this issue. I was able to reproduce it and I have found that CLI version `10.16.0` is latest version not affected by the issue, so until we fix it for the latest version (very soon), I recommend using version `10.16.0` for the preload command on Linux. The standalone zip for that version can be downloaded at:
https://github.com/balena-io/balena-cli/releases/download/v10.16.0/balena-cli-v10.16.0-linux-x64.zip

**Comment by pdcastro** [comment]
Further investigation has narrowed the issue down to an upstream dependency ([pkg](https://www.npmjs.com/package/pkg)), and PR was created to fix it: https://github.com/zeit/pkg/pull/720

We have also determined that the issue does not affect `npm` installations of `balena-cli` (any versions), which is thus also a potential workaround for the issue:
https://github.com/balena-io/balena-cli/blob/master/INSTALL.md#npm-installation

**Comment by pdcastro** [comment]
This issue was fixed in [CLI v11.3.6 and later](https://github.com/balena-io/balena-cli/releases). Upstream is yet to accept our pull request ([zeit/pkg#720](https://github.com/zeit/pkg/pull/720)), but meanwhile we've patched their source in balena CLI. Many thanks to the reporters and to @zvin for the investigation and fix. 👍
