### ISSUE TITLE
Consider switching global-tunnel-ng to global-agent

### ISSUE THREAD

**Issue by gajus** [balena-io/balena-cli#1335]
`global-tunnel-ng` used in this package [does not work in Node v11 and above](https://github.com/np-maintain/global-tunnel#global-tunnel).

If you require a global proxy, consider switching to https://github.com/gajus/global-agent.

The required setup is:

```js
import {
  createGlobalProxyAgent
} from 'global-agent';

createGlobalProxyAgent({
  environmentVariableNamespace: '',
  forceGlobalAgent: true
});

```

**Comment by pdcastro** [comment]
Thanks for reporting this! We intend to support Node 12 (currently we recommend Node 8 or Node 10) and this issue sounds like a pre-requisite.
