### ISSUE TITLE
Include sshKeys in os configure

### ISSUE THREAD

**Issue by mwohlert** [balena-io/balena-cli#1340]
When supplying a config.json with sshKeys in it, they are not written onto the ssh partition, since they are omitted while generating the config, that is written onto the sd card.

@CameronDiver Since you pointed me to the correct spots on the pr with balena-supervisor. I would like to help here aswell, since we also have the need to have this working.

My investigation so far:
os configure, calls generateApplicationConfig or generateDeviceConfig in config.ts and they call generateBaseConfig, which calls balena.sdk model.os.getConfig, this config does of course not have any ssh keys in it.
My idea is to add the sshKeys to the config outputted by generateBaseConfig, when they are specified in the options.

**Comment by pdcastro** [comment]
Thanks for PR @mwohlert ! Merged and [released as CLI v11.6.0](https://github.com/balena-io/balena-cli/releases).

**Comment by MBerka** [comment]
This one absolutely saved production deployability by making it possible to stop manually adding the keys to the disk image. Thank you.

**Comment by ashwinvandijk** [comment]
I'm not sure if I'm missing something here, or what I want to do isn't possible. I'd like to issue a command to create a config, with a specified ssh-key already in there. Is there a way to do this?
