### ISSUE TITLE
balena push <application> never completes

### ISSUE THREAD

**Issue by adamlee-ARC** [balena-io/balena-cli#1342]
- **balena CLI version:** 11.6.0
- **Operating system version:** Windows 10
- **32/64 bit OS and processor:** 64bit
- **Install method:** honestly can't remember

---

When doing balena push <application> via Git Bash the command doesn't fully complete and I am forced to kill it every time. Before killing I receive the following message:

_Received SIGINT, cleaning up. Please wait._

My builds are succeeding despite this issue. This happens on every single push. Nothing interesting shows up with DEBUG=1.

**Comment by pdcastro** [comment]
Related to issue #1182

**Comment by pdcastro** [comment]
This issue was fixed in CLI release v11.21.3 ([releases](https://github.com/balena-io/balena-cli/releases)).
