### ISSUE TITLE
Should bump the SDK to the one using the /v6 endpoint

### ISSUE THREAD

**Issue by thgreasi** [balena-io/balena-cli#1348]
Placeholder milestone issue.
Specifically the changes from https://github.com/balena-io/balena-sdk/pull/621

**Comment by srlowe** [comment]
@pdcastro This one is old I think?

**Comment by pdcastro** [comment]
@srlowe yes, from the balena SDK changelog I gather that the `/v6` endpoint is used in SDK v14, and the CLI is now using SDK v15. Closing it.
