### ISSUE TITLE
balena push: Could not detect project type: Resolution could not be performed

### ISSUE THREAD

**Issue by pdcastro** [balena-io/balena-cli#1352]
***If you arrived here because you're getting "Resolution could not be performed":***
* Check that you are running `balena push` on the project folder, i.e. run "cd _&lt;folder&gt;_" before running "`balena push`".
* Alternatively, use the "`-s`" command-line option:
```
--source, -s <source>   The source that should be sent to the balena builder
                        to be built (defaults to the current directory)
```
<hr>

Despite this issue's title sounding like a bug, this issue is actually a feature request. (Well, unless you apply a loose definition of "bug".)

If the `-s` option is not provided, `balena push` will use the current working directory as the project folder. It then creates a tar stream of the project folder (including subfolders) and send it to the balenaCloud builders. One of the early processing checks that the builder performs is "resolving" the type of project: single container, `Dockerfile.template`, multicontainer, simple Node.js project..., by looking for a `Dockerfile`, `Dockerfile.template`, `docker-compose.yml` or `package.json` file at the root of the project folder.

Sometimes, however, the user forgets to "cd" to the project folder, and runs `balena push` in some random folder, like "Downloads" or their homedir. In this case, the result is:

* A huge tar stream may be created (possibly gigabytes: the whole of the user's homedir...) and uploaded to the balenaCloud builder. This takes a lot of RAM memory on the user's laptop and also on the balenaCloud builder, and uses a lot of network bandwidth.
* The builder does not find a Dockerfile at the root of the project folder, and replies with: _"[Error] Could not detect project type: Resolution could not be performed"_
* The user contacts balena support asking for help.
* Support agents ask the user a bunch of debugging questions and forward the thread around, until it reaches someone who came across the error enough times to realise what is going on...

So the feature request is for the CLI to perform an early local project resolution before creating the tar stream, and print a user-friendly error message like _"Dockerfile not found, have you cd'ed to the project folder?"_

**Comment by mrjogo** [comment]
Note that this also occurs if you put the Dockerfile into the .dockerignore

**Comment by pdcastro** [comment]
The error message _(Resolution could not be performed)_ was changed a little while ago to something closer to _"Dockerfile not found",_ however it is still reported in the server side, thus after the local folder has been uploaded. There is another issue, #1421 [Run sanity project checks before push / deploy / build commands](https://github.com/balena-io/balena-cli/issues/1421), for the CLI to make local checks before the local folder is uploaded. Closing this issue in favour of that one.
