### ISSUE TITLE
'balena help' hides too much behind the verbose flag

### ISSUE THREAD

**Issue by kazazes** [balena-io/balena-cli#1358]
- **balena CLI version:** 11.7.2
- **Operating system version:** macOS
- **32/64 bit OS and processor:** 42 Qubit
- **Install method:** Executable

---

I've been using balena-cli for months and still use the help verb all the time. It's a powerful tool, so why are all the best commands hidden behind a (not even shorthand!) `--verbose` flag?

If length is the issue, breaking the  `config`, `device` and `os` commands into subgroups like `balena help config` would be a quick fix.

 I've found more than a few features I didn't know the cli tool had below the fold.

**Comment by pdcastro** [comment]
Related to #694, #1343

**Comment by pdcastro** [comment]
CC: @srlowe because of recent discussions on `balena help` conversion to oclif

**Comment by srlowe** [comment]
Closing, as now there is clearer info about listing the extra commands, which are available using short `-v` flag.
