### ISSUE TITLE
inconsistent documentation 

### ISSUE THREAD

**Issue by ofirule** [balena-io/balena-cli#1371]
Here you say we should use node.js 6.x
https://www.balena.io/os/docs/raspberrypi3/getting-started/

but here you say we should use node.js 8.x or 10.x: 
https://github.com/balena-io/balena-cli/blob/master/INSTALL.md

**Comment by thgreasi** [comment]
@ofirule Thanks for bringing this up.
I will open an internal issue to track updating the OS getting started instructions.

**Comment by pdcastro** [comment]
I think the getting started guide (first link), section "Install the Balena CLI", should consist of a link to the INSTALL.md file (second link).

**Comment by ofirule** [comment]
Also thee ssh command in the BalenaOS manual is not updated 

```
$ sudo balena local ssh mydevice.local --host
Note: the command "balena local ssh" was replaced in CLI version v11.0.0.
Please use "balena ssh" instead.

Additional information may be available by setting a DEBUG=1 environment
variable: "set DEBUG=1" on a Windows command prompt, or "export DEBUG=1"
on Linux or macOS.

If you need help, don't hesitate in contacting our support forums at
https://forums.balena.io

For bug reports or feature requests, have a look at the GitHub issues or
create a new one at: https://github.com/balena-io/balena-cli/issues/
```

**Comment by xginn8** [comment]
Fixed by removing any install instructions from  https://www.balena.io/os/docs/raspberrypi3/getting-started/ (instead just referring to the CLI install instructions directly)
