### ISSUE TITLE
CLI package for Mac needs to be notarized

### ISSUE THREAD

**Issue by imrehg** [balena-io/balena-cli#1376]
> Beginning in macOS 10.14.5, all new or updated kernel extensions and all software from developers new to distributing with Developer ID must be notarized in order to run. Beginning in macOS 10.15, notarization is required by default for —> all software <—.

https://developer.apple.com/documentation/security/notarizing_your_app_before_distribution

Flowdock conversation: https://www.flowdock.com/app/rulemotion/pub/threads/z-DZbL4S5TKBxsH3l0eV8w3QVfg

**Comment by pdcastro** [comment]
Closing this issue in favour of #1479 (macOS Catalina: balena-cli can't be opened because Apple cannot check it for malicious software)
