### ISSUE TITLE
Update insecure packages

### ISSUE THREAD

**Issue by LucianBuzzo** [balena-io/balena-cli#1384]
`npm i` gives the message

```
found 242 vulnerabilities (27 low, 1 moderate, 213 high, 1 critical)
```

We should try to resolve as many of these as possible.

**Comment by pdcastro** [comment]
On this topic, some `balena` commands also result in `Buffer()` warnings being printed to the console (reported by @CameronDiver in [flowdock](https://www.flowdock.com/app/rulemotion/resin-frontend/threads/fpYFKpCm2eWF7dEubEztdD1Uo2O)):
```
(node:30588) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(node:30588) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
```
I didn't find any occurrence in `balena-cli` itself, but a grep of node_modules returned 1625 occurrences:
```
$ grep -R ' Buffer(' node_modules | wc -l
    1625
```
Trying to isolate "balena's own code" in the output above, I identified the following three balena libraries that we could act on first:
```
resin-bundle-resolve
balena-request
balena-sdk
```

**Comment by srlowe** [comment]
The critical vuln has been removed already at some point. Currently:

`found 249 vulnerabilities (27 low, 1 moderate, 221 high)`

**Comment by Page-** [comment]
#1645 fixes all of the vulnerabilities in production dependencies (`npm audit --production`), there are still some remaining in dev dependencies but they're never shipped to users :)

**Comment by Page-** [comment]
#1645 has now been merged so there's no insecure production dependencies
