### ISSUE TITLE
Homogenise oclif action loading

### ISSUE THREAD

**Issue by LucianBuzzo** [balena-io/balena-cli#1391]
see https://github.com/balena-io/balena-cli/pull/1383#discussion_r312458518

Currently to add a new oclif command to the CLI you need modify lines in:
- `help_ts.ts`
- `app.ts`
- `oclif-utils.ts`
- `capitanodoc.ts`

This situation could be improved so that is simpler and cleaner to add new commands in oclif

**Comment by pdcastro** [comment]
FYI, I'm actually doing some of this work at the moment, as part of the implementation of some other features. PR to follow soon.
