### ISSUE TITLE
Balena SSH: "Error: Missing applicationOrDevice"

### ISSUE THREAD

**Issue by evanlesmez** [balena-io/balena-cli#1401]
- balena version 11.8.2
- ubuntu 19.04
- 64 bit OS and Intel® Core™ i5 CPU M 560 @ 2.67GHz × 4
- zip installer
---
balena login success then 
Running balena ssh gives me this error -> 
```

Error:` Missing applicationOrDevice
    at /snapshot/versioned-source/node_modules/capitano/build/signature.js:150:29
    at _setImmediate (/snapshot/versioned-source/node_modules/capitano/node_modules/async/lib/async.js:181:20)
    at Immediate.iterate [as _onImmediate] (/snapshot/versioned-source/node_modules/capitano/node_modules/async/lib/async.js:262:13)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at process.topLevelDomainCallback (domain.js:120:23)

If you need help, don't hesitate in contacting our support forums at
https://forums.balena.io

For bug reports or feature requests, have a look at the GitHub issues or
create a new one at: https://github.com/balena-io/balena-cli/issues/'
```

**Comment by pdcastro** [comment]
@evanlesmez, I have not been able to reproduce the issue using the same CLI version (11.8.2 zip installer) and OS (Ubuntu 19.04, 64-bit Intel Core i5):

```
$ ./balena-cli-11.8.2/balena ssh 6712b3d712d4b5299b23550ee2e405b1
Enter passphrase for key '/root/.ssh/id_rsa':
=============================================================
    Welcome to balenaOS
=============================================================
root@6983a3f:~#
```
Could you share the full command line you were running?

**Comment by evanlesmez** [comment]
It was just `balena ssh `which for me errors out but I lookedt through the docs some more & tried specifying an app name & it worked. for me using `balena ssh {app-name}` gave me the list of devices within that app from which I could connect. I also tried with a specific uuid and it worked fine. Should `balena ssh` defualt to one of your apps if you have on? If not the output should probably say 'make sure to specify an app or uuid such as ex. balena ssh myApp' rather than just an error message.

**Comment by evanlesmez** [comment]
`balena ssh `
