### ISSUE TITLE
`balena login` should convenience-open the signup page if `I don't have a balena account!` is selected

### ISSUE THREAD

**Issue by xginn8** [balena-io/balena-cli#1417]
This action already occurs if authenticating via the web dashboard, so it seems reasonable to extend for new signups.

**Comment by srlowe** [comment]
Hey @xginn8 I just tested this, and it seems to already open the signup page.  Did it not for you?  May be a platform-specific bug.

Just to make sure we're on the same page, the steps I took were:
 - Logout from web dashboard.
 - run `balena login`, and select `I don't have a balena account!`
 - I then get a 'please sign up at...' message, and shortly after the browser opens at the signup page.

(The message in the shell is presented as an error though, which is not right (ie. it gives info about debug env var))

**Comment by xginn8** [comment]
@srlowe thanks for looking into this. I've just retested with 11.23.0 and it seems to work now, though I agree that writing to stderr is misleading in this case!

**Comment by srlowe** [comment]
@xginn8 Ah good. There have been some changes to the error handling code since Nov, so my guess is that previously the error was inhibiting the browser launch somehow.  I'll close this and open a new issue about the message.

**Comment by srlowe** [comment]
Opened #1597
