### ISSUE TITLE
`balena os download` does not let you download a development image

### ISSUE THREAD

**Issue by hedss** [balena-io/balena-cli#1426]
- **balena CLI version:** 11.9.5
- **Operating system version:** macOS 10.14.5
- **32/64 bit OS and processor:** 64-bit Intel processor
- **Install method:** npm
- **If npm install, Node.js and npm version:** Node v10.16.0 and npm v6.9.0

`balena os download` only allows the download of a production image. There's no good reason why we shouldn't allow the download of a development image, especially as engineers are more likely to be using balenaCLI to do downloads as part of developing their CI/CD/manufacturing process, where they'd want to use development images.

**Comment by pdcastro** [comment]
Related to #724 (Split the dev/prod OS download version options, similarly to the UI)

**Comment by srlowe** [comment]
Dev versions can now be downloaded either through the `--os-version menu` option, or by appending `.dev` to version.
