### ISSUE TITLE
`balena join` states devices can't be moved between applications

### ISSUE THREAD

**Issue by hedss** [balena-io/balena-cli#1429]
- **balena CLI version:** 11.9.5
- **Operating system version:** macOS 10.14.5
- **32/64 bit OS and processor:** 64-bit Intel processor
- **Install method:** npm
- **If npm install, Node.js and npm version:** Node v10.16.0 and npm v6.9.0

The help text states:
```
Usage: join [deviceIp]
...
Moving a device between applications on the same server is not supported.
```
This is not true, as `balena device move` does exactly this. Description needs updating.

**Comment by pdcastro** [comment]
> Moving a device between applications on the same server is not supported.

I _guess_ it was meant that the `balena join` command cannot be used for that purpose. So perhaps it could be reworded as:

> To move a device between applications on the same server, use the `balena device move`
command instead of `balena join`.

@hedss, does it match your understanding? Thanks!

**Comment by hedss** [comment]
@pdcastro Sounds like a great text change to me! :)
