### ISSUE TITLE
`balena join` lists all applications and not just those of the relevant device type

### ISSUE THREAD

**Issue by hedss** [balena-io/balena-cli#1431]
- **balena CLI version:** 11.9.5
- **Operating system version:** macOS 10.14.5
- **32/64 bit OS and processor:** 64-bit Intel processor
- **Install method:** npm
- **If npm install, Node.js and npm version:** Node v10.16.0 and npm v6.9.0

When using `balena move`, only applications of the same device type as the device being moved are listed by the interactive menu. This ensures a device doesn't join an application whose code it wouldn't be able to run.

`balena join` however does not, and lists all applications. Here's an example of a device of type `fincm3`:
```
BALENARC_DATA_DIRECTORY=. balena join 192.168.1.171
? Select application (Use arrow keys)
❯ heds/artik530
  heds/orangepi
  heds/stagingcliapp
  heds/switchapp
  heds/vpn-changed
```
This list is interesting in that it's not *all* the apps available for the account on the staging environment, and I suspect the reason is `balena join` is doing this via architecture (ie. `armv7hf` is the common factor here) rather than type. It should probably be type.

**Comment by dfunckt** [comment]
`balena move` is the one that needs fixing here -- `join` shows all apps for device types with the same underlying architecture, but `move` doesn't apparently.

**Comment by thgreasi** [comment]
Discussed that on FD @dfunckt , here is the outcome.
See: https://github.com/balena-io/balena-cli/pull/1434

**Comment by thgreasi** [comment]
On the other hand @dfunckt  it seems that balena join doesn't allow joining a compatible arch application.
After #1434 gets merged, I think `balena join` should use the same mechanism and allow `join`ing a compatible arch app (eg: an RPi4 joins and RPi3 app).

**Comment by dfunckt** [comment]
Given #1433, let's close this.

**Comment by dfunckt** [comment]
Yes @thgreasi it doesn't know about compatible archs -- it just matches them literally.
