### ISSUE TITLE
`balena join` does not allow the non-interactive setting of the update period

### ISSUE THREAD

**Issue by hedss** [balena-io/balena-cli#1432]
- **balena CLI version:** 11.9.5
- **Operating system version:** macOS 10.14.5
- **32/64 bit OS and processor:** 64-bit Intel processor
- **Install method:** npm
- **If npm install, Node.js and npm version:** Node v10.16.0 and npm v6.9.0

When `join`ing a new environment from an unmanaged device, there is no way of specifying the update period non-interactively. This makes automating this from balenaCLI awkward.

**Comment by pdcastro** [comment]
> specifying the update period

@hedss, just confirming, this refers to the `appUpdatePollInterval` field in `config.json`, right? For which the interactive prompt is something like `? Check for updates every X minutes (10)`.
Thanks!

**Comment by hedss** [comment]
@pdcastro Heya Paulo, yep that's exactly it!
