### ISSUE TITLE
`balena app/device {ID} --view` option to open application/device panel from cli

### ISSUE THREAD

**Issue by peterblazejewicz** [balena-io/balena-cli#1440]
- **balena CLI version:** e.g. 11.2.1 (output of the `"balena version"` command)
n/a
- **Operating system version:** e.g. Windows 10, Ubuntu 18.04, macOS 10.14.5
n/a
- **32/64 bit OS and processor:** e.g. 32-bit Windows on 64-bit Intel processor
n/a
- **Install method:** npm or zip or executable installer
n/a
- **If npm install, Node.js and npm version:** e.g. Node v8.16.0 and npm v6.4.1
n/a
---

I'd like to request a command similar to `npm` `view`, to allow quickly open a dashboard panel for the app from the CLI app:

Scenario:

```bash
balena apps
ID      APP NAME             DEVICE TYPE     ONLINE DEVICES DEVICE COUNT
.....
```
pick ID:

```bash
balena app {ID} --view
```

It shall start the url with like:
> https://dashboard.balena-cloud.com/apps/{ID}/

which resolves to address like:
https://dashboard.balena-cloud.com/apps/1509151/devices

Similary for the device scenario:

```bash
balena devices
ID      UUID    DEVICE NAME DEVICE TYPE     APPLICATION NAME     STATUS IS ONLINE SUPERVISOR VERSION OS VERSION           DASHBOARD URL
....
```

pick ID (which is a short hash, instead of the long one used for current dashboard url):
```bash
balena device {ID} --view
```

Or maybe, just extend the information about the apps with the url link similar to devices information (and short hash ID works)

Thanks!

**Comment by pdcastro** [comment]
@peterblazejewicz, thank you for this suggestion. It's a nice idea!
Normally we tend to prioritise work on fixing bugs and adding high-demand features, but every now and then there's a push / project on usability and then this kind of suggestion gets implemented. And of course, anyone in the community is welcome to [contribute](https://github.com/balena-io/balena-cli/blob/master/CONTRIBUTING.md) at any time!
