### ISSUE TITLE
Balena push --env doesn't support multi-line env variables

### ISSUE THREAD

**Issue by krasi-georgiev** [balena-io/balena-cli#1442]
11.11.2
linux with zip installation

This doesn't work and throws an error. I need this to pass config variables to a service.

```
export CONFIG="line1
line2"

balena push --env CONFIG="$CONFIG" 192.168.0.113
```

more discussions
https://forums.balena.io/t/how-should-the-docker-compose-variables-work/32628/5?u=krasi-georgiev

**Comment by pdcastro** [comment]
Related to balena supervisor issues:
* [Better handle spaces and other special characters in environment variables](https://github.com/balena-io/balena-supervisor/issues/748)
* [Allow dots in environment variable names](https://github.com/balena-io/balena-supervisor/issues/1104)
