### ISSUE TITLE
`config inject/read` fail due to `sudo` calls not working correctly

### ISSUE THREAD

**Issue by hedss** [balena-io/balena-cli#1443]
- **balena CLI version:** 11.11.2
- **Operating system version:** macOS 10.14.5
- **32/64 bit OS and processor:** 64-bit Intel processor
- **Install method:** npm
- **If npm install, Node.js and npm version:** Node v10.16.0 and npm v6.9.0

Both of these commands list the help text instead of attempting to execute correctly. Suspect it's similar to the underlying issue for #1428.

**Comment by pdcastro** [comment]
@hedss, I've just tested `config inject` and `config read` on macOS (10.14.6) and it worked OK, so I think it was fixed at same time as `os initalize` with PR #1455. It also worked OK on Linux. As for Windows, `config inject` failed as described in issue #785 that remains open.
Please confirm that it now also works for you, in which case this issue can be closed. Thanks!

**Comment by hedss** [comment]
@pdcastro Works for me, I'm going to close. Thanks :)
