### ISSUE TITLE
Balena push/build fails to understand code as a multicontainer project

### ISSUE THREAD

**Issue by imrehg** [balena-io/balena-cli#1445]
- **balena CLI version:** 11.11.2
- **Operating system version:** ArchLinux
- **32/64 bit OS and processor:** 64-bit
- **Install method:** npm
- **If npm install, Node.js and npm version:*

```
~> npm version  
{
  npm: '6.11.3',
  ares: '1.15.0',
  brotli: '1.0.7',
  cldr: '35.1',
  http_parser: '2.8.0',
  icu: '64.2',
  llhttp: '1.1.4',
  modules: '72',
  napi: '4',
  nghttp2: '1.39.2',
  node: '12.10.0',
  openssl: '1.1.1c',
  tz: '2019a',
  unicode: '12.1',
  uv: '1.31.0',
  v8: '7.6.303.29-node.16',
  zlib: '1.2.11'
}
```

When deploying this repo to one of our applications: https://github.com/monicahq/monica, with balena push (just changing the version in the docker-compose.yml to 2.1, the build fails with)

```
master /tmp/monica> balena push monica
[Info]     Starting build for monica, user imrehg
[Info]     Dashboard link: https://dashboard.balena-cloud.com/apps/1513257/devices
[Error]    Could not detect project type: Service main: package.json: engines.node must be specified
[Error]    Not deploying release.
Remote build failed

Additional information may be available by setting a DEBUG=1 environment
variable: "set DEBUG=1" on a Windows command prompt, or "export DEBUG=1"
on Linux or macOS.

If you need help, don't hesitate in contacting our support forums at
https://forums.balena.io

For bug reports or feature requests, have a look at the GitHub issues or
create a new one at: https://github.com/balena-io/balena-cli/issues/
```
Similar thing for `balena build`
```
master /tmp/monica> balena build -a monica
[Info]    Compose file detected
[Info]    Building for armv7hf/raspberrypi3
[Build]   Built 2 services in 0:02
[Build]   monicahq Preparing...
[Build]   mysql    Preparing...
[Error]   Build failed
package.json: engines.node must be specified
```

Discussed in [Flowdock](https://www.flowdock.com/app/rulemotion/resin-tech/threads/y0Bh0eD-duERaY5DcDqi5vlG9Qu)

**Comment by Dko1905** [comment]
I have the same issue. 
* balena CLI version: 11.19.1
* Operating system version: Manjaro/ArchLinux
* 32/64 bit OS and processor: 64-bit
* Install method: yarn
* Yarn version: 1.19.2
```bash
$ npm version
{
  'node-rest-password-server': '1.0.0',
  npm: '6.12.1',
  ares: '1.15.0',
  brotli: '1.0.7',
  cldr: '35.1',
  http_parser: '2.8.0',
  icu: '64.2',
  llhttp: '1.1.4',
  modules: '72',
  napi: '5',
  nghttp2: '1.39.2',
  node: '12.13.0',
  openssl: '1.1.1d',
  tz: '2019a',
  unicode: '12.1',
  uv: '1.33.1',
  v8: '7.7.299.13-node.12',
  zlib: '1.2.11'
}
```
When I push using the cli:
```
$ balena push test-app-1
[Info]     Starting build for test-app-1, user gh_dko1905
[Info]     Dashboard link: https://dashboard.balena-cloud.com/apps/1558381/devices
[Error]    Could not detect project type: Service main: package.json: engines.node must be specified
[Error]    Not deploying release.
Remote build failed

Additional information may be available by setting a DEBUG=1 environment
variable: "set DEBUG=1" on a Windows command prompt, or "export DEBUG=1"
on Linux or macOS.

If you need help, don't hesitate in contacting our support forums at
https://forums.balena.io

For CLI bug reports or feature requests, have a look at the GitHub issues or
create a new one at: https://github.com/balena-io/balena-cli/issues/

(node:25049) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
```

**Comment by pdcastro** [comment]
@Dko1905, thank you for this additional report. I've increased this issue's priority in the backlog (I hope to investigate it further this week). Until it is fixed, here's some information that might be helpful. The balenaCloud builders (and sometimes the CLI itself) will check for the "project type" as one of:
* docker-compose project (a `docker-compose.yml` file exists at the project root folder),
* Dockerfile project (a `Dockerfile` or `Dockerfile.template` or `Dockerfile.<arch>` exists at the project root folder),
* and a Node.js project (a `package.json` file exists at the project root folder).

... in the order listed above. From earlier bug reports, it seems that, sometimes, an issue parsing the docker-compose file makes the builder assume that the project is not a docker-compose project, and then proceed with checking a `package.json` file assuming it is a Node.js project. So the "debugging suggestion" would be to strip down the `docker-compose.yml` file (assuming your project has one) to try and narrow down where parsing is failing (assuming this is what is happening...).

**Comment by srlowe** [comment]
@Dko1905 Would you be willing/able to share your `docker-compose.yml` file to aid diagnosis?

**Comment by srlowe** [comment]
@Dko1905 Do you have `Dockerfile` included in your `.dockerignore`?  If so, removing this entry should work around the problem, and a fix for this will be available shortly.
