### ISSUE TITLE
Allow custom network connections to be generated

### ISSUE THREAD

**Issue by hedss** [balena-io/balena-cli#1498]
Currently we allow the configuration of a Wifi connection via `balena os config`, which will create an appropriate wifi connection in the `system-connections` directory of the boot partition.

We should allow the generation of custom network configurations (eg. modem configs) as well, and allow them to be injected.

I *thought* I'd raised this under another issue, but can't find it.

cc @majorz

**Comment by pdcastro** [comment]
Related to issue #1395 ['balena config' should add network settings in the right place for balenaOS 2.x](https://github.com/balena-io/balena-cli/issues/1395)

**Comment by richbayliss** [comment]
@hedss do you think this issue is closable now, due to the merging of the above PR? You talk about file *generation* which is a different, so I wasn't sure.

**Comment by hedss** [comment]
@richbayliss Yes, and shall do so now! cc @pdcastro
