### ISSUE TITLE
Livepush using `.local` address fails on Windows (with incorrect error).

### ISSUE THREAD

**Issue by srlowe** [balena-io/balena-cli#1518]
Livepush using `xxxxxx.local` address does not work with Windows, and fails with the incorrect error `The supervisor version on this remote device does not support multicontainer local mode...`

It looks like the `api.getVersion()` call is failing with an address resolution error `getaddrinfo ENOTFOUND`.  (The prior call to `api.ping()` completes successfully however, presumably with working address resolution).

This error is then being incorrectly masked with the supervisor version error, by the error handling in `deployToDevice(...)`.

**Comment by srlowe** [comment]
@CameronDiver Do you remember if there is any particular reason why the `try/catch` around `api.getVersion()` is masking errors with the `versionError`?  E.g. Maybe old supervisors not supporting the `getVersion` call, and so the implication that errors there are due to old versions?

https://github.com/balena-io/balena-cli/blob/a8bd5d332acd671002881c55625794bc3bc10106/lib/utils/device/deploy.ts#L142-L161

**Comment by CameronDiver** [comment]
@srlowe that's right, the version string didn't exist until v7.21.0: https://www.balena.io/docs/reference/supervisor/supervisor-api/#supervisor-version-get-v2version

**Comment by srlowe** [comment]
After some sleuthing with @hedss, it turns out to be that repeated DNS resolution calls in quick succession cause the problem, which appears to be a symptom of this windows bug:

https://support.microsoft.com/en-gb/help/4057932/getaddrinfo-failed-with-wsahost-not-found-11001-error

We came up with 3 possible workarounds:

1. (tested) Add the option { family: 4 } to http requests.
2. (not tested) Manually call DNS (once) and replace hostname with IP in subsequent request URLs.
3. (tested) Put a pause between each stop (just for windows I guess).

# 1 May interfere with ip6 networking
# 2 Has not been tested (though should work).
# 3 Works well with shortish delay (e.g. 300ms)

Will implement workaround # 3 (only when CLI host is windows).

**Comment by srlowe** [comment]
Note that this Windows problem may be present in other parts of the CLI.

**Comment by pdcastro** [comment]
@srlowe, FYI, looks like the commit headers did not automatically close this issue. Just a guess: a space may be required after the colon character (`:`) for parsing to succeed as documented in: https://help.github.com/en/github/managing-your-work-on-github/closing-issues-using-keywords
