### ISSUE TITLE
Pin releases are not available in CLI.

### ISSUE THREAD

**Issue by shaunmulligan** [balena-io/balena-cli#1543]
We should allow pinning of devices and apps from the CLI to complement the functionality we have in the UI

**Comment by myarmolinsky** [comment]
Reopening because #2493 did not resolve this issue, only partially. It enabled pinning a _device_ to a specific release or making it track the fleet's pinned release. We still need to add the parallel commands for _fleets_  (`pin` and `track-latest`(?))
