### ISSUE TITLE
Deactivate device not available from cli

### ISSUE THREAD

**Issue by shaunmulligan** [balena-io/balena-cli#1545]
A user should be able to deactivate a device from the CLI.

**Comment by srlowe** [comment]
@pdcastro @shaunmulligan I guess the two obvious options are:
 - `balena device deactivate <uuid>`  (new command)
 - `balena device --deactivate <uuid>` (expand responsibilities of existing command)
Any preference?

**Comment by srlowe** [comment]
Ok, we are in agreement then :-)
