### ISSUE TITLE
Add ability to "Grant support access" to devices and apps

### ISSUE THREAD

**Issue by shaunmulligan** [balena-io/balena-cli#1546]
Currently one can only grant support access from the UI, it should be possible from the CLI too.

**Comment by pdcastro** [comment]
Related to (duplicates) #766 [Add command for enabling support access on a device or app](https://github.com/balena-io/balena-cli/issues/766)

**Comment by srlowe** [comment]
Implemented in https://github.com/balena-io/balena-cli/pull/2046
