### ISSUE TITLE
Purge data not available

### ISSUE THREAD

**Issue by shaunmulligan** [balena-io/balena-cli#1547]
One should be able to purge data on devices from the cli

**Comment by pdcastro** [comment]
Related to #583 [Implement new device commands](https://github.com/balena-io/balena-cli/issues/583)

**Comment by srlowe** [comment]
@pdcastro @shaunmulligan I guess the two obvious options are:

    balena device purge <uuid> (new command)
    balena device --purge <uuid> (expand responsibilities of existing command)

One benefit of the first, is that we can more simply implement support for multiple devices. Also commands with multiple responsibilities will be harder to align with the concept of auto-generation.

**Comment by srlowe** [comment]
@pdcastro Given your answer on the `device deactivate` issue, I guess you agree that #1 is best?

**Comment by pdcastro** [comment]
Yes, it would be consistent. :-)
