### ISSUE TITLE
The CLI is not ending after pushing

### ISSUE THREAD

**Issue by AlexProgrammerDE** [balena-io/balena-cli#1554]
- **balena CLI version:** 11.20.1
- **Operating system version:** Windows 10
- **32/64 bit OS and processor:** 64-bit Windows on 64-bit AMD processor
- **Install method:** executable installer
- **Terminal info:** git bash in MINGW64
---

I love the CLI and love also to work with it, but the command stays open after the unicorn and i have to close it manually with ctrl + c . This behavior is not only in this version of the CLI and i am not experiencing this in the linux terminal (I switched back to Windows now.) . Before i switched to Linux and then came back, i had the same problem with the git bash. I have got this behavior only after pushing and not at any other command with the CLI.
Here are some pics:

**This is the terminal**
![Git Bash](https://user-images.githubusercontent.com/40795980/71644503-a1092080-2cc9-11ea-8698-4fc09e373acf.png)

**Here is it before the push:**
![Before the push](https://user-images.githubusercontent.com/40795980/71644518-fe9d6d00-2cc9-11ea-893c-b881da7ddb24.png)

**Here is it after the push:**
![After the push](https://user-images.githubusercontent.com/40795980/71644541-589e3280-2cca-11ea-814f-121a3f54f04a.png)
**It stays there forever. I don´t have this experiance at the Linux terminal.**

**Comment by pdcastro** [comment]
Thank you for reporting this issue. It looks very similar to #1182 [`balena push myApp` hangs on Windows](https://github.com/balena-io/balena-cli/issues/1182). I have now increased its priority in the [Backlog](https://github.com/balena-io/balena-cli/milestone/2).

**Comment by AlexProgrammerDE** [comment]
@pdcastro Thank you for that quick reply. I hope this feature can soon be fixed.

**Comment by pdcastro** [comment]
This issue was fixed in CLI release v11.21.3 ([releases](https://github.com/balena-io/balena-cli/releases)).

**Comment by AlexProgrammerDE** [comment]
@pdcastro wow thanks! 😄
