### ISSUE TITLE
`balena scan` doesn't hint to Windows users to install Bonjour

### ISSUE THREAD

**Issue by grahammcculloch** [balena-io/balena-cli#1562]
- **balena CLI version:** e.g. 11.2.1
- **Operating system version:** Windows (10)
- **32/64 bit OS and processor:** either
- **Install method:** executable installer

---

If Bonjour for Windows is not installed and running, `balena scan` on a Windows machine will not find any devices on the local network. But no advice/help is given to the user about what to do. 

Providing some hint on the console output with a link to download the Bonjour for Windows installer would be useful (if we detect they are running Windows).  I'll submit a PR for this...

**Comment by pdcastro** [comment]
> I'll submit a PR for this...

That PR could also add a note in the INSTALL.md file (Additional Dependencies).

Btw, I have a Windows 10 laptop that was installed from scratch / fresh a few months ago, and checking the Control Panel, I see that Bonjour is there (and yes, `balena scan` works all right). I definitely did not install Bonjour directly myself, but I installed all the CLI [development dependencies](https://github.com/balena-io/balena-cli/blob/master/INSTALL.md#npm-installation) including the WDK, windows-build-tools, MSYS2 and Docker for Windows, plus balenaEtcher and the Microsoft Visual Studio Code. Chances are that one of those dependencies / applications brought Bonjour along.

**Comment by grahammcculloch** [comment]
@pdcastro 

> That PR could also add a note in the INSTALL.md file (Additional Dependencies).

Ha - I'd already added that in the PR #greatmindsthinkalike

Interesting re: Bonjour being installed with the dev dependencies. I was using it before installing the dev dependencies so that's how I discovered it was needed but not installed.
