### ISSUE TITLE
Some `balena` commands result in `Buffer()` warnings being printed to the console

### ISSUE THREAD

**Issue by srlowe** [balena-io/balena-cli#1564]
[Taken from @pdcastro's comment in #1384]

Some `balena` commands result in `Buffer()` warnings being printed to the console (reported by @CameronDiver in [flowdock](https://www.flowdock.com/app/rulemotion/resin-frontend/threads/fpYFKpCm2eWF7dEubEztdD1Uo2O)):
```
(node:30588) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(node:30588) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
```
I didn't find any occurrence in `balena-cli` itself, but a grep of node_modules returned 1625 occurrences:
```
$ grep -R ' Buffer(' node_modules | wc -l
    1625
```
Trying to isolate "balena's own code" in the output above, I identified the following three balena libraries that we could act on first:
```
resin-bundle-resolve
balena-request
balena-sdk
```

_Originally posted by @pdcastro in https://github.com/balena-io/balena-cli/issues/1384#issuecomment-527156522_

**Comment by srlowe** [comment]
@pdcastro Do you remember which commands cause these warnings?

**Comment by pdcastro** [comment]
I believe this was fixed completely. Lots of dependencies were updated in the 2 years since this was initially reported. Closing the issue.
