### ISSUE TITLE
More insight into issues related to development and production builds

### ISSUE THREAD

**Issue by minusplusminus** [balena-io/balena-cli#1566]
Hi,

I already had multiple times in the past that it's unclear for me on what kind of build i'm working on. This causes unclarity about pushing dockers and modes. Is it possible that Balena-cli gives more feedback on this part. It would be rather helpful when developing and testing builds.

**Comment by pdcastro** [comment]
Thanks for this feedback / suggestion @minusplusminus. Could you share an example or more details? I didn't understand the meaning of "what kind of build", "dockers and modes".
* Do you mean identifying the release / commit / ID / hash ?
* Do you mean any specific commands, like `balena build` _vs._ `balena deploy` _vs._ `balena push`?
* Is it specific to building using the balenaCloud builders, or a local device, or Docker running your development machine?

**Comment by pdcastro** [comment]
Closing for now, pending a reply / clarification.
