### ISSUE TITLE
Ability to rename applications

### ISSUE THREAD

**Issue by JSReds** [balena-io/balena-cli#1567]
- **balena CLI version: 11.21.0**
- **Operating system version: macOS 10.15.2**
- **Install method: npm**
- **If npm install, Node.js and npm version: Node v12.14.0 and npm v6.13.4**

It would be helpful to have a command to be able to rename an application. Maybe it exists but I have not found any references from `balena help --verbose`

**Comment by srlowe** [comment]
@pdcastro I see this has been added to `Web dashboard feature parity`, but is this possible in the dash? I couldn't see any way to do it, and there's no obvious SDK method for this.

**Comment by srlowe** [comment]
I see it described in the docs, but can't find that option in the dash: https://www.balena.io/docs/learn/manage/actions/#rename-application
