### ISSUE TITLE
"balena os download" always gives "No such version for the device type"

### ISSUE THREAD

**Issue by Ciantic** [balena-io/balena-cli#1593]
- **balena CLI version:** 11.25.2
- **Operating system version:** Windows 10 64bit
- **Install method:** npm
- **If npm install, Node.js and npm version:** node v10.15.0, npm 6.4.1

---

I'm connected to openBalena instance, none of the os downloads work (they haven't worked ever for me with openBalena):

This example is from the master class:
```
balena os download fincm3 --version 2.38.0+rev1 --output balena-fin-image.img
Getting device operating system for fincm3
No such version for the device type
```

This is my attempt:
```
balena os download raspberrypi4-64 --version 2.47.0+rev1 --output balena-rpi4.img
Getting device operating system for raspberrypi4-64
No such version for the device type
```

Is this related to fact that I use openBalena?

**Comment by pdcastro** [comment]
> Is this related to fact that I use openBalena?

@Ciantic, I believe so. I have gathered that the `balena os download` command uses `balena-sdk`, which issues a request to the balena API's `/download` endpoint:
* https://github.com/balena-io/balena-sdk/blob/v12.21.1/lib/models/os.coffee#L387
* https://github.com/balena-io/balena-sdk/blob/v12.21.1/lib/models/os.coffee#L152

And then I found the following relatively recent answers by an openBalena developer in a forum thread:
> https://forums.balena.io/t/unable-to-download-balenaos-images-using-pythonsdk/52409/18
> * OpenBalena does not support image downloads – you have to get the images from [balena.io/os](http://balena.io/os).
> * The openBalena API has no `/download` endpoint and from the logs above you can see the SDK clearly tries to reach that endpoint, and as a matter of fact, gets a 404 response.
> * That `/image` endpoint is reaching out to the Image Maker, not the API, which is a component that is not included with openBalena. Image downloads with openBalena were never supported.

Of course, this also reveals that we need to improve documentation, CLI's `help` output, and detect openBalena and warn/prevent execution of unsupported commands. I have created CLI issue #1610 for this purpose. Thank you for pointing it out!

**Comment by pdcastro** [comment]
Closing this issue with the understanding that the original question was clarified, and that the actionable aspects were captured in #1610.
