### ISSUE TITLE
Add '--cachefrom' option to balena build / deploy commands

### ISSUE THREAD

**Issue by pdcastro** [balena-io/balena-cli#1616]
User reports that cached images are not used by balena build / deploy commands. Shaun found / believes that the solution would be to use the `cachefrom` option of image build Docker API.

* Forum thread: https://forums.balena.io/t/balena-cli-is-not-using-the-cache-on-fresh-machine/62266
* Flowdock: https://www.flowdock.com/app/rulemotion/resin-frontend/threads/uD3tiekE56YA1zpVEuoEq8z1SGX
* API: https://docs.docker.com/engine/api/v1.40/#operation/ImageBuild

**Comment by samothx** [comment]
User reports this fix has worked for him..

**Comment by pdcastro** [comment]
Feature released in CLI version 11.26.0.
