### ISSUE TITLE
Perform some sanity checks before starting tar/upload of directory when pushing

### ISSUE THREAD

**Issue by chrisys** [balena-io/balena-cli#1619]
It appears to be a common scenario where users do not `cd` into the correct directory for their project when pushing for the first time. Due to this the CLI will compress & upload a directory which could have a whole load of other files in.

1. We don't want files/data on our builder that the user didn't intend for us to have
1. Can make the upload process take a long time (and also can't tell whats happening, #1303 related)
1. Build will fail anyway

Could we do some basic checks such as looking for a Dockerfile or docker-compose.yml before compressing and starting the upload when using `balena push`? If neither are found, we could provide a useful error message? *No Dockerfile or docker-compose.yml detected - is this the right directory?*

**Comment by pdcastro** [comment]
Related to / duplicates #1421 _(Run sanity project checks before push / deploy / build commands)_ which, as it happens, I am working on at the moment. :-)

**Comment by chrisys** [comment]
@pdcastro oh dang, our issue titles were so similar and I still didn't find yours! Great to hear, thanks 👍

**Comment by pdcastro** [comment]
Implemented in CLI release 11.27.0.
