### ISSUE TITLE
Prompt before replacing a multi-container app with a single-container app

### ISSUE THREAD

**Issue by pdcastro** [balena-io/balena-cli#1621]
Creating this issue out of @jimsynz's [comment in another issue](https://github.com/balena-io/balena-cli/issues/1421#issuecomment-561848706)

> When you have a multi-container application and you accidentally run `balena push ...` inside one of the service subdirectories balena sees that you have a `Dockerfile.template` in this directory and happily redeploys your application as a single-container app.
Some suggestions:
> 1. check if there is a `docker-compose.yml` in a parent directory and query the user for confirmation.
> 2. check if the command is run from a subdirectory of the local git repo and either query for confirmation or just assume that they want to push from the root.
> 3. combination of the two above, check if there is a `Dockerfile.template` or `docker-compose.yml` in the root of the current git repo and use that.
> 4. detect if a push would change the service topology of the application (ie would add or remove services) and ask the user for confirmation. this may be a little annoying so...
> 5. detect if a push would _remove all existing services and replace them_ with a new one and require confirmation.

The first point was partially implemented in CLI release 11.27.0 (PR #1571), but the CLI only issues a warning and doesn't actually prompt the user or prevent the operation.

When implementing it, consider also that the push/build/deploy commands may be automated in scripts, in which case prompting the user is not a good idea. TTY detection and scriptable mode override may be needed alongside this implementation: see issue #1089 (scriptable mode) and #1001 (suppress unicorn).

**Comment by myarmolinsky** [comment]
Closing as all applications are now multicontainer and application types are no longer a thing
