### ISSUE TITLE
Filter old CLI versions when logging via sentry.

### ISSUE THREAD

**Issue by srlowe** [balena-io/balena-cli#1630]
Unnecessary sentry logging is steadily being reduced in CLI releases, however we have no control over older versions that may still be in use.  To reduce the amount of data logged to sentry we should:
 - Send CLI v when logging via sentry.
 - In API sentry proxy route, set a min CLI version, below which we do not forward requests.

It may make sense to do this after we have upgraded sentry client (since this will probably require changes to sentry library code, which would be replaced during sentry upgrade).

**Comment by pdcastro** [comment]
@srlower, do you know/remember if we actually/already have a balena-controlled endpoint ("API sentry proxy route")? I know we do for Mixpanel (`events.ts`), but for Sentry it seems to use a `sentry.io` URL:
* https://github.com/balena-io/balena-cli/blob/v11.29.4/lib/app-common.ts#L53
* https://github.com/balena-io/balena-cli/blob/v11.29.4/lib/config.ts#L21

**Comment by srlowe** [comment]
@pdcastro Ah... this may have been a bad assumption on my part (because we had the proxy for mixpanel).   

Hmm.  Not sure how we could save this in that case.   Even if we add proxy now, that doesn't stop old stuff getting through.    We could in theory change our sentryid/DSN (if we wanted to stop old traffic, or direct traffic), but that might cause strange behaviour on the users' end when an error encountered.

**Comment by srlowe** [comment]
Closing, since we have no control over sentry endpoint.
