### ISSUE TITLE
CLI on arm64: net-keepalive fails to compile, then "logs" and "live push" fail silently

### ISSUE THREAD

**Issue by pdcastro** [balena-io/balena-cli#1647]
- **balena CLI version:** any (11.28.11)
- **Operating system version:** Linux
- **32/64 bit OS and processor:** arm64
- **Install method:** npm
- **If npm install, Node.js and npm version:** tested with Node 8 and 10

---

Testing with a Raspberry 4 (arm64, `raspberrypi4-64` device type), balena OS 2.47.0+rev1 (development image), with the device in [local mode](https://www.balena.io/docs/learn/develop/local-mode/):

```
# open ssh shell on the RPi 4
$ ssh -p 22222 root@192.168.0.37
$ balena-engine run -it ubuntu:18.04 /bin/bash
$ apt-get update && apt-get install -y curl git python g++ make
$ curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.2/install.sh | bash
$ source /root/.bashrc
$ nvm install 10.16.0
$ npm install balena-cli -g --production --unsafe-perm
...
make: Entering directory '/root/.nvm/versions/node/v10.16.0/lib/node_modules/balena-cli/node_modules/net-keepalive/node_modules/ffi-napi/build'
  SOLINK_MODULE(target) Release/obj.target/../node-addon-api/src/nothing.node
  COPY Release/nothing.node
  CC(target) Release/obj.target/ffi/deps/libffi/src/prep_cif.o
../deps/libffi/src/prep_cif.c:26:10: fatal error: ffi.h: No such file or directory
 #include <ffi.h>
          ^~~~~~~
compilation terminated.
deps/libffi/ffi.target.mk:117: recipe for target 'Release/obj.target/ffi/deps/libffi/src/prep_cif.o' failed
make: *** [Release/obj.target/ffi/deps/libffi/src/prep_cif.o] Error 1
make: Leaving directory '/root/.nvm/versions/node/v10.16.0/lib/node_modules/balena-cli/node_modules/net-keepalive/node_modules/ffi-napi/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/root/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 4.19.71
gyp ERR! command "/root/.nvm/versions/node/v10.16.0/bin/node" "/root/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/.nvm/versions/node/v10.16.0/lib/node_modules/balena-cli/node_modules/net-keepalive/node_modules/ffi-napi
gyp ERR! node -v v10.16.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
...
+ balena-cli@11.28.11
added 2243 packages from 1813 contributors in 371.384s
```
But the CLI installation succeeds overall, probably because the `net-keepalive` module is declared as an "optional dependency" in the CLI's `package.json` file.

Then a command like `balena logs`, which depends on `net-keepalive`, fails silently:
```
$ DEBUG=1 balena logs 192.168.0.21
[debug] original argv0="node" argv=[/root/.nvm/versions/node/v10.16.0/bin/node,/root/.nvm/versions/node/v10.16.0/bin/balena,logs,192.168.0.21] length=4
[Debug]   Checking we can access device
[Debug]   Sending request to http://192.168.0.21:48484/ping
```

Searching the web for the `node-ffi` compilation error, I found the following seemingly relevant issues:
* https://github.com/node-ffi/node-ffi/issues/533
* https://github.com/node-ffi/node-ffi/issues/393

Other than having those `node-ffi` issues fixed, the CLI commands that "optionally depend" on net-keepalive (balena logs, balena push ip-address) should:
* At runtime, succeed without relying on the `net-keealive` module. After all, it is listed as an optional dependency.
* Or at least, fail noisily with a good explanation, instead of failing silently.
* Alternatively, the `net-keepalive` module should be declared as a non-optional dependency, and the CLI should noisily fail to install. Perhaps this is not an option because `net-keepalive` is not available on all platforms? (Windows?)

**Comment by pdcastro** [comment]
Good news: the `net-keepalive` package was updated (already a few months ago, actually...) and, as a result, the CLI now compiles / installs on arm64 (Raspberry Pi 4) without errors, with Node.js v10 and v12 (v10.22.1 and v12.18.4) which are the currently supported Node.js versions on all platforms (Intel x86-64 / amd64 on Linux, Windows, macOS).

Tested specifically with Ubuntu 18.04 on a container on balenaOS on a Raspberry Pi4, with the following commands:

```
# open ssh shell on the RPi 4
$ ssh -p 22222 root@192.168.0.37
$ balena-engine run -it ubuntu:18.04 /bin/bash
$ apt-get update && apt-get install -y curl git python g++ make
$ curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.36.0/install.sh | bash
$ source /root/.bashrc
$ nvm install 12.18.4
$ npm install balena-cli -g --production --unsafe-perm
...
+ balena-cli@12.23.4
added 2123 packages from 1985 contributors in 406.256s
```
Commands that use `net-keepalive` also work:   🎉 
```
root@5f0c645ff16e:/# balena logs 192.168.1.46
[Logs]    [10/6/2020, 1:28:54 PM] [main] Plain Dockerfile 43 (292547) howdy (2)
[Logs]    [10/6/2020, 1:29:04 PM] [main] Plain Dockerfile 43 (292548) howdy (2)

$ balena version -a
balena-cli version "12.23.4"
Node.js version "12.18.4"
```

**Comment by srlowe** [comment]
Oh cool!
