### ISSUE TITLE
`balena apps` fails with "_.trimEnd is not a function"

### ISSUE THREAD

**Issue by pdcastro** [balena-io/balena-cli#1658]
- **balena CLI version:** 11.28.14
- **Operating system version:** Windows 10
- **32/64 bit OS and processor:** 64-bit Intel
- **Install method:** Windows native installer
- **If npm install, Node.js and npm version:** Node v8.15.1, installer built-in

---

```
C:\Users\paulo>set DEBUG=1
C:\Users\paulo>balena apps
[debug] original argv0="C:\Program Files\balena-cli\bin\\..\client\bin\node.exe" argv=[C:\Program Files\balena-cli\client\bin\node.exe,C:\Program Files\balena-cli\client\bin\run,apps] length=3
_.trimEnd is not a function
TypeError: _.trimEnd is not a function
    at C:\Program Files\balena-cli\client\node_modules\resin-cli-visuals\build\widgets\table.js:85:14
    at arrayMap (C:\Program Files\balena-cli\client\node_modules\resin-cli-visuals\node_modules\lodash\index.js:1406:25)
    at Function.map (C:\Program Files\balena-cli\client\node_modules\resin-cli-visuals\node_modules\lodash\index.js:6710:14)
    at trimRight (C:\Program Files\balena-cli\client\node_modules\resin-cli-visuals\build\widgets\table.js:84:18)
    at Object.exports.horizontal (C:\Program Files\balena-cli\client\node_modules\resin-cli-visuals\build\widgets\table.js:120:10)
    at balena.models.application.getAll.then (C:\Program Files\balena-cli\client\build\actions\app.js:78:51)
From previous event:
    at Command.action (C:\Program Files\balena-cli\client\build\actions\app.js:73:14)
    at <anonymous>
```

**However,** there is no error in a "fresh" installation of v11.28.14. It only happens when it is installed on top of an older, pre-installed version, for example v11.28.0. Thus:

**Steps to reproduce:**
1. Use Windows Explorer to delete the following folder and all its contents:
`C:\Program Files\balena-cli`

2. Install CLI v11.28.0: [balena-cli-v11.28.0-windows-x64-installer.exe](https://github.com/balena-io/balena-cli/releases/download/v11.28.0/balena-cli-v11.28.0-windows-x64-installer.exe)

3. Install CLI v11.28.14 on top: [balena-cli-v11.28.14-windows-x64-installer.exe](https://github.com/balena-io/balena-cli/releases/download/v11.28.14/balena-cli-v11.28.14-windows-x64-installer.exe)

**Known workaround:**

1. Before installing / upgrading the CLI, use Windows Explorer to delete the following folder and all its contents: `C:\Program Files\balena-cli`

2. Install the CLI as usual: [installation instructions](https://github.com/balena-io/balena-cli/blob/master/INSTALL.md)

**Comment by pdcastro** [comment]
The proper fix for this issue may be to modify the native installer so that it first deletes an existing installation, before installing on top.

**Comment by srlowe** [comment]
I've reproduced this problem, and compared a clean  v11.28.14 install with a  v11.28.0-> v11.28.14 upgrade install.  There were differences in ~20 npm modules (winmerge report attached).

[cli-install-differences-filtered.csv.txt](https://github.com/balena-io/balena-cli/files/4317068/cli-install-differences-filtered.csv.txt)

**Comment by srlowe** [comment]
@pdcastro I understand that the windows installer is built with `oclif-dev pack:win` (pls correct me if I'm wrong).  I can't find any options in the https://github.com/oclif/dev-cli docs regarding removing old installs before installing.  Nor can I see any open issues matching ours.
