### ISSUE TITLE
Support easy switching between multiple accounts.

### ISSUE THREAD

**Issue by jimsynz** [balena-io/balena-cli#1660]
When using balena CLI while on support one often needs to switch between their personal account and their support agent account. It'd be awesome if it was possible to easily switch between multiple accounts.

Inspiration could be taken from the [awscli named profile support](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html) where an environment variable can be used to switch between multiple profiles.

Thanks team!

**Comment by pdcastro** [comment]
@xginn8 has contributed this workaround / helper shell function:
```sh
$ which balena-change-env 
balena-change-env () {
        local url
        case $1 in
                (""|help) echo "USAGE: $0 <cloud|staging|dev|support|[url]>"
                        echo "set the balena-cli environment"
                        return 1 ;;
                (support) url=balena-cloud.com  ;;
                (prod|cloud) url=balena-cloud.com  ;;
                (stag|staging) url=balena-staging.com  ;;
                (dev) url=my.devenv.local  ;;
                (ob) url=openbalena.local  ;;
                (*) if test -z "$2"
                        then
                                echo "USAGE: $0 $1 <url>"
                                return 1
                        fi
                        url=$1  ;;
        esac
        yq write ~/.balenarc.yml balenaUrl "${url}" | sponge ~/.balenarc.yml
        local token_path="${HOME}/.balena/token" 
        local env_token_path="${token_path}.${1}" 
        ln -fvs "${env_token_path}" "${token_path}"
        export VIRTUAL_ENV_LABEL="${1}" 
}
```

**Comment by pdcastro** [comment]
Also of potential interest, if the accounts (login details) are dependent on the "current working directory", for example different accounts to be used when `cd`'ing to different repos like `balena-on-balena`, `openbalena`, `myproject`... Then the CLI already provides a built-in solution:
* A `balenarc.yml` file on the current working directory takes precedence over (and, I believe, gets merged with) any `.balenarc.yml` file in the homedir.
* A `balenarc.yml` file may include a `dataDirectory` field that specifies an alternative directory for the login token (an alternative to the default `~/.balena` directory).

Therefore, one could have multiple CLI config files such as:

* `~/.balenarc.yml` - default config
* `~/balena-on-balena/balenarc.yml` - BoB specific config
* `~/openbalena/balenarc.yml` - openBalena specific config

The contents of a sample `balenarc.yml` file might be:
```
balenaUrl: 'balena-cloud.com'
dataDirectory: '/Users/paulo/.balena-bob'
```
Or for the staging environment:
```
balenaUrl: 'balena-staging.com'
dataDirectory: '/Users/paulo/.balena-staging'
```
This solution is (partially) documented in the CLI masterclass and FAQ:
* https://www.balena.io/docs/learn/more/masterclasses/advanced-cli/#13-separate-environment-configurations
* https://github.com/balena-io/balena-cli/blob/master/TROUBLESHOOTING.md#how-do-i-make-the-balena-cli-persist-data-in-another-directory

**Comment by pdcastro** [comment]
JellyFish brainstorming link: https://jel.ly.fish/cab2b7ff-c650-41e3-89fb-ec31d9d87ee9

**Comment by 20k-ultra** [comment]
Sharing my solution to this for now which works well. I have the following functions added to my bash profile so I can then invoke the CLI with specific env vars set to point to each "profile". The bob profile needs the certs because that device is using self signed TLS certs.

```
bob () {
  NODE_EXTRA_CA_CERTS=/home/mig/Projects/balena-on-balena/keys/haproxy-certs/ca.pem \
  BALENARC_BALENA_URL=my.devenv.local \
  BALENARC_DATA_DIRECTORY=~/.balena/balena-on-balena \
    balena $@
}

balena_staging () {
  BALENARC_BALENA_URL=balena-staging.com \
  BALENARC_DATA_DIRECTORY=~/.balena/staging \
    balena $@
}
```
