### ISSUE TITLE
Add permission validation of auth token / folders when running as non-root users

### ISSUE THREAD

**Issue by pdcastro** [balena-io/balena-cli#1667]
As per following FAQ entry, users get permission denied if, at some point, they run the CLI as the root user, and then attempt to run it again as non-root user:
https://github.com/balena-io/balena-cli/blob/master/TROUBLESHOOTING.md#i-get-eacces-permission-denied-when-logging-in

The CLI itself could/should validate permissions and provide a friendlier user message -- and maybe even attempt dynamic privilege escalation to fix the problem for the user. (Not sure whether the last point is really a good idea... but certainly a friendlier error message.)

**Comment by pdcastro** [comment]
Support thread: https://jel.ly.fish/b36e4bed-4f1a-4604-b104-b1abdd38996c

**Comment by josecoelho** [comment]
Hi, @pbcastro,

I did some investigation, and the problem is not only on login, is the error message asking you to login again if you are logged in but have no permission to read the file as well. You can get into a loop where you can't proceed until you fix the file permission (or start using `sudo` for all commands as a workaround).

## Steps to reproduce (example of loop)
```bash
# after logged in, remove read access from ~/.balena/token
chmod a-r ~/.balena/token

# Run balena-cli as normal user
bin/balena apps

# Fail with message asking for login
bin/balena login
# EACCESS error asking to run with sudo

sudo bin/balena login
# success login

bin/belana apps
# Fail with message asking for login

# and keep doing it :)

sudo bin/belena apps # works as expected, but it's not good UX
```

### Thinking about a solution

One possible solution could be as simple as improving errors.ts [EACCESS](https://github.com/josecoelho/balena-cli/blob/d94a74dfee615a07a0c1951d762d910dfbb9721e/lib/errors.ts#L82) message, mentioning a way to fix in the same way that is described on [throubleshooting](https://github.com/balena-io/balena-cli/blob/master/TROUBLESHOOTING.md#i-get-eacces-permission-denied-when-logging-in)
But, this is quite a generic error and the message might not make sense in all cases.

Just changing the message might be less than ideal, as the user will still receive the not logged in failure with no clue about permissions. I believe we need to  fix [patterns.checkLoggedIn](https://github.com/josecoelho/balena-cli/blob/f9ece2ce7de3d0c2089692e592c70828e92353f9/lib/utils/patterns.ts#L83) as well. 

But we can't simply check for the permissions before trying to log in, not directly from the `balena-cli` at least,
`balena-cli` doesn't know where, how or when the token is stored. balena-auth/settings-storage might know that.
So the proper way to fix it might be fixing `balena-auth`:
 * to throw a specific error when trying to log in, with storage, and no permission to the token file, 
 * or, to keep backwards compatibility, add a new method to check any required permission.

I hope this can help a bit. I will try to get back to it later. Do you mind checking if I'm on the right path?

**Comment by pdcastro** [comment]
> Do you mind checking if I'm on the right path?

@josecoelho, yes it sounds like the right path. 👍   Some comments:

> But we can't simply check for the permissions before trying to log in, not directly from the `balena-cli` at least,
`balena-cli` doesn't know where, how or when the token is stored.

I know what you mean and I agree that it would be better that `balena-auth` checked permissions, but I wanted to point out that there is actually a precedent for `balena-cli` itself getting hold of the "data directory", inside which there is a file named "token". See `getStorage()` and `storage.get('token')` in the following lines:
https://github.com/balena-io/balena-cli/blob/v12.20.0/lib/events.ts#L60-L65

So it would not be beyond the realm of possibilities :-) that `balena-cli` itself did a permission check on the token file, if it detects that such a file exists.

> might be fixing `balena-auth` [...] to throw a specific error when trying to log in, with storage, and no permission to the token file

Yes, this sounds like the best approach.

> or, to keep backwards compatibility, 

This implies that modifying `balena-auth` to throw a specific error (if the token file does not have permissions) would break compatibility... hmm. `balena-auth` already throws an error when there is no permission to access the token, but it's EACCESS instead of a more specific error. Yes, this sounds like a breaking change, if to be strict about it. `balena-auth` follows the semver conventions, so a bump to the major version would allow this breaking change to be made. I don't think it's a problem to bump the major version.

> add a new method to check any required permission

Could be done as well, but I think it would be "cleaner" to raise the specific error with a major version bump, than to add another method.

> I will try to get back to it later.

Do you mean you're planning to implement it and create a pull request? If so, that's awesome! 👍  😀

**Comment by josecoelho** [comment]
Hi @pbcastro,

I was having another look into this and seems like the best way to handle the issue is actually changing balena-settings-storage. I couldn't find a good way to identify permission issues directly from `balena-auth` as all permission errors were being supressed by `balena-settings-storage`. https://github.com/balena-io-modules/balena-settings-storage/pull/29

I still doing integration tests with `balena-cli` after this change. Unfortunately, that's my limit for today, I will be back to it later.

**Comment by josecoelho** [comment]
Hi @pbcastro,

I have finally find some time to get back to this.
From further investigation. This is the flow of calls from `balena-cli` all the way down to `balena-settings-storage`

[![](https://mermaid.ink/img/eyJjb2RlIjoiZ3JhcGggTFJcbiAgICBiYWxlbmEtY2xpIC0tPnxpc0xvZ2dlZElufCBiYWxlbmEtc2RrXG4gICAgYmFsZW5hLXNkayAtLT4gfHJlcXVlc3Quc2VuZHwgYmFsZW5hLXJlcXVlc3RcbiAgICBiYWxlbmEtcmVxdWVzdCAtLT4gfGF1dGguaGFzVG9rZW58IGJhbGVuYS1hdXRoXG4gICAgYmFsZW5hLWF1dGggLS0-IHxzdG9yYWdlLmdldHwgYmFsZW5hLXNldHRpbmdzLXN0b3JhZ2VcbiAgICAgICAgICAgICIsIm1lcm1haWQiOnsidGhlbWUiOiJkZWZhdWx0IiwidGhlbWVWYXJpYWJsZXMiOnsiYmFja2dyb3VuZCI6IndoaXRlIiwicHJpbWFyeUNvbG9yIjoiI0VDRUNGRiIsInNlY29uZGFyeUNvbG9yIjoiI2ZmZmZkZSIsInRlcnRpYXJ5Q29sb3IiOiJoc2woODAsIDEwMCUsIDk2LjI3NDUwOTgwMzklKSIsInByaW1hcnlCb3JkZXJDb2xvciI6ImhzbCgyNDAsIDYwJSwgODYuMjc0NTA5ODAzOSUpIiwic2Vjb25kYXJ5Qm9yZGVyQ29sb3IiOiJoc2woNjAsIDYwJSwgODMuNTI5NDExNzY0NyUpIiwidGVydGlhcnlCb3JkZXJDb2xvciI6ImhzbCg4MCwgNjAlLCA4Ni4yNzQ1MDk4MDM5JSkiLCJwcmltYXJ5VGV4dENvbG9yIjoiIzEzMTMwMCIsInNlY29uZGFyeVRleHRDb2xvciI6IiMwMDAwMjEiLCJ0ZXJ0aWFyeVRleHRDb2xvciI6InJnYig5LjUwMDAwMDAwMDEsIDkuNTAwMDAwMDAwMSwgOS41MDAwMDAwMDAxKSIsImxpbmVDb2xvciI6IiMzMzMzMzMiLCJ0ZXh0Q29sb3IiOiIjMzMzIiwibWFpbkJrZyI6IiNFQ0VDRkYiLCJzZWNvbmRCa2ciOiIjZmZmZmRlIiwiYm9yZGVyMSI6IiM5MzcwREIiLCJib3JkZXIyIjoiI2FhYWEzMyIsImFycm93aGVhZENvbG9yIjoiIzMzMzMzMyIsImZvbnRGYW1pbHkiOiJcInRyZWJ1Y2hldCBtc1wiLCB2ZXJkYW5hLCBhcmlhbCIsImZvbnRTaXplIjoiMTZweCIsImxhYmVsQmFja2dyb3VuZCI6IiNlOGU4ZTgiLCJub2RlQmtnIjoiI0VDRUNGRiIsIm5vZGVCb3JkZXIiOiIjOTM3MERCIiwiY2x1c3RlckJrZyI6IiNmZmZmZGUiLCJjbHVzdGVyQm9yZGVyIjoiI2FhYWEzMyIsImRlZmF1bHRMaW5rQ29sb3IiOiIjMzMzMzMzIiwidGl0bGVDb2xvciI6IiMzMzMiLCJlZGdlTGFiZWxCYWNrZ3JvdW5kIjoiI2U4ZThlOCIsImFjdG9yQm9yZGVyIjoiaHNsKDI1OS42MjYxNjgyMjQzLCA1OS43NzY1MzYzMTI4JSwgODcuOTAxOTYwNzg0MyUpIiwiYWN0b3JCa2ciOiIjRUNFQ0ZGIiwiYWN0b3JUZXh0Q29sb3IiOiJibGFjayIsImFjdG9yTGluZUNvbG9yIjoiZ3JleSIsInNpZ25hbENvbG9yIjoiIzMzMyIsInNpZ25hbFRleHRDb2xvciI6IiMzMzMiLCJsYWJlbEJveEJrZ0NvbG9yIjoiI0VDRUNGRiIsImxhYmVsQm94Qm9yZGVyQ29sb3IiOiJoc2woMjU5LjYyNjE2ODIyNDMsIDU5Ljc3NjUzNjMxMjglLCA4Ny45MDE5NjA3ODQzJSkiLCJsYWJlbFRleHRDb2xvciI6ImJsYWNrIiwibG9vcFRleHRDb2xvciI6ImJsYWNrIiwibm90ZUJvcmRlckNvbG9yIjoiI2FhYWEzMyIsIm5vdGVCa2dDb2xvciI6IiNmZmY1YWQiLCJub3RlVGV4dENvbG9yIjoiYmxhY2siLCJhY3RpdmF0aW9uQm9yZGVyQ29sb3IiOiIjNjY2IiwiYWN0aXZhdGlvbkJrZ0NvbG9yIjoiI2Y0ZjRmNCIsInNlcXVlbmNlTnVtYmVyQ29sb3IiOiJ3aGl0ZSIsInNlY3Rpb25Ca2dDb2xvciI6InJnYmEoMTAyLCAxMDIsIDI1NSwgMC40OSkiLCJhbHRTZWN0aW9uQmtnQ29sb3IiOiJ3aGl0ZSIsInNlY3Rpb25Ca2dDb2xvcjIiOiIjZmZmNDAwIiwidGFza0JvcmRlckNvbG9yIjoiIzUzNGZiYyIsInRhc2tCa2dDb2xvciI6IiM4YTkwZGQiLCJ0YXNrVGV4dExpZ2h0Q29sb3IiOiJ3aGl0ZSIsInRhc2tUZXh0Q29sb3IiOiJ3aGl0ZSIsInRhc2tUZXh0RGFya0NvbG9yIjoiYmxhY2siLCJ0YXNrVGV4dE91dHNpZGVDb2xvciI6ImJsYWNrIiwidGFza1RleHRDbGlja2FibGVDb2xvciI6IiMwMDMxNjMiLCJhY3RpdmVUYXNrQm9yZGVyQ29sb3IiOiIjNTM0ZmJjIiwiYWN0aXZlVGFza0JrZ0NvbG9yIjoiI2JmYzdmZiIsImdyaWRDb2xvciI6ImxpZ2h0Z3JleSIsImRvbmVUYXNrQmtnQ29sb3IiOiJsaWdodGdyZXkiLCJkb25lVGFza0JvcmRlckNvbG9yIjoiZ3JleSIsImNyaXRCb3JkZXJDb2xvciI6IiNmZjg4ODgiLCJjcml0QmtnQ29sb3IiOiJyZWQiLCJ0b2RheUxpbmVDb2xvciI6InJlZCIsImxhYmVsQ29sb3IiOiJibGFjayIsImVycm9yQmtnQ29sb3IiOiIjNTUyMjIyIiwiZXJyb3JUZXh0Q29sb3IiOiIjNTUyMjIyIiwiY2xhc3NUZXh0IjoiIzEzMTMwMCIsImZpbGxUeXBlMCI6IiNFQ0VDRkYiLCJmaWxsVHlwZTEiOiIjZmZmZmRlIiwiZmlsbFR5cGUyIjoiaHNsKDMwNCwgMTAwJSwgOTYuMjc0NTA5ODAzOSUpIiwiZmlsbFR5cGUzIjoiaHNsKDEyNCwgMTAwJSwgOTMuNTI5NDExNzY0NyUpIiwiZmlsbFR5cGU0IjoiaHNsKDE3NiwgMTAwJSwgOTYuMjc0NTA5ODAzOSUpIiwiZmlsbFR5cGU1IjoiaHNsKC00LCAxMDAlLCA5My41Mjk0MTE3NjQ3JSkiLCJmaWxsVHlwZTYiOiJoc2woOCwgMTAwJSwgOTYuMjc0NTA5ODAzOSUpIiwiZmlsbFR5cGU3IjoiaHNsKDE4OCwgMTAwJSwgOTMuNTI5NDExNzY0NyUpIn19LCJ1cGRhdGVFZGl0b3IiOmZhbHNlfQ)](https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggTFJcbiAgICBiYWxlbmEtY2xpIC0tPnxpc0xvZ2dlZElufCBiYWxlbmEtc2RrXG4gICAgYmFsZW5hLXNkayAtLT4gfHJlcXVlc3Quc2VuZHwgYmFsZW5hLXJlcXVlc3RcbiAgICBiYWxlbmEtcmVxdWVzdCAtLT4gfGF1dGguaGFzVG9rZW58IGJhbGVuYS1hdXRoXG4gICAgYmFsZW5hLWF1dGggLS0-IHxzdG9yYWdlLmdldHwgYmFsZW5hLXNldHRpbmdzLXN0b3JhZ2VcbiAgICAgICAgICAgICIsIm1lcm1haWQiOnsidGhlbWUiOiJkZWZhdWx0IiwidGhlbWVWYXJpYWJsZXMiOnsiYmFja2dyb3VuZCI6IndoaXRlIiwicHJpbWFyeUNvbG9yIjoiI0VDRUNGRiIsInNlY29uZGFyeUNvbG9yIjoiI2ZmZmZkZSIsInRlcnRpYXJ5Q29sb3IiOiJoc2woODAsIDEwMCUsIDk2LjI3NDUwOTgwMzklKSIsInByaW1hcnlCb3JkZXJDb2xvciI6ImhzbCgyNDAsIDYwJSwgODYuMjc0NTA5ODAzOSUpIiwic2Vjb25kYXJ5Qm9yZGVyQ29sb3IiOiJoc2woNjAsIDYwJSwgODMuNTI5NDExNzY0NyUpIiwidGVydGlhcnlCb3JkZXJDb2xvciI6ImhzbCg4MCwgNjAlLCA4Ni4yNzQ1MDk4MDM5JSkiLCJwcmltYXJ5VGV4dENvbG9yIjoiIzEzMTMwMCIsInNlY29uZGFyeVRleHRDb2xvciI6IiMwMDAwMjEiLCJ0ZXJ0aWFyeVRleHRDb2xvciI6InJnYig5LjUwMDAwMDAwMDEsIDkuNTAwMDAwMDAwMSwgOS41MDAwMDAwMDAxKSIsImxpbmVDb2xvciI6IiMzMzMzMzMiLCJ0ZXh0Q29sb3IiOiIjMzMzIiwibWFpbkJrZyI6IiNFQ0VDRkYiLCJzZWNvbmRCa2ciOiIjZmZmZmRlIiwiYm9yZGVyMSI6IiM5MzcwREIiLCJib3JkZXIyIjoiI2FhYWEzMyIsImFycm93aGVhZENvbG9yIjoiIzMzMzMzMyIsImZvbnRGYW1pbHkiOiJcInRyZWJ1Y2hldCBtc1wiLCB2ZXJkYW5hLCBhcmlhbCIsImZvbnRTaXplIjoiMTZweCIsImxhYmVsQmFja2dyb3VuZCI6IiNlOGU4ZTgiLCJub2RlQmtnIjoiI0VDRUNGRiIsIm5vZGVCb3JkZXIiOiIjOTM3MERCIiwiY2x1c3RlckJrZyI6IiNmZmZmZGUiLCJjbHVzdGVyQm9yZGVyIjoiI2FhYWEzMyIsImRlZmF1bHRMaW5rQ29sb3IiOiIjMzMzMzMzIiwidGl0bGVDb2xvciI6IiMzMzMiLCJlZGdlTGFiZWxCYWNrZ3JvdW5kIjoiI2U4ZThlOCIsImFjdG9yQm9yZGVyIjoiaHNsKDI1OS42MjYxNjgyMjQzLCA1OS43NzY1MzYzMTI4JSwgODcuOTAxOTYwNzg0MyUpIiwiYWN0b3JCa2ciOiIjRUNFQ0ZGIiwiYWN0b3JUZXh0Q29sb3IiOiJibGFjayIsImFjdG9yTGluZUNvbG9yIjoiZ3JleSIsInNpZ25hbENvbG9yIjoiIzMzMyIsInNpZ25hbFRleHRDb2xvciI6IiMzMzMiLCJsYWJlbEJveEJrZ0NvbG9yIjoiI0VDRUNGRiIsImxhYmVsQm94Qm9yZGVyQ29sb3IiOiJoc2woMjU5LjYyNjE2ODIyNDMsIDU5Ljc3NjUzNjMxMjglLCA4Ny45MDE5NjA3ODQzJSkiLCJsYWJlbFRleHRDb2xvciI6ImJsYWNrIiwibG9vcFRleHRDb2xvciI6ImJsYWNrIiwibm90ZUJvcmRlckNvbG9yIjoiI2FhYWEzMyIsIm5vdGVCa2dDb2xvciI6IiNmZmY1YWQiLCJub3RlVGV4dENvbG9yIjoiYmxhY2siLCJhY3RpdmF0aW9uQm9yZGVyQ29sb3IiOiIjNjY2IiwiYWN0aXZhdGlvbkJrZ0NvbG9yIjoiI2Y0ZjRmNCIsInNlcXVlbmNlTnVtYmVyQ29sb3IiOiJ3aGl0ZSIsInNlY3Rpb25Ca2dDb2xvciI6InJnYmEoMTAyLCAxMDIsIDI1NSwgMC40OSkiLCJhbHRTZWN0aW9uQmtnQ29sb3IiOiJ3aGl0ZSIsInNlY3Rpb25Ca2dDb2xvcjIiOiIjZmZmNDAwIiwidGFza0JvcmRlckNvbG9yIjoiIzUzNGZiYyIsInRhc2tCa2dDb2xvciI6IiM4YTkwZGQiLCJ0YXNrVGV4dExpZ2h0Q29sb3IiOiJ3aGl0ZSIsInRhc2tUZXh0Q29sb3IiOiJ3aGl0ZSIsInRhc2tUZXh0RGFya0NvbG9yIjoiYmxhY2siLCJ0YXNrVGV4dE91dHNpZGVDb2xvciI6ImJsYWNrIiwidGFza1RleHRDbGlja2FibGVDb2xvciI6IiMwMDMxNjMiLCJhY3RpdmVUYXNrQm9yZGVyQ29sb3IiOiIjNTM0ZmJjIiwiYWN0aXZlVGFza0JrZ0NvbG9yIjoiI2JmYzdmZiIsImdyaWRDb2xvciI6ImxpZ2h0Z3JleSIsImRvbmVUYXNrQmtnQ29sb3IiOiJsaWdodGdyZXkiLCJkb25lVGFza0JvcmRlckNvbG9yIjoiZ3JleSIsImNyaXRCb3JkZXJDb2xvciI6IiNmZjg4ODgiLCJjcml0QmtnQ29sb3IiOiJyZWQiLCJ0b2RheUxpbmVDb2xvciI6InJlZCIsImxhYmVsQ29sb3IiOiJibGFjayIsImVycm9yQmtnQ29sb3IiOiIjNTUyMjIyIiwiZXJyb3JUZXh0Q29sb3IiOiIjNTUyMjIyIiwiY2xhc3NUZXh0IjoiIzEzMTMwMCIsImZpbGxUeXBlMCI6IiNFQ0VDRkYiLCJmaWxsVHlwZTEiOiIjZmZmZmRlIiwiZmlsbFR5cGUyIjoiaHNsKDMwNCwgMTAwJSwgOTYuMjc0NTA5ODAzOSUpIiwiZmlsbFR5cGUzIjoiaHNsKDEyNCwgMTAwJSwgOTMuNTI5NDExNzY0NyUpIiwiZmlsbFR5cGU0IjoiaHNsKDE3NiwgMTAwJSwgOTYuMjc0NTA5ODAzOSUpIiwiZmlsbFR5cGU1IjoiaHNsKC00LCAxMDAlLCA5My41Mjk0MTE3NjQ3JSkiLCJmaWxsVHlwZTYiOiJoc2woOCwgMTAwJSwgOTYuMjc0NTA5ODAzOSUpIiwiZmlsbFR5cGU3IjoiaHNsKDE4OCwgMTAwJSwgOTMuNTI5NDExNzY0NyUpIn19LCJ1cGRhdGVFZGl0b3IiOmZhbHNlfQ)

To be able to test locally you can run:
```bash
$ git clone git@github.com:josecoelho/balena-cli.git
$ git clone git@github.com:josecoelho/balena-settings-storage.git
$ cd balena-settings-storage; git checkout raise-eaccess-errors
$ npm install; npm link
$ cd ../balena-cli; git checkout raise-eacces-errors
$ npm install 
$ npm link balena-settings-storage
$ npm build:fast
$ ./bin/balena login # do login
$ chmod a-r ~/.balena/token # remove read access
$ ./bin/balena apps # it will now fail with new custom error message, instead of generic require login error
```

I created some draft PRs, would it be possible to have a look?
