### ISSUE TITLE
Unable to pass the poll interval as an argument to `join` command

### ISSUE THREAD

**Issue by richbayliss** [balena-io/balena-cli#1670]
From: https://forums.balena.io/t/78926

I am creating a script that takes care of the our whole device provisioning process at once. One of these steps is joining the device to an application. During normal (non-script) usage, `balena join <ip> --application <app>` asks for how often the device should check-in with the app, and you provide the answer in minutes (or press enter for the default). In trying to do this with a script, I’ve found that it keeps giving me the error `Prompts can not be meaningfully rendered in non-TTY environments` whenever I try to provide the answer with the script (or even just on the command line). I’ve tried using `yes` and piping in input from a file or `echo`. Is this just not possible currently, or is there a better way of doing it?

# Proposal

We should be able to pass these values in via args and avoid the user being prompted.

**Comment by pdcastro** [comment]
Related to:
* #1432 [`balena join` does not allow the non-interactive setting of the update period](https://github.com/balena-io/balena-cli/issues/1432)
* #1089 [Implement scriptable (non-interactive) mode](https://github.com/balena-io/balena-cli/issues/1089)

**Comment by srlowe** [comment]
Resolved in #2028 (not sure why it didn't close automatically)
