### ISSUE TITLE
`balena build` help missing `-f` flag

### ISSUE THREAD

**Issue by srlowe** [balena-io/balena-cli#1687]
`balena build` help mentions that an alternative dockerfile can be specified with the `-f` flag, but there is no alias defined for `--dockerfile`.

@pdcastro This appears to be defined in `utils/compose.coffee appendOptions`.  I'll check if this was omitted for a reason (perhaps collides somewhere that uses appendOptions).  Do you know of any reason this is not defined?

**Comment by pdcastro** [comment]
> Do you know of any reason this is not defined?

@srlowe, actually I do! In a CLI check-in about a year ago, :-) I remember proposing the `-f` option to match `docker build`, but then someone else pointed out that `docker-compose` also uses `-f` to select an alternative `docker-compose.yml` file, and we would like the CLI push/build/deploy commands to be able to specify an alternative `docker-compose.yml` as well (pending issue #1142), and they could not both be `-f`. I had suggested having different single-char options, but somewhat to my surprise everybody else (Shaun, Cameron, Hedley, Akis) thought it was preferable not to have any single-character option at all, having only the `--dockerfile` long option name. I must have dropped the single-character option from the code but I guess I forgot to update the help output to match it. So the action to be taken would be to edit the help text to remove any reference to a `-f` option, unless you wanted to reopen the discussion with the product team. :-)

**Comment by srlowe** [comment]
@pdcastro Ah thanks!  I'll update the help.

**Comment by srlowe** [comment]
Fixed in PR #1691
