### ISSUE TITLE
`balena build` does not check for loggedin when applicaiton option set.

### ISSUE THREAD

**Issue by srlowe** [balena-io/balena-cli#1688]
Specifying the `-a --application` flag requires authentication, but this is not checked, and leads to a `BalenaRequestError: Request error: Unauthorized`.  We should probably check on the condition that -a is specified and throw the NotLoggedinError.

**Comment by pdcastro** [comment]
> We should probably check on the condition that -a is specified and throw the NotLoggedinError.

Sounds good 👍  (remembering that the build command does not always require authentication, e.g. when `-A` and `-d` are provided instead of `-a`)

**Comment by srlowe** [comment]
Fixed in PR #1691
