### ISSUE TITLE
Red error messages have poor contrast on PowerShell's default blue background

### ISSUE THREAD

**Issue by pdcastro** [balena-io/balena-cli#1712]
The CLI installation instructions say that the main supported shells on Windows are the Command Prompt (cmd.exe) and PowerShell, so it would be reasonable to expect that text printed by the CLI would be readable on the PowerShell's default blue background. Especially thinking of first-time user experienced / getting started guide, users will install the CLI on Windows, will open PowerShell and run `balena scan`: the output is **very** hard to read.

By the way, perhaps too much text is printed in red. For example, the following "standard" message should probably not be printed in red:
```
[Actual error goes here, could be in red if the background is not blue]

Additional information may be available by setting a DEBUG=1 environment
variable: "set DEBUG=1" on a Windows command prompt, "$env:DEBUG = 1" on
powershell, or "export DEBUG=1" on Linux or macOS.

If you need help, don't hesitate in contacting our support forums at
https://forums.balena.io

For CLI bug reports or feature requests, have a look at the GitHub issues or
create a new one at: https://github.com/balena-io/balena-cli/issues/
```

**Comment by srlowe** [comment]
Closing, as recent changes to error messaging have greatly reduced the amount of red text, making this less of an issue.
