### ISSUE TITLE
`balena scan` should not filter out production devices

### ISSUE THREAD

**Issue by pdcastro** [balena-io/balena-cli#1713]
As per product feedback ([gsheet](https://docs.google.com/spreadsheets/d/1V6URepXBhqU7WhFU1FwUrn-LdQi95ZF4je49dlM2YWQ/))

**Comment by srlowe** [comment]
I had a quick look at this, and I can't see anywhere where we are explicitly filtering out production devices.

**Comment by pdcastro** [comment]
>  I can't see anywhere where we are explicitly filtering out production devices.

And did you actually see any production device being listed by `balena scan`? I've just done a test here with three devices: two development devices were listed, one production device was not. Maybe production devices don't advertise themselves? Which would then be a balenaOS matter.

**Comment by srlowe** [comment]
Turns that the CLI is not filtering production devices (nor are module dependencies), but this is a feature of the production OS (see info below).  Will update gsheet and close.

https://www.flowdock.com/app/rulemotion/r-resinos/threads/q8xugwUW-Q3oLDAlcqkxwU16PDQ

> I believe balena scan will only work on development images. The supervisor can set the discoverability on/off using a HOST_DISCOVERABILITY config option that starts/stops the avahi daemon. You can check whether the service is running in the hostOS and that will tell you whether it is discoverable.

**Comment by pdcastro** [comment]
> Turns that the CLI is not filtering production devices

Or maybe it kind of is... :-)  The discussion continued on that FD thread. I have found that `avahi-daemon` was actually running on a prod device, asked @richbayliss about it who pointed out:
> balena scan is looking for a device SSH service advertised over mDNS
> then it connects to that SSH service to pull device info
> it cannot do that in prod mode due to keys (I think)
> it's not just looking for mDNS/avah

So the CLI, or more precisely the `balena-sync` module:
https://github.com/balena-io-modules/balena-sync/blob/v11.0.2/lib/discover.coffee#L26
... would be potentially finding some info being advertised by the prod devices, but then not being able to collect "additional info" (e.g. ssh service) that a dev device would provide. I actually see this `docker.pingAsync()` call in CLI code:
https://github.com/balena-io/balena-cli/blob/v12.26.0/lib/commands/scan.ts#L93-L97
... which might mean that the CLI gives up if balenaEngine is not exposed on the device. I know that balenaEngine is reachable on port 2375 on dev-image devices, but not on prod-image devices (possibly because of iptables rules).

So I think we need to dig deeper before deciding that there is nothing the CLI can report about prod devices. If there is anything the CLI receives from prod devices, even just an IP address, it could print a reduced output and maybe even print an explanation as to why the output is reduced.
