### ISSUE TITLE
There needs to be a better way to list device type versions

### ISSUE THREAD

**Issue by hedss** [balena-io/balena-cli#1724]
- **balena CLI version:** 11.30.6
- **Operating system version:** All
- **32/64 bit OS and processor:** Al
- **Install method:** Any

The only current way to do this is:
```
﻿﻿balena os download <deviceType> --version menu -o foo
```
which implies that you're going to be downloading an image, rather than just getting a list of the available versions.

Maybe something like `balena os versions <deviceType>`.

**Comment by pdcastro** [comment]
"Device type versions" sounds like output related to that of the `devices supported` command. Maybe some flags could be added to that command.

**Comment by hedss** [comment]
@pdcastro Actually, that's an extremely good observation. Yep, adding versions there makes a tonne of sense! :)

**Comment by cmfcruz** [comment]
`balena os versions <deviceType>` has already been implemented and converted to typescript in [PR #1943](https://github.com/balena-io/balena-cli/pull/1943).
