### ISSUE TITLE
Give a better error message on "balena ssh" when the keys don't match

### ISSUE THREAD

**Issue by jviotti** [balena-io/balena-cli#1731]
The error currently looks like this:

```
$ balena ssh e19f
user@ssh.balena-devices.com: Permission denied (publickey).
Warning: ssh process exited with non-zero code "255"
```

Which may confuse some users. Maybe we can expand on that saying that we believe they don't have the right SSH key configured in their balena cloud account, and maybe even provide a link?

See https://forums.balena.io/t/94451

**Comment by nwneisen** [comment]
I'd like to start contributing to Balena and thought I would start here.

From what I can tell, `user@ssh.balena-devices.com: Permission denied (publickey).` is the stdout of ssh and `Warning: ssh process exited with non-zero code "255"` is the logged output from balena-cli. This is a generic message that is printed no matter what error code is returned from ssh.

The desired solution seems to be to watch for code 255 and improve the message with something like:
`Are your SSH keys correctly configured in Balena Cloud? https://dashboard.balena-cloud.com/preferences/sshkeys`. I can open a pull request if this sounds like the desired solution.

**Comment by jviotti** [comment]
I think that will do! Thanks!

**Comment by nwneisen** [comment]
@jviotti Got in a PR. Let me know any adjustments it may need.
