### ISSUE TITLE
Simplify installation instructions 

### ISSUE THREAD

**Issue by pdcastro** [balena-io/balena-cli#1760]
As mentioned in issue #1711, one vision is to reduce the installation instructions to a download link: "click here to download and install the CLI".

As an intermediate, immediate-term step (discussed with @OdysLam and @srlowe), the proposal is to edit the INSTALL.md file:

* Split out any instructions that apply to developers (the npm installation method) to a separate document (perhaps Contributing.md). Leave only a link to such document in INSTALL.md.
* Provide a single installer recommendation for each platform:
  * Native installer on Windows
  * Native installer on macOS
  * zip package on Linux

Also:
* For Windows, include Bonjour as a required installation step if it is indeed required and/or for as long as `balena scan` is part of the Getting Started guide.
* For macOS, also add a note that homebrew is **not** an official balena-cli installation channel (connects-to: #1406).

**Comment by vipulgupta2048** [comment]
Hey @pdcastro, I agree on the points made in #1711 there is definately scope for improving the installation instructions for beginners coming from the `Getting Started` guide. I was recently following `living Balena user experinece` and had some more thoughts as per my feedback:

- When using the standalone zip package to install the CLI, we can link a specific answer on Stackoverflow about setting a PATH that just works for user rather listing the entire question. My suggestion would be to use this one - https://stackoverflow.com/a/14638025.
- Link the Getting Started guide to the installation page or just add command after the steps to test if the CLI is installed that would be great for completion. Something like 

```
~$ balena --version
11.31.11
```
