### ISSUE TITLE
Convert all remaining commands from Capitano to oclif

### ISSUE THREAD

**Issue by pdcastro** [balena-io/balena-cli#1768]
The CLI was originally implemented with the [Capitano](https://github.com/balena-io/capitano) framework. A decision was made to adopt [oclif](https://oclif.io/) instead. We currently use both, but contributors report this makes it harder to submit contributions. The transition should be completed.

Internal discussion references:
* https://www.flowdock.com/app/rulemotion/resin-frontend/threads/h4hhQ3y5o9bvFkie7sn296DRfu3
* https://www.flowdock.com/app/rulemotion/i-cli/threads/yQaXStqd-pNuJ56Rz4yyqHacBdA

**Comment by srlowe** [comment]
Completed in : https://github.com/balena-io/balena-cli/pull/2018
