### ISSUE TITLE
Improve error boilerplate message

### ISSUE THREAD

**Issue by srlowe** [balena-io/balena-cli#1779]
Base on recent feedback and discussions, the error boilerplate should be rewritten more succinctly.

Current message:
```
Additional information may be available by setting a DEBUG=1 environment
variable: "set DEBUG=1" on a Windows command prompt, "$env:DEBUG = 1" on
powershell, or "export DEBUG=1" on Linux or macOS.

If you need help, don't hesitate in contacting our support forums at
https://forums.balena.io

For CLI bug reports or feature requests, have a look at the GitHub issues or
create a new one at: https://github.com/balena-io/balena-cli/issues/
```

**Comment by srlowe** [comment]
@pdcastro, @Page- , @OdysLam 

How about something like this for reduced boilerplate?

```
Additional information may be available with the `--debug` flag.
For help, see our forums: https://forums.balena.io
For bug reports or feature requests, see: https://github.com/balena-io/balena-cli/issues/
```

We could also use the github url shortener (git.io) for the issues page: 
https://git.io/JfYbB

**Comment by OdysLam** [comment]
@srlowe - just to be certain, this is for the unexpected error, correct?
The important part for me is not to be a wall of red text, other than that I am not opinionated.

**Comment by srlowe** [comment]
@OdysLam , That right.  It will only be displayed in unexpected errors, and at the bottom of the help pages.  Expected errors will also not be red.  I think it was mainly Page that wanted to reduce the text.

**Comment by pdcastro** [comment]
> Additional information may be available with the `--debug` flag.
> For help, see our forums: https://forums.balena.io
> For bug reports or feature requests, see: https://github.com/balena-io/balena-cli/issues/

Could we add the word "support" on the second line? Not sure if instead of, or in addition to the word "help". Suggestions:

* `For help, see our support forums: https://forums.balena.io` 👍 
* `For support, see our forums: https://forums.balena.io` 🤔 
* `For help and support, see our forums: https://forums.balena.io` 👎 

> We could also use the github url shortener (git.io) for the issues page

Tempting, but my vote goes to the long/expanded github URL because users can tell where it takes them before clicking on it. Just one vote. :-)

**Comment by srlowe** [comment]
Yeah first line sounds good to me.  Also, perhaps visit might be better than see?
` - For help, visit our support forums: https://forums.balena.io`

**Comment by OdysLam** [comment]
I think the first line is alright, let's not spend more time on that, any change we deliver to the user will be an immense improvement, so let's focus on spending the least time in every time and shipping it as fast as possible :P
