### ISSUE TITLE
`balena build` should infer architecture from device type

### ISSUE THREAD

**Issue by pdcastro** [balena-io/balena-cli#1795]
In a command like:
```
balena build --arch armv7hf --deviceType fincm3 --emulated
```
The user should not have to specify the architecture, as it can be inferred from the device type.

The `balena devices supported -v` command seems to query a public API endpoint in order to get the architecture information, so `balena build` could do the same even where the user does not have a balenaCloud account (e.g. standalone balenaOS + openBalena).

**Comment by pdcastro** [comment]
Thanks to @cmfcruz for pointing it out. Flowdock discussion: https://www.flowdock.com/app/rulemotion/r-beginners/threads/NW-1oHFua44YhYBAuQhc8n_225d

**Comment by cmfcruz** [comment]
I just realized that one use case of `balena build` is when there might be no Internet and the user intends to deploy only to a local development device.  This means the CLI should cache a local copy of the architecture-device type mapping so it can still identify the architecture even without Internet. Maybe update the local list when an Internet connection is detected?
