### ISSUE TITLE
Fatal error in , line 0

### ISSUE THREAD

**Issue by pattyland** [balena-io/balena-cli#1796]
- **balena CLI version:** 11.31.22
- **Operating system version:** macOS 10.15.4
- **32/64 bit OS and processor:** 64-bit macOS on 64-bit Intel processor
- **Install method:** homebrew

---

I'm trying to configure an image but after entering all values it crashes. The image seems to be unchanged:

```
pattyland@Air ~ % sudo balena local configure ~/Downloads/balena.img
? Network SSID XXX
? Network Key XXX
? Do you want to set advanced settings? Yes
? Device Hostname XXX
? Do you want to enable persistent logging? No


#
# Fatal error in , line 0
# Check failed: result.second.
#
#
#
#FailureMessage Object: 0x7ffeefbf6d70
 1: 0x1000d4fee node::NodePlatform::GetStackTracePrinter()::$_3::__invoke() [/usr/local/bin/node]
 2: 0x100a18c31 V8_Fatal(char const*, ...) [/usr/local/bin/node]
 3: 0x100378772 v8::internal::GlobalBackingStoreRegistry::Register(std::__1::shared_ptr<v8::internal::BackingStore>) [/usr/local/bin/node]
 4: 0x10018d907 v8::ArrayBuffer::GetBackingStore() [/usr/local/bin/node]
 5: 0x100063054 node::Buffer::New(node::Environment*, char*, unsigned long, void (*)(char*, void*), void*) [/usr/local/bin/node]
 6: 0x100062deb node::Buffer::New(v8::Isolate*, char*, unsigned long, void (*)(char*, void*), void*) [/usr/local/bin/node]
 7: 0x102d068db js_request(void*) [/usr/local/Cellar/balena-cli/11.31.22/libexec/lib/node_modules/balena-cli/node_modules/ext2fs/build/Release/bindings.node]
 8: 0x102d06447 default_loop_entry(uv_async_s*) [/usr/local/Cellar/balena-cli/11.31.22/libexec/lib/node_modules/balena-cli/node_modules/ext2fs/build/Release/bindings.node]
 9: 0x1006cefcc uv__async_io [/usr/local/bin/node]
10: 0x1006dea52 uv__io_poll [/usr/local/bin/node]
11: 0x1006cf406 uv_run [/usr/local/bin/node]
12: 0x1000b53dd node::NodeMainInstance::Run() [/usr/local/bin/node]
13: 0x10005d052 node::Start(int, char**) [/usr/local/bin/node]
14: 0x7fff695dbcc9 start [/usr/lib/system/libdyld.dylib]
15: 0x5 
zsh: illegal hardware instruction  sudo balena local configure ~/Downloads/balena.img
```

**Comment by pdcastro** [comment]
Thanks for reporting this issue. Some notes:
* What is the output of the `balena version -a` command? I wonder if this is something related to Node.js v13 or Node.js v14, which are not yet supported. If you can, try using Node.js v12 or v10.
* Note that `homebrew` is not an "official" distribution channel (it is maintained by balena users). Could you try one of the installation methods documented at https://github.com/balena-io/balena-cli/blob/master/INSTALL.md ? For example, the executable installer, even though with macOS Catalina you will come across issue #1479 which requires some juggling around security pop-ups (sorry for the trouble).

**Comment by pattyland** [comment]
```bash
pattyland@Air ~ % balena version -a
balena-cli version "11.31.22"
Node.js version "14.1.0"
```
So yes, I'm using an unsupported version. Strange that somebody made node 14.1.0 a dependency on homebrew: https://formulae.brew.sh/formula/balena-cli
As this your already working on node 14 support in #1770 I will close this :)
