### ISSUE TITLE
Leading zeroes stripped from device uuid

### ISSUE THREAD

**Issue by jeff-at-dwelo** [balena-io/balena-cli#1805]
It seems the CLI mysteriously strips leading zeroes from some device uuids. I discovered this when trying to script tag changes across our fleet. This doesn't happen on all devices with leading zeroes, but when it happens on a specific device it does happen consistently.

---
- **balena CLI version:** 11.32.10
- **Operating system version:** Debian 10 buster
- **32/64 bit OS and processor:** 64
- **Install method:** npm
- **If npm install, Node.js and npm version:** Node v12.16.3, npm 6.14.4

---
```
DEBUG=1 balena tag set TAGNAME foo --device '0783151'
[debug] original argv0="node" argv=[/home/username/.nvm/versions/node/v12.16.3/bin/node,/home/username/.nvm/versions/node/v12.16.3/bin/balena,tag,set,TAGNAME,foo,--device,0783151] length=8
BalenaDeviceNotFound: Device not found: 783151

BalenaDeviceNotFound: Device not found: 783151
    at /home/username/.nvm/versions/node/v12.16.3/lib/node_modules/balena-cli/node_modules/balena-sdk/build/models/device.js:390:35
    at processImmediate (internal/timers.js:456:21)
From previous event:
    at /home/username/.nvm/versions/node/v12.16.3/lib/node_modules/balena-cli/node_modules/balena-sdk/build/models/device.js:388:26
From previous event:
    at Object.get (/home/username/.nvm/versions/node/v12.16.3/lib/node_modules/balena-cli/node_modules/balena-sdk/build/models/device.js:361:31)
    at getResourceId (/home/username/.nvm/versions/node/v12.16.3/lib/node_modules/balena-cli/node_modules/balena-sdk/build/models/device.js:66:28)
    at /home/username/.nvm/versions/node/v12.16.3/lib/node_modules/balena-cli/node_modules/balena-sdk/build/util/dependent-resource.js:93:28
From previous event:
    at Object.set (/home/username/.nvm/versions/node/v12.16.3/lib/node_modules/balena-cli/node_modules/balena-sdk/build/util/dependent-resource.js:83:31)
    at Command.action (/home/username/.nvm/versions/node/v12.16.3/lib/node_modules/balena-cli/build/actions/tags.js:129:46)
    at runNextTicks (internal/process/task_queues.js:62:5)
    at processImmediate (internal/timers.js:429:9)
    at process.topLevelDomainCallback (domain.js:137:15)
```

**Comment by pdcastro** [comment]
Thanks for reporting this issue!
@srlowe, perhaps the best way of fixing this issue is to convert the `tag set` command from Capitano to oclif ASAP. Do you think it could be put ahead of other command conversions?
(It's already in Typescript, and the implementation is not particularly large.)

**Comment by srlowe** [comment]
@pdcastro Yeah sure.

**Comment by pdcastro** [comment]
@jeff-at-dwelo, as a temporary workaround, if possible use the device's "full uuid" instead the "short uuid", e.g. `0123456789abcdef0123456789abcdef` instead of `0123456`. Even if the full uuid starts with a zero, the leading zero won't be dropped because this only happens when the argument contains only decimal digits (and the full uuid will also include letters).

**Comment by jeff-at-dwelo** [comment]
Aha, that does make sense. Yeah that should let me work around this for now. Thanks!
