### ISSUE TITLE
Livepush process didn't exit after connection hangup

### ISSUE THREAD

**Issue by StefKors** [balena-io/balena-cli#1828]
Running live-push with a NUC on balena-on-balena devenv causes problems with connection hangups. 

# Expected Behavior
Livepush workflow for balena on balena development

# Actual Behavior
Device disconnect while developing the balena-api on a bob.
See logs: https://gist.github.com/StefKors/41f6f59d48c4a5fd7934387732eb1343

# Specifications
- **HOST OS VERSION** balenaOS 2.48.0+rev3
- **SUPERVISOR VERSION** 11.4.3
- **balena CLI version:** e.g. 1.2.3 (output of the `"balena version -a"` command)
- **Operating system version:**  macOS 10.15.4
- **32/64 bit OS and processor:** 64-bit Intel processor
- **Install method:** npm
- **If npm install, Node.js and npm version:** 12.8.4

# Additional References
FD: https://www.flowdock.com/app/rulemotion/resin-starters/threads/nQMxNkQq9aRIzfMg7cMuuXdKC00

**Comment by pdcastro** [comment]
Further discussion on a [another thread](https://www.flowdock.com/app/rulemotion/r-beginners/threads/-6VzEum82yOienwJxGhypOiZ6C-):

> The "Connection to device lost" message is printed on this line:
> https://github.com/balena-io/balena-cli/blob/v12.25.2/lib/utils/device/logs.ts#L48
> 
> When it happens, the promise returned by `displayDeviceLogs` would be resolved. `displayDeviceLogs` is called either here:  
> https://github.com/balena-io/balena-cli/blob/v12.25.2/lib/utils/device/deploy.ts#L267
> or here:  
> https://github.com/balena-io/balena-cli/blob/v12.25.2/lib/utils/device/deploy.ts#L288
> 
> Assuming the `--nolive` option is not used, it would be the former. In this case, an array of promises is awaited, including the promise returned by `livepush.init()`:
> 
> * https://github.com/balena-io/balena-cli/blob/v12.25.2/lib/utils/device/deploy.ts#L261
> * https://github.com/balena-io/balena-cli/blob/v12.25.2/lib/utils/device/live.ts#L85
