### ISSUE TITLE
Allow passing `--device-type` to `device register` command

### ISSUE THREAD

**Issue by sradevski** [balena-io/balena-cli#1833]
# Expected Behavior

One would be able to register any compatible device type to a device, so they can use their own UUID

# Actual Behavior

A device is registered as the default device type instead.

**Comment by pdcastro** [comment]
Labelling it a bug from the point of view that "the functionality is broken" if it does not allow specifying the device type when registering it. 🤔

**Comment by thgreasi** [comment]
Resolved by https://github.com/balena-io/balena-cli/pull/2533
