### ISSUE TITLE
Balena ssh not working since 12.1.15

### ISSUE THREAD

**Issue by rickardgranberg** [balena-io/balena-cli#1896]
# Expected Behavior
```
balena ssh <ip-address>
```
should ssh into the device

# Actual Behavior
```
balena ssh <ip-address>
```
> Part of the CLI could not be loaded. This typically means your CLI install is in a broken state.
> You can normally fix this by uninstalling and reinstalling the CLI.
> 
> Additional information may be available with the `--debug` flag.
> For help, visit our support forums: https://forums.balena.io
> For bug reports or feature requests, see: https://github.com/balena-io/balena-cli/issues/

Running with `--debug` gives the following:

> [debug] new argv=[/balena/balena-cli/balena,/snapshot/versioned-source/bin/balena,ssh,<ip-address>] length=4
> Part of the CLI could not be loaded. This typically means your CLI install is in a broken state.
> You can normally fix this by uninstalling and reinstalling the CLI.
> 
> Error: Cannot find module 'lodash/reduce'
> 1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:634:15)
>     at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1351:46)
>     at Function.resolveFilenameOptimized [as _resolveFilename] (/snapshot/versioned-source/node_modules/fast-boot2/index.js:57:33)
>     at Function.Module._load (internal/modules/cjs/loader.js:560:25)
>     at Module.require (internal/modules/cjs/loader.js:690:17)
>     at Module.require (pkg/prelude/bootstrap.js:1230:31)
>     at require (internal/modules/cjs/helpers.js:25:18)
>     at Promise.resolve.then (/snapshot/versioned-source/build/utils/device/ssh.js:7:55)
> 
> Additional information may be available with the `--debug` flag.
> For help, visit our support forums: https://forums.balena.io
> For bug reports or feature requests, see: https://github.com/balena-io/balena-cli/issues/
> 

# Steps to Reproduce the Problem

1. Install Balena CLI 12.1.15 or newer (I've tested with 12.1.16 and todays 12.3.1, both have the same problem)
1. Run balena ssh <ip-address>

Reverting to 12.1.14 and ssh works again.

# Specifications

- **balena CLI version:12.1.15**
- **Operating system version: Ubuntu 18.04**
- **32/64 bit OS and processor: 64-bit Linux and 64-bit Intel processor**
- **Install method: zip package** 

# Additional References
-

**Comment by pdcastro** [comment]
Thank you for reporting this issue, and apologies for the trouble it has caused you. We are investigating what went wrong, and I will post more details here shortly.

**Comment by pdcastro** [comment]
This issue is fixed in CLI release v12.3.2 in a "narrow way" (PR #1898). I am also working on another PR that has a more generic fix, and where I will add test code to prevent future regressions (PR #1897).

**Comment by rickardgranberg** [comment]
Impressed with the fast response. Just downloaded and ran 12.3.2 successfully. Thank you for the fix!

**Comment by pdcastro** [comment]
Closing this issue as some automated tests have now been added for `balena ssh` (PR #1909). (Coverage is still limited, but progressing in the right direction...) Thanks again for reporting this issue. 👍
