### ISSUE TITLE
Add "balena logs <app>" command

### ISSUE THREAD

**Issue by szony** [balena-io/balena-cli#1946]
# Expected Behavior

This is user feature request to add a way to see logs from entire application.

# Actual Behavior

Currently only "balena logs uuid" exists

**Comment by pdcastro** [comment]
Just trying to understand this better... Would this command collect logs from all devices in the application? And display them mixed together in the console, real time? Or save each device's logs to a separate file? And what if the application had 10,000 devices, and each produced multiple log message per second? It could be a huge amount of data... Perhaps the command could have a limit of X devices, either randomly chosen (as if sampling the fleet) or for a given list of UUIDs.

**Comment by srlowe** [comment]
@szony Would you be able to provide more info on the requirements for this?  Based on our assumptions, it sounds like something that would require changes across the stack (and need an arch call item).  cc @pdcastro

**Comment by srlowe** [comment]
Closing since it seems not possible to implement in CLI.
