### ISSUE TITLE
Add an environment variable to multiple applications, devices, or services.

### ISSUE THREAD

**Issue by nwneisen** [balena-io/balena-cli#1956]
This is a previously discussed issue that is desired to be added to the cli.

# Expected Behavior
Add an environment variable to multiple applications, devices, or services with one command.

# Actual Behavior
Not currently implemented

# Steps to Reproduce
`balena env add -d <uuid>,<uuid>...`
`balena env add -s <name>,<name>...`
`balena env add -a <name>,<name>...`

# Additional References
Originally mentioned in #323.

**Comment by nwneisen** [comment]
A few clarifications that come to mind with this one:

- The desire is to add one variable to multiple applications, devices, or services. As apposed to multiple variables to one application, device, or service. Or even a many to many possibility..
- Should it be possible to add the variable to a combination of devices, services, and applications? Such as:
`balena env add -d <uuid>,<uuid>... -s <name>,<name>... -a <name>,<name>...`. Or maybe it doesn't make sense to be putting the same variable in the different locations from a user's perspective.

**Comment by pdcastro** [comment]
> The desire is to add one variable to multiple applications, devices, or services

👍   I suspect the most common use case would be to list multiple devices.

> Should it be possible to add the variable to a combination of devices, services, and applications?

The `--service` option can already be used alongside `--device` or `--application`, but the `--device` and `--application` options are mutually exclusive. An explanation is that the variable value would usually be different between device and application: for example, an application variable being overridden (with a different value) for specific devices. I suggest preserving this behavior.
