### ISSUE TITLE
sudo balena config inject fails and returns "TypeError: Class constructor PinejsClientCore cannot be invoked without 'new'"

### ISSUE THREAD

**Issue by PastaGringo** [balena-io/balena-cli#1971]
# Expected Behavior

Inject the local config.json to the BalenaOS image.
I'm using the CLI version 12.3.3 because I can't use "balena device UUID" with the latest version of the Balena CLI and OpenBalena (latest version).

# Actual Behavior

```sudo balena config inject config.json --type raspberrypi4 --drive /Volumes/Transcend/Documents/OpenBalena/img/balena-cloud-raspberrypi4-64-2.48.0+rev1-dev-v10.8.0.img --debug```
```Class constructor PinejsClientCore cannot be invoked without 'new'
TypeError: Class constructor PinejsClientCore cannot be invoked without 'new'
    at new BalenaPine (/usr/local/lib/balena-cli/node_modules/balena-pine/build/pine.js:59:47)
    at getPine (/usr/local/lib/balena-cli/node_modules/balena-pine/build/pine.js:97:18)
    at getSdk (/usr/local/lib/balena-cli/node_modules/balena-config-json/node_modules/balena-sdk/build/balena.js:101:16)
    at Function.getSdk.fromSharedOptions (/usr/local/lib/balena-cli/node_modules/balena-config-json/node_modules/balena-sdk/build/balena.js:311:12)
    at Object.<anonymous> (/usr/local/lib/balena-cli/node_modules/balena-config-json/build/utils.js:20:32)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/local/lib/balena-cli/node_modules/balena-config-json/build/config.js:25:9)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)

Additional information may be available with the `--debug` flag.
For help, visit our support forums: https://forums.balena.io
For bug reports or feature requests, see: https://github.com/balena-io/balena-cli/issues/
```

# Specifications

- **balena CLI version:** balena-cli version "12.3.3" Node.js version "10.16.0"
- **Operating system version:** macOS 10.15.6
- **32/64 bit OS and processor:** 64-bit Intel processor
- **Install method:** executable installer

**Comment by PastaGringo** [comment]
Result with the v12.10.1 :

`sudo balena config inject config.json --type raspberrypi4 --drive /Users/XXX/Documents/OpenBalena/img/balena-cloud-raspberrypi4-64-2.48.0+rev1-dev-v10.8.0.img --debug `
```
[debug] new argv=[/usr/local/lib/balena-cli/bin/node,/usr/local/lib/balena-cli/bin/run,config:inject,config.json,--type,raspberrypi4,--drive,/Users/XXX/Documents/OpenBalena/img/balena-cloud-raspberrypi4-64-2.48.0+rev1-dev-v10.8.0.img] length=8
1: Command failed: /usr/sbin/diskutil unmountDisk force "/Users/XXX/Documents/OpenBalena/img/balena-cloud-raspberrypi4-64-2.48.0+rev1-dev-v10.8.0.img"
Unmount failed for /Users/XXX/Documents/OpenBalena/img/balena-cloud-raspberrypi4-64-2.48.0+rev1-dev-v10.8.0.img


Error: Command failed: /usr/sbin/diskutil unmountDisk force "/Users/XXX/Documents/OpenBalena/img/balena-cloud-raspberrypi4-64-2.48.0+rev1-dev-v10.8.0.img"
Unmount failed for /Users/XXX/Documents/OpenBalena/img/balena-cloud-raspberrypi4-64-2.48.0+rev1-dev-v10.8.0.img

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:198:13)
    at ChildProcess.EventEmitter.emit (domain.js:448:20)
    at maybeClose (internal/child_process.js:982:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
    at Socket.emit (events.js:198:13)
    at Socket.EventEmitter.emit (domain.js:448:20)
    at Pipe._handle.close (net.js:607:12)

Additional information may be available with the `--debug` flag.
For help, visit our support forums: https://forums.balena.io
For bug reports or feature requests, see: https://github.com/balena-io/balena-cli/issues/
```

**Comment by pdcastro** [comment]
@PastaGringo, the error shared above with v12.10.1 is probably because the `--drive` option does not accept an image file directly. The help / documentation is not very clear about it, but the word "mounted" is key:
```
$ balena help config inject
Usage: config inject <file>

Use this command to inject a config.json file to the mounted filesystem
(e.g. SD card or mounted balenaOS image) of a provisioned device.
```

On Linux, you would use a loop device ([ref1](https://en.wikipedia.org/wiki/Loop_device), [ref2](https://unix.stackexchange.com/questions/4535/what-is-a-loop-device-when-mounting)) to mount the image file as a "drive" like `/dev/disk2`, then the drive path is given to the `--drive` option.

By the way, consider also whether the `os configure` command may be more helpful, as it accepts an image file:
https://www.balena.io/docs/learn/more/masterclasses/advanced-cli/#32-configuring-a-provisioning-image

Regarding the error you got with v12.3.3 (`PinejsClientCore`), it was fixed in v12.3.4 (or you could downgrade further). Given that newer CLI versions currently prevent the `balena device` command working with openBalena (sorry about it), consider having multiple simultaneous installations of the balena CLI, perhaps using the standalone zip files (see [installation documentation](https://github.com/balena-io/balena-cli/blob/master/INSTALL.md)) as they can be simply unzipped to different folders. This way you could run `balena device` with v12.3.3, and other commands with a newer version.

**Comment by pdcastro** [comment]
Connects-to: #1970

**Comment by pdcastro** [comment]
Update: a new recommendation for openBalena users is to temporarily downgrade the CLI to v12.2.2, which should avoid the need of having multiple CLI installations (multiple versions) for different CLI commands. Also, the balena team is currently working on updating openBalena to support balena SDK v14 / v15, which will then allow the latest CLI version to be used again. We are discussing internally how to prevent this situation from re-occurring in the future, as it is of course problematic to users as well as to the balena team itself.

**Comment by pdcastro** [comment]
openBalena version 3 has been released,  🎉  
https://github.com/balena-io/open-balena/blob/master/CHANGELOG.md

It includes support for the new API endpoints and newer versions of the balena SDK, and therefore the latest CLI releases. I have successfully  tested openBalena v3 with CLI v12.25.6 (currently the latest version):

```
$ balena apps
ID APP NAME SLUG  DEVICE TYPE  ONLINE DEVICES DEVICE COUNT
1  myApp    myapp raspberrypi3 1              2

$ balena devices
ID UUID    DEVICE NAME  DEVICE TYPE  APPLICATION NAME STATUS IS ONLINE SUPERVISOR VERSION OS VERSION           DASHBOARD URL
2  7d0cb2c bold-paper   raspberrypi3 myApp            Idle   true      11.14.0            balenaOS 2.58.3+rev1 https://dashboard.vestamon.co.uk/devices/7d0cb2cb6e2e84ca7e75e554a9a8069b/summary
1  ae11d4f wild-glitter raspberrypi3 myApp                   false                                             https://dashboard.vestamon.co.uk/devices/ae11d4f3b4db426a98606252180758e6/summary

$ balena device 7d0cb2c
== BOLD PAPER
ID:                    2
DEVICE TYPE:           raspberrypi3
STATUS:                idle
IS ONLINE:             true
IP ADDRESS:            192.168.1.36
MAC ADDRESS:           B8:27:EB:94:74:69 B8:27:EB:C1:21:3C
APPLICATION NAME:      myApp
LAST SEEN:             2020-10-29T02:17:13.200Z
UUID:                  7d0cb2cb6e2e84ca7e75e554a9a8069b
COMMIT:                N/a
SUPERVISOR VERSION:    11.14.0
IS WEB ACCESSIBLE:     false
OS VERSION:            balenaOS 2.58.3+rev1
DASHBOARD URL:         https://dashboard.vestamon.co.uk/devices/7d0cb2cb6e2e84ca7e75e554a9a8069b/summary
CPU USAGE PERCENT:     6
CPU TEMP C:            45
CPU ID:                000000000894746
MEMORY USAGE MB:       278
MEMORY TOTAL MB:       745
MEMORY USAGE PERCENT:  37
STORAGE BLOCK DEVICE:  /dev/mmcblk0
STORAGE USAGE MB:      74
STORAGE TOTAL MB:      13929
STORAGE USAGE PERCENT: 1
```

For older versions of openBalena (older than v3.0.0), the recommendation remains to downgrade the CLI to v12.2.2.
