### ISSUE TITLE
Empty build args in v12.14.6

### ISSUE THREAD

**Issue by magnucha** [balena-io/balena-cli#1992]
# Expected Behavior
When running `balena build -a myApp -B SOME_VAR=$SOME_VAR` I expect the SOME_VAR build arg to match the content of my host machines SOME_VAR environment variable.

# Actual Behavior
After updating to balena-cli v12.14.6 the variables are not set during docker build, and contain empty strings.
This behavior does not occur with my previous balena-cli v12.6.5, when running the exact same command in the same repository.

# Steps to Reproduce the Problem
Update to balena-cli v12.14.6 and try using build arguments. During build, they should appear as empty strings.

# Specifications

- **balena CLI version:** 12.14.6
- **Cloud backend:** balenaCloud
- **Operating system version:** Ubuntu 18.04
- **32/64 bit OS and processor:** 64 bit
- **Install method:** zip package

**Comment by pdcastro** [comment]
Thank you for reporting this issue @magnucha 👍   I have found that it was introduced in CLI v12.9.9 during the conversion of the `build` command from [Capitano](https://github.com/balena-io/capitano/) to [oclif](https://oclif.io/). I am working on a fix, and will add more test code as well, so it doesn't regress. Meanwhile, please use CLI v12.9.8.

**Comment by pdcastro** [comment]
This issue was fixed in CLI release v12.14.10. Test code was added to prevent future regressions. Sorry for trouble it caused you, and thank you again for reporting it! 👍
