### ISSUE TITLE
Preload boot splash screen doesn't work on newer balenaOS versions

### ISSUE THREAD

**Issue by shaunmulligan** [balena-io/balena-cli#1993]
# Expected Behavior
The following command:
```
balena preload ./device.img --app APP_NAME --commit current --splash-image ./logo.png
```
It should insert `logo.png` into `resin-boot/splash/` and rename it to either `resin-logo.png` or `balena-logo.png` depending on the version of balenaOS

# Actual Behavior

Currently, the CLI will take `logo.png` and rename it to `resin-logo.png` and puts it into `resin-boot/splash/` the problem comes in because later OS versions do not notice resin-logo.png and so just uses `balena-logo.png` so it boots up with the wrong splash. We should detect the OS version we are configuring and write the correct name for this.

CLI version: 12.14.6
OS version: rpi4-raspberrypi4-64 2.53.12+rev1-dev

This file was renamed in `balenaOS v2.53.0`

**Comment by pdcastro** [comment]
Fixed in CLI v12.14.13.
