### ISSUE TITLE
Balena CLI version > v12.13.0 incompatible with last openbalena

### ISSUE THREAD

**Issue by M07ak** [balena-io/balena-cli#1998]
Balena CLI version higher than 12.13.0 is not compatible with the self hosted version of openbalena.

The error seems to be related to the V6 to API used by Balena CLI.

Error: <pre>Cannot GET /v6/my_application</pre>.

Downgrading to Balena CLI v12.13.0 fix the issue.

![image](https://user-images.githubusercontent.com/10629503/90409441-711c5b00-e0a9-11ea-9cc9-ad358e44f703.png)

**Comment by pdcastro** [comment]
@M07ak, thank you for reporting this issue. openBalena is a bit behind regarding support for recent versions of the [balena SDK](https://github.com/balena-io/balena-sdk), which is used by recent versions of the balena CLI. The current recommendation is to [downgrade to CLI version 12.2.2](https://github.com/balena-io/balena-cli/issues/1970#issuecomment-668842196). Work is ongoing to update openBalena (issue https://github.com/balena-io/open-balena-api/issues/338). Meanwhile, I have created a PR to update openBalena documentation at https://www.balena.io/open/docs/getting-started/ (pending review), as it currently recommends installing the latest version of the CLI which is not fully compatible. (Most CLI commands still work, but this is not good enough, of course.)

I will also keep this CLI issue open (thanks again for creating it) to widen visibility of the issue and the current recommendation (downgrade to CLI v12.2.2). Other CLI versions may also work, but v12.2.2 is a version believed to be "fully compatible".

**Comment by pdcastro** [comment]
openBalena version 3 has been released,  🎉  
https://github.com/balena-io/open-balena/blob/master/CHANGELOG.md

It includes support for the new API endpoints and newer versions of the balena SDK, and therefore the latest CLI releases. I have successfully  tested openBalena v3 with CLI v12.25.6 (currently the latest version):

```
$ balena apps
ID APP NAME SLUG  DEVICE TYPE  ONLINE DEVICES DEVICE COUNT
1  myApp    myapp raspberrypi3 1              2

$ balena devices
ID UUID    DEVICE NAME  DEVICE TYPE  APPLICATION NAME STATUS IS ONLINE SUPERVISOR VERSION OS VERSION           DASHBOARD URL
2  7d0cb2c bold-paper   raspberrypi3 myApp            Idle   true      11.14.0            balenaOS 2.58.3+rev1 https://dashboard.vestamon.co.uk/devices/7d0cb2cb6e2e84ca7e75e554a9a8069b/summary
1  ae11d4f wild-glitter raspberrypi3 myApp                   false                                             https://dashboard.vestamon.co.uk/devices/ae11d4f3b4db426a98606252180758e6/summary

$ balena device 7d0cb2c
== BOLD PAPER
ID:                    2
DEVICE TYPE:           raspberrypi3
STATUS:                idle
IS ONLINE:             true
IP ADDRESS:            192.168.1.36
MAC ADDRESS:           B8:27:EB:94:74:69 B8:27:EB:C1:21:3C
APPLICATION NAME:      myApp
LAST SEEN:             2020-10-29T02:17:13.200Z
UUID:                  7d0cb2cb6e2e84ca7e75e554a9a8069b
COMMIT:                N/a
SUPERVISOR VERSION:    11.14.0
IS WEB ACCESSIBLE:     false
OS VERSION:            balenaOS 2.58.3+rev1
DASHBOARD URL:         https://dashboard.vestamon.co.uk/devices/7d0cb2cb6e2e84ca7e75e554a9a8069b/summary
CPU USAGE PERCENT:     6
CPU TEMP C:            45
CPU ID:                000000000894746
MEMORY USAGE MB:       278
MEMORY TOTAL MB:       745
MEMORY USAGE PERCENT:  37
STORAGE BLOCK DEVICE:  /dev/mmcblk0
STORAGE USAGE MB:      74
STORAGE TOTAL MB:      13929
STORAGE USAGE PERCENT: 1
```

For older versions of openBalena (older than v3.0.0), the recommendation remains to downgrade the CLI to v12.2.2.
