### ISSUE TITLE
Balena-push on PiSupply Lora Gateway Hat

### ISSUE THREAD

**Issue by Weng0827** [balena-io/balena-cli#1999]
I'm setting up my Raspberry pi Model 4b with PiSupply Lora Gateway Hat. 
When I'm trying to push the file i downloaded from https://github.com/PiSupply/iot-lora-gateway-balena
it show's the following error any one know how to solve this ?
![balenaerror](https://user-images.githubusercontent.com/53169087/90867318-cae19580-e3c7-11ea-8aac-551e8aae1680.PNG)

**Comment by pdcastro** [comment]
Closing this issue with the understanding that it has been resolved or clarified, but feel free to add more comments.
