### ISSUE TITLE
`os versions` and `os download` not listing balenaOS ESR releases

### ISSUE THREAD

**Issue by pdcastro** [balena-io/balena-cli#2005]
At least for [Production and Enterprise plan](https://www.balena.io/pricing/) users (and for some device types like the Raspberry Pi 3, also for a few other plans?), the `os versions` and `os download --version menu` commands should list balenaOS ESR versions such as `v2020.07.1`, instead of the "usual" version format such as `v2.29.2+rev2`.

Balena support agents in the "Team member plan and standard support" should also be able to list ESR releases, but currently are not.

Originally reported in [this flowdock thread](https://www.flowdock.com/app/rulemotion/resin-devices/threads/iHHXQlkB5Dt-m2_EBzO3WlDBn1G).

# Expected Behavior

```
$ balena os versions
...
v2020.07.1
...
```

# Actual Behavior

```
$ balena os versions raspberrypi3
v2.53.9+rev1.prod (recommended)
v2.53.9+rev1.dev
v2.51.1+rev1.prod
...
```

See: https://www.flowdock.com/app/rulemotion/resin-devices/threads/BtGUlpKl9fyhDGpI1OJ4W32EfAD

**Comment by shawaj** [comment]
Any progress with this? We need this quite urgently

**Comment by pdcastro** [comment]
@shawaj, support for ESR versions was added to CLI v12.52.0 (or later). Check `balena help os download` and `balena help os versions` for notes regarding ESR support (options and limitations). Let us know if it works as you expected.
