### ISSUE TITLE
login: Sentry reports a large number of BalenaRequestError Request error: Unauthorized

### ISSUE THREAD

**Issue by pdcastro** [balena-io/balena-cli#2035]
Sentry reports a large number of `BalenaRequestError` `Request error: Unauthorized` errors:
* https://sentry.io/organizations/balena/issues/747313108/?project=149239
* https://sentry.io/organizations/balena/issues/1836332147/?project=149239

They come from the `login` command. I believe these are "harmless" and "expected" errors resulting from expired tokens, in which case the CLI should dismiss them without reporting to Sentry.

**Comment by srlowe** [comment]
@pdcastro Not sure if I'm looking in the wrong place, but both of those links you added point me to an incidence of:
```
BalenaRequestError

Request error: tunneling socket could not be established, statusCode=500
```
Triggered by `balena ssh`

**Comment by srlowe** [comment]
Ah, I found them : https://sentry.io/organizations/balena/issues/747313108/?project=149239
