### ISSUE TITLE
tunnel command uses unencrypted connection to backend server

### ISSUE THREAD

**Issue by pdcastro** [balena-io/balena-cli#2042]
The `balena tunnel` command establishes a TCP connection to a CONNECT HTTP proxy server at `vpn.balena-cloud.com:3128` with 'basic' HTTP authentication. This connection is not currently encrypted, making it subject to network sniffing - a security issue. (The connection is encrypted between the balenaCloud backend and the device, but not between the CLI and the balenaCloud backend.) The connection should be encrypted end to end.

This issue was originally kindly reported by a user in this forum thread:
* https://forums.balena.io/t/balena-tunnel-connections-are-not-encrypted/191826/
* Internal thread: https://jel.ly.fish/9ee8724d-50d6-40a8-8ccf-3ee7911cf6be

Proposed solutions:
* Enable (and require) TLS encryption on the existing TCP connection.
* Alternatively, use 'ssh' to the device in combination with `/usr/bin/nc`, as suggested in the forum thread linked above.
* Internal discussion: https://www.flowdock.com/app/rulemotion/resin-tech/threads/nOheKZaBwyMwC2PmzfPw0NxYEMl

Related `open-balena-vpn` issue: https://github.com/balena-io/open-balena-vpn/issues/149

**Comment by mcamou** [comment]
Hi, do you have a rough timeline when this might be fixed? Right now we're using the `socat`/`ssh` hack but it's not working reliably especially when we need to e.g. transfer binary files via a REST interface. I'm really not comfortable with my Balena token flying around the Internet unencrypted.

**Comment by pdcastro** [comment]
Thanks for chasing progress on this issue, @mcamou. 👍   I have re-raised it with the backend team. I gather that a decision was made to enable TLS on port `vpn.balena-cloud.com:3128`, but no one in team had picked it up -- that is, until today when @zwhitchcox bravely took it on him 👏    to implement it soon (at least on the backend, then we can amend the CLI to use it).

Thank you again for raising this issue.

**Comment by pdcastro** [comment]
@mcamou, starting with CLI version 12.38.5, the `balena tunnel` commands connects to a new balenaCloud endpoint:
* New: `tunnel.balena-cloud.com`, port 443, using TLS (CLI v12.38.5 and later)
* Old: `vpn.balena-cloud.com`, port 3128, no encryption (CLI v12.38.4 and earlier)

Older CLI clients are not affected. We intend to close external access to port 3128, which will then break `balena tunnel` for CLI releases older than v12.38.5. We are currently internally discussing a "grace period" before closing port 3128 (to be decided).

Thank you very much for reporting this issue and sharing the workarounds, 💯   and sorry for the delay in getting it resolved.

**Comment by mcamou** [comment]
That is good news @pdcastro. Thanks for letting me know!

**Comment by pdcastro** [comment]
And for any openBalena users reaching this issue: starting with openBalena version 3.1.2, openBalena also includes a new `tunnel` backend endpoint with TLS enabled. CLI release v12.38.5 and later requires openBalena v3.1.2 and later; older CLI releases should be used with older openBalena releases.

**Comment by pdcastro** [comment]
Connects-to: #2172 [balena tunnel: [Error] connect ETIMEDOUT](https://github.com/balena-io/balena-cli/issues/2172)
