### ISSUE TITLE
Should support Node 14 and higher

### ISSUE THREAD

**Issue by pdcastro** [balena-io/balena-cli#2079]
The balena CLI currently supports Node 10 ([>= 10.20.0](https://github.com/balena-io/balena-cli/blob/v12.26.0/package.json#L87)) and Node 12 only, as documented in the [installation instructions](https://github.com/balena-io/balena-cli/blob/master/INSTALL-ADVANCED.md#npm-installation).

With Node 14, it crashes as mentioned in issue #1990 [Illegal instruction: 4](https://github.com/balena-io/balena-cli/issues/1990)

What is currently missing in order to support Node 14 is solving a problem with the `ext2fs` dependency: https://github.com/balena-io-modules/node-ext2fs/issues/76 , which in turn blocks the Etcher SDK from supporting Node 14: https://github.com/balena-io-modules/etcher-sdk/issues/183

**Comment by pdcastro** [comment]
It looks like [etcher-sdk](https://www.npmjs.com/package/etcher-sdk) and [ext2fs](https://www.npmjs.com/package/ext2fs) were updated to support Node v14. We see below that the CLI is using (either directly or via old dependencies) old versions of `etcher-sdk` and `ext2fs`. Updating them might be what it takes to support Node v14. It may require pull requests and testing in other repos like `balena-image-fs`, `resin-image-fs` (same repo?), `balena-config-json`, `resin-cli-visuals`. (This last one might be replaceable with `cli-ux`.) Because they are major version bumps, we need to be careful with any API compatibility issues.
```
$ npm list
...
├─┬ balena-config-json@4.1.0
│ ├─┬ balena-image-fs@7.0.1
│ │ ├─┬ ext2fs@2.0.1
...
├─┬ resin-image-fs@5.0.9
│ ├─┬ ext2fs@1.0.31
...
├─┬ etcher-sdk@2.0.20
...
├─┬ resin-cli-visuals@1.7.0
│ ├── etcher-sdk@2.0.20 deduped
```

**Comment by pdcastro** [comment]
Also recently reported: #2165 [livepush: CLI exits unexpectedly (no error) with Node.js v14](https://github.com/balena-io/balena-cli/issues/2165)

**Comment by mbalamat** [comment]
Modules to fix:
* https://github.com/balena-io-modules/balena-device-init
* https://github.com/balena-io-modules/resin-device-operations
* https://github.com/balena-io-modules/resin-cli-visuals

**Comment by myarmolinsky** [comment]
Closing as we currently support node >= 20.6.0
