### ISSUE TITLE
Nanopi Neo Air not in application list

### ISSUE THREAD

**Issue by maggie0002** [balena-io/balena-cli#2082]
When doing 'balena app create' through the CLI to an Open Balena instance, there is no Nanopi Neo Air option, despite the OS being available in the Balena OS website. 

CLI version: 12.26.1

**Comment by pdcastro** [comment]
Thank you for reporting this issue, @maggie0002 👍    The openBalena team have already found the problem (pull request balena-io/open-balena/pull/96) and released the fix in openBalena version 3.1.0 - [CHANGELOG](https://github.com/balena-io/open-balena/blob/master/CHANGELOG.md). Building on the [Getting Started](https://www.balena.io/open/docs/getting-started/) instructions, to update your installation:

```
cd open-balena
./scripts/compose down
git pull --ff-only
./scripts/compose up -d
```

```
$ balena devices supported | grep neo
nanopi-neo-air                                      armv7hf Nanopi Neo Air

$ $ balena app create test
? Device Type
  Microsoft Surface Go (NEW)
  NPE X500 M3
  NanoPC-T4 (NEW)
❯ Nanopi Neo Air
  Nitrogen8M Mini SBC (NEW)
  Nvidia D3 TX2
  Nvidia Jetson Nano SD-CARD (NEW)
(Move up and down to reveal more choices)
Application created: test (nanopi-neo-air, id 2)
```
