### ISSUE TITLE
Ideally `balena devices` should not show dashboard url in openBalena context

### ISSUE THREAD

**Issue by srlowe** [balena-io/balena-cli#2089]
The `Dashboard Url` column in the `balena devices` results is causing confusion for openBalena users (since dash is not supported).  Ideally this column should not be shown in the openBalena context (maybe by checking the domain in settings?)

https://jel.ly.fish/view-all-support-threads/support-thread-discourse-207326

**Comment by pdcastro** [comment]
Duplicates #2055
