### ISSUE TITLE
Add malware warning note to INSTALL_MAC.md

### ISSUE THREAD

**Issue by danthegoodman1** [balena-io/balena-cli#2180]
Add a note in `INSTALL-MAC.md` that you have to `Right click`>`Open` to get around the warning.

The code could also be signed to prevent the popup

**Comment by pdcastro** [comment]
Closing this issue because the graphical installer is now notarized -- since #2186 was merged, thanks @danthegoodman1 💯  -- and because the advanced installation document mentions a workaround for the standalone zip package.
