### ISSUE TITLE
Feature request: local flash taking <target drive> parameter

### ISSUE THREAD

**Issue by LeFish1** [balena-io/balena-cli#2201]
# Expected Behavior

`local flash` does not only take the `<image>` parameter, but also a `<target drive>` parameter.

A call would the look like
`balena local flash <image> <target drive>`

# Actual Behavior

This feature currently does not exist.

**Comment by pdcastro** [comment]
@LeFish1, I think this feature already exists, in the form of the `--drive` flag:
```
$ balena help local flash
...
OPTIONS
  -d, --drive <drive>  the drive to write the image to, eg. `/dev/sdb` or `/dev/mmcblk0`.
                       Careful with this as you can erase your hard drive.
                       Check `balena util available-drives` for available options.

  -h, --help           show CLI help

  -y, --yes            answer "yes" to all questions (non interactive use)

DESCRIPTION
  Flash a balenaOS image to a drive.
  Image file may be one of: .img|.zip|.gz|.bz2|.xz

  If --drive is not specified, then it will interactively
  show a list of available drives for selection.

EXAMPLES
  $ balena local flash path/to/balenaos.img
  $ balena local flash path/to/balenaos.img --drive /dev/disk2
  $ balena local flash path/to/balenaos.img --drive /dev/disk2 --yes
```

**Comment by LeFish1** [comment]
@pdcastro , thank you very much - I tested it. I kinda worked, but showed the same behaviour as the older etcher v 1.1.2 - it hangs at random percentages.

Maybe it is a bug?

**Comment by pdcastro** [comment]
> it hangs at random percentages until some user interactions (buttons pressed...).

I see that you have created issue #2202 about the hanging problem - thank you 👍 
I think we can close this issue because the `--drive` flag implements the feature, and will look at the hanging problem in that other issue. Feel free to add any comments even after this issue is closed (I can always reopen it if needed).
