### ISSUE TITLE
Patch file for "open" is outdated for open-7.4.2

### ISSUE THREAD

**Issue by doronbehar** [balena-io/balena-cli#2234]
# Expected Behavior

Being able to install `balena-cli` with `npm`.

# Actual Behavior

Installing `balena-cli` with `npm` fails due to the patch of package `open` being outdated.

```
Skipping dev-only pkg@4.4.9 ✔

Failed to apply some patches:
Error: 
Warning: patch-package detected a patch file version mismatch

  Don't worry! This is probably fine. The patch was still applied
  successfully. Here's the deets:

  Patch file created for

    @oclif/plugin-help@3.2.0

  applied to

    @oclif/plugin-help@3.2.2
  
  At path
  
    node_modules/@oclif/plugin-help

  This warning is just to give you a heads-up. There is a small chance of
  breakage even though the patch was applied successfully. Make sure the package
  still behaves like you expect (you wrote tests, right?) and then run

    patch-package @oclif/plugin-help

  to update the version in the patch file name and make this warning go away.


**ERROR** Failed to apply patch for package open at path
  
    node_modules/open

  This error was caused because open has changed since you
  made the patch file for it. This introduced conflicts with your patch,
  just like a merge conflict in Git when separate incompatible changes are
  made to the same piece of code.

  Maybe this means your patch file is no longer necessary, in which case
  hooray! Just delete it!

  Otherwise, you need to generate a new patch file.

  To generate a new one, just repeat the steps you made to generate the first
  one.

  i.e. manually make the appropriate file changes, then run 

    patch-package open

  Info:
    Patch file: patches/open+7.1.0.patch
    Patch was made for version: 7.1.0
    Installed version: 7.4.2

---
patch-package finished with 1 warning(s), 1 error(s).

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! balena-cli@12.43.2 postinstall: `node patches/apply-patches.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the balena-cli@12.43.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /build/.npm/_logs/2021-03-27T08_57_33_163Z-debug.log
```

# Steps to Reproduce the Problem

I'm building the package with [node2nix](https://github.com/svanderburg/node2nix) but I _think_ this should be reproducible on a clean machine, because you use `^` at:

https://github.com/balena-io/balena-cli/blob/2737c9c53c0c670f87ff3b1a91f770f071a3ba83/package.json#L249

And the fact that you don't use a `package-lock.json`.

# Specifications

- **balena CLI version:** 12.43.2
- **Cloud backend: openBalena or balenaCloud?** Irrelevant
- **Operating system version:** NixOS
- **32/64 bit OS and processor:** x86_64
- **Install method:** npm
- **If npm install, Node.js and npm version:** Node v12.21.0 and npm v6.14.11

# Additional References

- According to https://david-dm.org/balena-io/balena-cli the `open` package is also outdated.
- Is this related to https://github.com/balena-io/balena-cli/issues/1751 ?

**Comment by doronbehar** [comment]
Opened the issue before putting any info to it by mistake. Sorry for the noise :pray:.

**Comment by pdcastro** [comment]
@doronbehar, thank you for reporting this issue. I haven't used `node2nix` before, but the patching errors you have quoted sound to me like `node2nix` is ignoring the balena CLI's [npm-shrinkrap.json](https://github.com/balena-io/balena-cli/blob/master/npm-shrinkwrap.json). For example, `open` is pinned to version "7.1.0" on this line:
https://github.com/balena-io/balena-cli/blob/v12.43.2/npm-shrinkwrap.json#L11208

I see in the `node2nix` documentation that they have a `-l` flag for `package-lock.json`, so perhaps try:

`node2nix -l npm-shrinkwrap.json`
https://github.com/svanderburg/node2nix#using-npm-lock-files

For more information on the differences between `npm-shrinkwraps.json` and `package-lock.json`, see:

* https://stackoverflow.com/questions/44258235/what-is-the-difference-between-npm-shrinkwrap-json-and-package-lock-json
* https://docs.npmjs.com/cli/v6/configuring-npm/shrinkwrap-json
* https://docs.npmjs.com/cli/v6/configuring-npm/package-lock-json

**Comment by pdcastro** [comment]
> Installing balena-cli with npm fails due to the patch of package open being outdated.
> I'm building the package with node2nix [...]

To confirm, I have not been able to reproduce this issue with Node v12.21.0 and npm v6.14.11, and I assume it only happens when `node2nix` is used. If you can reproduce it without using `node2nix`, try deleting the `node_modules` folder as suggested in #1715.

**Comment by doronbehar** [comment]
Thanks a lot for the info @pdcastro ! Since `npm-shrinkwrap.json` is published in the registry, I think node2nix should respect it when it fetches information about dependencies of a package.
