### ISSUE TITLE
It's not possible to pass in commands to ssh

### ISSUE THREAD

**Issue by Hades32** [balena-io/balena-cli#2275]
# Expected Behavior

```bash
$ balena ssh uuid -- hostname
mydevicename
```

# Actual Behavior

```bash
$ balena ssh uuid -- hostname
Could not find a service hostname on device <uuid>.
```

# Current Workaround
I know I can do 
```bash
echo "hostname" | balena ssh uuid
```
But this is inconvenient, unexpected to long-time users of ssh and will not yield the same results as the former. E.g. exit codes might not be returned correctly and doesn't exit the shell after the command finishes.

**Comment by pdcastro** [comment]
Sounds like a duplicate of #1482, though I think that issue does not mention a double dash preceeding the remote command.

**Comment by Hades32** [comment]
ah yes you're right. Didn't find that in my search
