### ISSUE TITLE
macOS installer missing in release v12.44.22

### ISSUE THREAD

**Issue by bartversluijs** [balena-io/balena-cli#2284]
Hi,

I wanted to installed the newest Balena CLI (release v12.44.22), but the macOS installer is missing from the [releases page](https://github.com/balena-io/balena-cli/releases/tag/v12.44.22).  

Can this installer be added to the release, or am I missing something?

Thanks in advance!

**Comment by pdcastro** [comment]
@bartversluijs, thanks for reporting this issue. It looks like the CI build failed to upload the macOS installer to GitHub, and a CI bug meant that this did not cause the build to fail as it should have. I have now re-triggered the build and the installer was uploaded: https://github.com/balena-io/balena-cli/releases/tag/v12.44.22
