### ISSUE TITLE
`balena ssh <ip-addr>` should attempt `<username>@<ip-addr>` in addition to `<root>@<ip-addr>`

### ISSUE THREAD

**Issue by pdcastro** [balena-io/balena-cli#2292]
**Summary**

`balena ssh 192.168.10.10` to a [production image](https://www.balena.io/docs/reference/OS/overview/2.x/#development-vs-production-images) of balenaOS results in "Permission denied (publickey)".

**Known workarounds**

* Use plain ssh instead of `balena ssh`, with the balena account username. Example:
```
ssh -p 22222 gh_paulo_castro@192.168.10.10
```

* Alternatively, [add a ssh key to config.json](https://www.balena.io/docs/reference/OS/configuration/#sshkeys)

**Detailed description**

Currently, `balena ssh 192.168.10.10` translates to `ssh -p 22222 root@192.168.10.10`, using the `root` user account. This works with [development images](https://www.balena.io/docs/reference/OS/overview/2.x/#development-vs-production-images) of balenaOS that allow passwordless root access, but not with production images unless a ssh key had been previously "manually" added to the [sshKeys sections of config.json](https://www.balena.io/docs/reference/OS/configuration/#sshkeys).

However, balenaOS devices (since ~~some version of~~ balenaOS v2.44.0) also allow `ssh -p 22222 username@192.168.10.10`, where `username` is the user's balena account username as shown on the web dashboard and as reported by `balena whoami`, in which case, as I understand, the device will attempt to fetch the user's ssh public key from balenaCloud to complete the authentication. I understand that this applies to both development and production images of balenaOS.

In this case, the CLI is missing a trick: translating `balena ssh 192.168.10.10` to `ssh -p 22222 username@192.168.10.10`, where `username` comes from `balena login` / `balena whoami`.

For development images, `root@<ip-addr>` connects faster and more reliably, as it does not require the device to query balenaCloud. Perhaps a solution is for the CLI to attempt `root` first, with a short timeout, and if it fails, then attempt `username`. There could also be flags to force one behaviour or the other.

**References**

Internal discussion:
* https://www.flowdock.com/app/rulemotion/r-beginners/threads/bJOAo9gMdWtrhyQ3ql12qu9iO3z
* https://www.flowdock.com/app/rulemotion/r-beginners/threads/zeOV7satU29TwrGE4Jbfe12xlBE

**Comment by pdcastro** [comment]
Consider also "unmanaged devices" that are not connected to the cloud -- only `root@<ip-addr>` would work for those devices.

**Comment by 20k-ultra** [comment]
This style of trying to use several login options is also seen in normal SSH authentication. When a SSH client is authentication to a server it will try all the keys in a user's ssh folder. So, use using different usernames is sort of the same philosophy.

Additionally, SSH lets you control this better with [IdentityFiles](https://www.ssh.com/academy/ssh/identity-key) which maybe we can get some inspiration from as well. I'm not entirely familiar with these files though.

**Comment by pdcastro** [comment]
> since some version of balenaOS

I gather that the feature of using a ssh key stored in balenaCloud (non-root user authentication) requires balenaOS v2.44.0 or later: [changelog](https://github.com/balena-os/meta-balena/blob/master/CHANGELOG.md#v2440), [pull request](https://github.com/balena-os/meta-balena/pull/1549/files).

**Comment by pdcastro** [comment]
This issue was resolved for connections to the host OS, however `balena ssh <ip-address> <service>` with production variants of balenaOS is still affected by issue #2458.
