### ISSUE TITLE
 "Application is ambiguous" but device UUID is specified

### ISSUE THREAD

**Issue by 20k-ultra** [balena-io/balena-cli#2306]
In the following snippet I am setting a device variable for the sideshow-bob service. I am explicitly saying a device UUID which is unique across balenaCloud. However, the CLI responds saying that it can't figure out what to do because my account had access to more then 1 fleet (application) named balena-on-balena. After renaming one of those fleets

```
mig@ghost ~$ balena env add API_TOKEN ${balena_api_token} \                                                                                                               
  --service sideshow-bob \
  --device 0bd0bfe
Application is ambiguous: balena-on-balena, service: sideshow-bob
```

**Expected results**
To set service variable for device specified

**Actual results**
CLI says it cannot figure out what device to update because "Application is ambiguous"

**Steps to reproduce**
1. create an application with the same name as an app in another org so your account has access to 2 applications of the same name
2. run above command

**Comment by pdcastro** [comment]
Fixed in CLI v12.45.1. Thanks for reporting it! 👍
