### ISSUE TITLE
Registry Connection Timeout

### ISSUE THREAD

**Issue by HenrikWittemeier** [balena-io/balena-cli#2310]
Hi together, 
i use an gitlab runner for CI. Usually it works fine, but sometimes i get an timeout for uploading images.
The Operating system is Raspbian on a Raspberry PI 4 with 4 GB RAM.

```[Info]    Saving release... \
[Info]    Saving release...
[Error]   Deploy failed
Get https://registry2.balena-cloud.com/v2/: dial tcp: lookup registry2.balena-cloud.com on 192.168.188.1:53: read udp 192.168.188.39:51129->192.168.188.1:53: i/o timeout
```
This issue appears randomly, stays only for a few minutes. Around two or three times a week.

The IP 192.168.188.39 is the IP of the RaspberryPi.

Unfortunately i dont have any Debug messages. But if you need i can try to catch them.

Maybe you can say if this issue is according to my network, or to balena-cloud. (Maybe downtimes?) --> Happened at (Aug 21, 2021 1:03pm GMT+0200)

**Comment by pdcastro** [comment]
That error message looks like a DNS lookup error in the local network. Specifically, `read udp 192.168.188.39:51129->192.168.188.1:53` tells us that the Raspberry Pi sent a UDP packet to `192.168.188.1:53`, where port number 53 is the port number of a local DNS server, running in gateway/router `192.168.188.1`. DNS servers typically use the UDP protocol. Furthermore, the error message tells us that it was during a lookup of hostname `registry2.balena-cloud.com`. It would be the equivalent of running, e.g. on my laptop:
```
$ host registry2.balena-cloud.com
registry2.balena-cloud.com is an alias for a251a80e271154d4ea823607c449750e-144134624.us-east-1.elb.amazonaws.com.
a251a80e271154d4ea823607c449750e-144134624.us-east-1.elb.amazonaws.com has address 44.193.56.50
a251a80e271154d4ea823607c449750e-144134624.us-east-1.elb.amazonaws.com has address 3.219.225.63
a251a80e271154d4ea823607c449750e-144134624.us-east-1.elb.amazonaws.com has address 52.86.204.64
```
Or:
```
$ nslookup registry2.balena-cloud.com
Server:		192.168.1.1
Address:	192.168.1.1#53

Non-authoritative answer:
registry2.balena-cloud.com	canonical name = a251a80e271154d4ea823607c449750e-144134624.us-east-1.elb.amazonaws.com.
Name:	a251a80e271154d4ea823607c449750e-144134624.us-east-1.elb.amazonaws.com
Address: 52.86.204.64
Name:	a251a80e271154d4ea823607c449750e-144134624.us-east-1.elb.amazonaws.com
Address: 3.219.225.63
Name:	a251a80e271154d4ea823607c449750e-144134624.us-east-1.elb.amazonaws.com
Address: 44.193.56.50
```
So, such a query would be failing for the Raspberry Pi. Note: the error does not indicate a failure to open a network connection to the registry; it fails before that stage, while attempting to resolve a hostname (registry2.balena-cloud.com) into an IP address (e.g. `44.193.56.50`). The next question is why. According to the following command, apparently balena uses [Cloudflare](https://www.cloudflare.com/) for the authoritative DNS servers:
```
$ dig +short NS balena-cloud.com
todd.ns.cloudflare.com.
dahlia.ns.cloudflare.com.
```
In theory Cloudflare could have had intermittent name resolution issues, but it would have affected many users and I have not heard any other reports, so more likely than not it would be a local network issue. Actually, even if Cloudflare had had issues, I am not sure it would manifest as `i/o timeout` as per error message. It would most likely have been a different error. Perhaps `i/o timeout` is really saying that the DNS server in the local gateway/router (`192.168.188.1`) was not available.

Here's a suggestion: experimentally, change the Raspberry Pi's name server from `192.168.188.1` to `8.8.8.8`, which is Google's DNS name server. Google has a pretty solid uptime record (when they're down, the world is down). :-)  Even then, there would still be a possibility of a local network issue dropping internet access altogether, but then you might be able to debug it further by trying to access or resolve other sites / hostnames.

**Comment by HenrikWittemeier** [comment]
Never happened again without any action
