### ISSUE TITLE
Will not install

### ISSUE THREAD

**Issue by Sven491** [balena-io/balena-cli#2319]
I installed it on my computer but i can't run it please help me

**Comment by pdcastro** [comment]
Hi @Sven491,
Is your computer running Windows, macOS or Linux?

Try closing and re-opening any command prompt / terminal windows:
* If your computer is running Windows, click on the Windows Start Menu, type PowerShell, and then click on Windows PowerShell.
* If your computer is running macOS, follow these instructions: [Open the Terminal app](https://support.apple.com/en-gb/guide/terminal/apd5265185d-f365-44cb-8b09-71a064a42125/mac)

The type `balena version` and the Enter key. It should display the version of the balena CLI that you have installed.

**Comment by srlowe** [comment]
Closing due to lack of response.
