### ISSUE TITLE
balena build does not tag the resulting image when using `--tag`

### ISSUE THREAD

**Issue by pipex** [balena-io/balena-cli#2327]
# Expected Behavior

Image tag should be set on resulting image when doing `balena build --tag`

```
my-project $ balena build -f my-fleet -t my-image:v1.1.0
[Build]   Built 1 service in 0 seconds
[Success] Build succeeded!
my-project $ docker images 
REPOSITORY                 TAG              IMAGE ID       CREATED          SIZE
my-project_main           latest           0ab63e543ead   21 minutes ago   221MB
my-image                      v1.1.0           0ab63e543ead   21 minutes ago   221MB
```

# Actual Behavior

Tag does not get set
```
my-project $ balena build -f my-fleet -t my-image:v1.1.0
[Build]   Built 1 service in 0 seconds
[Success] Build succeeded!
my-project $ docker images 
REPOSITORY                 TAG              IMAGE ID       CREATED          SIZE
my-project_main           latest           0ab63e543ead   21 minutes ago   221MB
```
balena push 192.168.0.12
balena deploy myFleet
balena deploy myFleet --build
balena build . -f myFleet
balena build . -A armv7hf -d raspberrypi3
```

```

# Steps to Reproduce the Problem

1. Run `balena build -f <fleet name> -t <some tag>`
2. Check the list of built images with `docker images`

# Specifications

- **balena CLI version:** 
balena-cli version "12.46.0"
Node.js version "12.20.0"
- **Cloud backend: balenaCloud?** 
- **Operating system version:** macOS 11.4
- **32/64 bit OS and processor:** 64-bit Intel processor
- **Install method:** executable installer

**Comment by pdcastro** [comment]
Sounds like a duplicate of #825, and connects to #1018.

**Comment by pipex** [comment]
I promised I searched the issues first. Closing this one then
