### ISSUE TITLE
Add support for the release model

### ISSUE THREAD

**Issue by toochevere** [balena-io/balena-cli#2329]
## Description

Add support to list, get info, and finalize releases.  Also, add support to list and add tags.  

## References
See: https://www.flowdock.com/app/rulemotion/r-supervisor/threads/JN2-gnspQ-v6WaeWCvm9T8NYDY1

**Comment by pdcastro** [comment]
Until this is implemented, a workaround to convert a draft release to a final release is the following `curl` command line:

```sh
curl -X PATCH "https://api.balena-cloud.com/v6/release?\$filter=commit%20eq%20'${COMMIT}'" \
    -d "{\"is_final\": true}" -H "Content-type: application/json" \
    -H "Authorization: Bearer ${API_TOKEN}"
```

Where `${COMMIT}` should be replaced with the release hash / UUID, a value in the format `382d59948f87890a7c646d734ffff000`.

As a convenience, on Linux or WSL or macOS, if you are logged in to the balena CLI on your machine, the API token expression can be replaced with `-H "Authorization: Bearer $(cat ~/.balena/token)"`

To query / print the release object, the command line is:

```
curl -X GET "https://api.balena-cloud.com/v6/release?\$filter=commit%20eq%20'${COMMIT}'" \
   -H "Authorization: Bearer ${API_TOKEN}" | jq .
```
Where `| jq .` is optional -- it prettifies the output.

**Comment by toochevere** [comment]
Closed with https://github.com/balena-io/balena-cli/pull/2345
