### ISSUE TITLE
Can't specify pre-release versions in `balena.yml`

### ISSUE THREAD

**Issue by jrc** [balena-io/balena-cli#2337]
# Expected Behavior

When specifying a version in `balena.yml`, I expect to be able to provide pre-release versions e.g. "1.0.0-a.1". This is supported in the [SemVer specification, item 9](https://semver.org/#spec-item-9):

> A pre-release version MAY be denoted by appending a hyphen and a series of dot separated identifiers immediately following the patch version. Identifiers MUST comprise only ASCII alphanumerics and hyphens [0-9A-Za-z-]. Identifiers MUST NOT be empty. Numeric identifiers MUST NOT include leading zeroes. Pre-release versions have a lower precedence than the associated normal version. A pre-release version indicates that the version is unstable and might not satisfy the intended compatibility requirements as denoted by its associated normal version. Examples: 1.0.0-alpha, 1.0.0-alpha.1, 1.0.0-0.3.7, 1.0.0-x.7.z.92, 1.0.0-x-y-z.–.

# Actual Behavior

Upon running `balena push`, the current CLI outputs a warning message "[Warning]  The balena.yml version field must be a 3 digit semver (eg: 1.0.0). Please update your balena.yml or use the Dashboard to update the release version".
The version shown in the dashboard becomes "0.0.0+rev67"
This is reproducible with both `version: 1.0.0-a.1` and `version: 1.0.0+a.1` in `balena.yml`. 

Additionally: the part of the warning message "use the Dashboard to update the release version" seems to be erroneous, as I don't see any way of doing this.

# Specifications

- **balena CLI version:** 12.48.12
- **Operating system version:** macOS 10.15.7

# Additional References

* https://github.com/balena-io/balena-cli/issues/2336

**Comment by pdcastro** [comment]
Thanks for this feedback 👍  
It is something on our radar, and needs to be implemented in the API data model first:
balena-io/open-balena-api/issues/749 [Should support all valid semver values in the release.semver field](https://github.com/balena-io/open-balena-api/issues/749)
