### ISSUE TITLE
Should stop using balena-sync

### ISSUE THREAD

**Issue by thgreasi** [balena-io/balena-cli#2453]
Since we are only using a small part of it and relying on a module with such name just for the `discover` functionality, we should move the implementation inside the CLI and drop the dependency to balena-sync (maybe later we could make a `discover` standalone module, but it doesn't have to be now).
See: https://www.flowdock.com/app/rulemotion/i-cli/threads/UaLodwWrtDZI7fEl8mTumBks9xS

**Comment by myarmolinsky** [comment]
Closing as we are not using `balena-sync`
