### ISSUE TITLE
'Error: Cannot find module '/Users/run'

### ISSUE THREAD

**Issue by warnes** [balena-io/balena-cli#2459]
# Expected Behavior

`balena version` should display version information

# Actual Behavior

Using a fresh install of Balena CLI using `balena-cli-v13.2.0-macOS-x64-installer.pkg`:
```bash
~ balena version
usage: dirname string [...]
usage: basename string [suffix]
       basename [-a] [-s suffix] string [...]
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module '/Users/run'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

# Steps to Reproduce the Problem

1. Download and execute `balena-cli-v13.2.0-macOS-x64-installer.pkg` from [
](https://github.com/balena-io/balena-cli/releases/download/v13.2.0/balena-cli-v13.2.0-macOS-x64-installer.pkg)
1. Open a terminal window
1. Execute `balena version`

# Specifications

- **balena CLI version:**  Filename suggests 13.2.0
- **Cloud backend: openBalena or balenaCloud?** balenaCloud
- **Operating system version:** MacOS 12.2.1
- **32/64 bit OS and processor:** 2.6 GHz 6-Core Intel Core i7
- **Install method:** installer package

**Comment by warnes** [comment]
It appears that the `balena` script is having trouble properly resolving its install path.

If I run the command via the link in /usr/local/bin it generates the error: ```bash
bash-3.2$ balena version
usage: dirname string [...]
usage: basename string [suffix]
       basename [-a] [-s suffix] string [...]
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module '/Users/run'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```
But if I use it's full path it executes successfully:

```bash
bash-3.2$ /usr/local/lib/balena-cli/bin/balena version
13.2.0
bash-3.2$
```

**Comment by pdcastro** [comment]
Thanks for reporting it @warnes, however I was not able to reproduce it:
```
$ balena version -a
balena-cli version "13.2.0"
Node.js version "12.20.0"

$ /usr/local/bin/balena version -a
balena-cli version "13.2.0"
Node.js version "12.20.0"

$ sw_vers
ProductName:	macOS
ProductVersion:	12.2.1
BuildVersion:	21D62
```

Above, the Node.js version refers to the Node.js binary that is shipped with (built in) the balena CLI installer for macOS -- there is no need to install Node.js separately. The `sw_vers` command shows the version of macOS (12.2.1 = Monterey).

Could it be that another, previous installation of the balena CLI still has priority in the PATH environment variable?
Check the contents of the PATH variable and the output of the `'which balena'` command:
```
$ echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

$ which balena
/usr/local/bin/balena
```
If a previous installation of the balena CLI exists in a folder other than `'/usr/local/bin'` with higher priority (listed first) in the PATH environment variable, this might explain the behaviour you were observing.

Also, just in case, try exiting your terminal application and starting it again. Sometimes, the shell itself might get in a strange state as a result of running some scripts that don't fully terminate or with subtle bugs.

**Comment by pdcastro** [comment]
> But if I use it's full path it executes successfully
> `/usr/local/lib/balena-cli/bin/balena version`

And what about neither `'balena'` nor `'/usr/local/lib/balena-cli/bin/balena'`, but:

```
$ /usr/local/bin/balena version -a
balena-cli version "13.2.0"
Node.js version "12.20.0"
```

**Comment by warnes** [comment]
I found the problem:  I had a non-standard `readlink` in my path.  Removing it resolved the problem.
