### ISSUE TITLE
command `balena fleet restart <fleet>` gives error `BalenaApplicationNotFound`

### ISSUE THREAD

**Issue by saveriogzz** [balena-io/balena-cli#2468]
### Setup
* balena-cli version 13.3.1
* openBalena running on remote server

# Expected Behavior

When I run the command `balena fleet restart <fleet>` I expect all the devices of my fleet to reboot.

# Actual Behavior

When running the aforementioned command, I get the error
```
BalenaApplicationNotFound: Application not found: 7
```
This happens both when specifying the fleet with its slug as well as solely the fleet's name.

**Comment by toochevere** [comment]
Hello @saveriogzz.  What environment are you targeting?  Balena cloud or open balena?  What are the results of running `balena whoami`?  I am able to successfully reboot my fleet using `balena fleet restart`.

**Comment by saveriogzz** [comment]
hey @toochevere , the `balena whoami` command gives me back `USERNAME: admin`. I'm targeting an openBalena environment.

**Comment by toochevere** [comment]
Can you paste the result of the following commands?  
`balena fleets`
`balena fleet <fleet>`

If you find that `balena fleet <fleets>` in fact works (gives you fleet info) then try the following: 
1) Create a new test user
2) Create a fleet for that test user
3) Do `balena login` with the test user's credentials
4) Try `balena fleet restart <fleet` and post the result.

**Comment by saveriogzz** [comment]
* `balena fleets`
```bash
ID NAME                SLUG                      DEVICE TYPE     ONLINE DEVICES DEVICE COUNT
7  davisFleetRaspiFour admin/davisfleetraspifour raspberrypi4-64 3              4
8  parsivelDataLogger  admin/parsiveldatalogger  raspberrypi4-64 0              0
```

* `balena fleet admin/davisfleetraspifour`
```bash
== admin/davisfleetraspifour
ID:          7
DEVICE TYPE: raspberrypi4-64
SLUG:        admin/davisfleetraspifour
COMMIT:      c66b05c8cb3a7ad7fc301a6333df1d83
```
---

Unfortunately, openBalena is single user and I'm not able to create a new user!

**Comment by toochevere** [comment]
Ok, the problem is that `fleet restart` is not a function that exists on openBalena.  It only exists currently on Balena Cloud.  

This is extremely not clear, as evidenced by the fact that I was also not aware of this either.  I am surfacing at a weekly product call internally a topic of how we can be more clear about what CLI functions are available on openBalena and which ones are not.  In the meantime, however, you can open an issue on the openBalena repo if you wish.

**Comment by saveriogzz** [comment]
Thanks @toochevere !
