### ISSUE TITLE
Unsupported device types appear on the `devices supported` output

### ISSUE THREAD

**Issue by alexgg** [balena-io/balena-cli#2524]
# Expected Behavior

Unsupported device types should not appear on the `devices supported` list.

# Actual Behavior

As soon as work to support a device is started and there is a contract for it, the device appears in the API device endpoint and hence in the output of `balena devices supported` but the device type is not yet usable.

Probably a further API check to make sure there are final releases in the hostapp should be made before listing the device.

# Steps to Reproduce the Problem

Right now the `Radxa zero` in in this state, and:
balena devices supported | grep -i "radxa"
radxa-zero aarch64 Radxa Zero

# Specifications
 * balena --version
14.2.0

**Comment by myarmolinsky** [comment]
@thgreasi Can you confirm whether this is the desired behavior for `devices supported` and furthermore for the sdk's `deviceTypes.getAllSupported` method? If so then to fix this we need to update the $filter in the sdk method to only keep deviceTypes with finalized releases: https://github.com/balena-io/balena-sdk/blob/4473a25667aadd144f1bd90cc5ea72f0c9d736d3/lib/models/device-type.ts#L190

**Comment by thgreasi** [comment]
Fixed by https://github.com/balena-io/balena-cli/pull/2607
