### ISSUE TITLE
Balena-CLI support for node.js version 18 is missing

### ISSUE THREAD

**Issue by pascal-buchs** [balena-io/balena-cli#2620]
# Expected Behavior
I would expect Balena-CLI to support at least LTS node.js version 18, which will be maintained until April 2025 rather than end-of-life versions or versions that will soon be marked as end-of-life.

# Actual Behavior
Currently it only supports version 14 which is end-of-life since 2023-04-30
https://github.com/balena-io/balena-cli/blob/master/INSTALL-ADVANCED.md#npm-installation
https://github.com/nodejs/Release

The next LTS node.js version that is still maintained would be 16, but this version will also soon be end-of-life on 2023-09-11: https://nodejs.org/en/blog/announcements/nodejs16-eol

Is there any roadmap/timeline on when the balena-cli will fully support node.js 18?

**Comment by otaviojacobi** [comment]
Hello, this is being worked in #2667 Because this will require a major change we will possibly use it to include a few other changes that are still WIP, so it might take still some weeks until publish

**Comment by otaviojacobi** [comment]
Fixed by #2667 Node 18 is currently the supported version, it might work on node 16 still but I don't think it will for too long
