### ISSUE TITLE
Add support for node 20 with CLI npm package.

### ISSUE THREAD

**Issue by rcooke-warwick** [balena-io/balena-cli#2659]
Currently I've seen strange behaviour when using the CLI npm package with node 20. 

So far this is `balena push` failing to reach the builders, giving a 404 error. 

We should add node 20 support. 

Node 18 seemed to work ok from what I can tell so far, despite https://github.com/balena-io/balena-cli/issues/2620 - I haven't seen any dysfunctional behaviour. The binary works fine with whatever node version of course, but is not convenient when managing versions

**Comment by otaviojacobi** [comment]
Done on #2720 2720
