### ISSUE TITLE
balena-cli 17.1.1 build failure

### ISSUE THREAD

**Issue by chenrui333** [balena-io/balena-cli#2675]
👋 trying to build the latest release, but run into some build issue. The error log is as below:

<details>
<summary>error build log</summary>

```
  npm verb stack Error: command failed
  npm verb stack     at ChildProcess.<anonymous> (/opt/homebrew/Cellar/node/20.5.1/libexec/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:53:27)
  npm verb stack     at ChildProcess.emit (node:events:514:28)
  npm verb stack     at maybeClose (node:internal/child_process:1105:16)
  npm verb stack     at Socket.<anonymous> (node:internal/child_process:457:11)
  npm verb stack     at Socket.emit (node:events:514:28)
  npm verb stack     at Pipe.<anonymous> (node:net:337:12)
  npm verb pkgid balena-cli@17.1.1
  npm verb cwd /private/tmp/balena-cli-20230905-19663-136x7ib/package
  npm verb Darwin 20.6.0
  npm verb node v20.5.1
  npm verb npm  v9.8.0
  npm ERR! code 1
  npm ERR! path /opt/homebrew/Cellar/balena-cli/17.1.1/libexec/lib/node_modules/balena-cli
  npm ERR! command failed
  npm ERR! command sh -c node patches/apply-patches.js
  npm ERR! Applying patches from "patches/all"...
  npm ERR! Failed to apply some patches:
  npm ERR! Error: Command failed: node node_modules/patch-package/index.js --patch-dir patches/all
  npm ERR! 
  npm ERR! Warning: patch-package detected a patch file version mismatch
  npm ERR! 
  npm ERR!   Don't worry! This is probably fine. The patch was still applied
  npm ERR!   successfully. Here's the deets:
  npm ERR! 
  npm ERR!   Patch file created for
  npm ERR! 
  npm ERR!     @oclif/config@1.18.16
  npm ERR! 
  npm ERR!   applied to
  npm ERR! 
  npm ERR!     @oclif/config@1.18.17
  npm ERR!   
  npm ERR!   At path
  npm ERR!   
  npm ERR!     node_modules/@oclif/config
  npm ERR! 
  npm ERR!   This warning is just to give you a heads-up. There is a small chance of
  npm ERR!   breakage even though the patch was applied successfully. Make sure the package
  npm ERR!   still behaves like you expect (you wrote tests, right?) and then run
  npm ERR! 
  npm ERR!     patch-package @oclif/config
  npm ERR! 
  npm ERR!   to update the version in the patch file name and make this warning go away.
  npm ERR! 
  npm ERR! Error: Patch file found for package oclif which is not present at node_modules/oclif
  npm ERR! ---
  npm ERR! patch-package finished with 1 warning(s), 1 error(s).
  npm verb exit 1
```

</details>

full build log, https://github.com/Homebrew/homebrew-core/actions/runs/6117295766/job/16603781998
relates to Homebrew/homebrew-core#141495

**Comment by myarmolinsky** [comment]
Hi, have you run `npm ci`? Version 17.1.0 bumped the version of oclif we were using to version 3 so node modules changes are expected

**Comment by otaviojacobi** [comment]
Hello @chenrui333 thanks for trying to upload the homebrew formula for the cli. I think the failure here https://github.com/Homebrew/homebrew-core/pull/141495 was being caused by a package that was droped on balena 17.1.3. Could you please retry with 7.1.3 ?

**Comment by chenrui333** [comment]
looks like 17.2.0 works for me in my local, checking with CI now, https://github.com/Homebrew/homebrew-core/pull/152077

**Comment by otaviojacobi** [comment]
@chenrui333 i think i see why ci fails. At somepoint you do "npm ci", which installs only the prod dependencies. Whe. Patch-packages library tries to patch the oclif library (which is now a dev dependency) it does not find it

**Comment by chenrui333** [comment]
i see, but somehow it works in my local though.

**Comment by chenrui333** [comment]
> @chenrui333 i think i see why ci fails. At somepoint you do "npm ci", which installs only the prod dependencies. Whe. Patch-packages library tries to patch the oclif library (which is now a dev dependency) it does not find it

removing the oclif patch works for me, thanks!

- https://github.com/Homebrew/homebrew-core/pull/152751
