### ISSUE TITLE
Migrate macOS publish pipeline to use new notarization toolchain

### ISSUE THREAD

**Issue by ab77** [balena-io/balena-cli#2687]
See, https://developer.apple.com/documentation/technotes/tn3147-migrating-to-the-latest-notarization-tool?changes=_3_3

https://github.com/balena-io/balena-cli/blob/master/automation/build-bin.ts#L464-L482

**Comment by otaviojacobi** [comment]
Done in https://github.com/balena-io/balena-cli/pull/2639
