### ISSUE TITLE
`balena block create` actually creates a fleet

### ISSUE THREAD

**Issue by PatrickHallek** [balena-io/balena-cli#2705]
# Expected Behavior

`balena block create test-block -o your_org --type qemux86-64` should create a block

# Actual Behavior

`balena block create test-block -o your_org --type qemux86-64` creates a fleet instead

  Examples:

# Specifications

- balena-cli v17.4.3
- Node.js v18.17.0
- balenaCloud
- macOS 13.4
- npm installer v9.6.7

**Comment by otaviojacobi** [comment]
Hello @PatrickHallek really sorry about this one. I am working on a fix right away and expect have it published very soon

**Comment by otaviojacobi** [comment]
Should be fixed on v17.4.4
