### ISSUE TITLE
MacOS apple silicon binaries?

### ISSUE THREAD

**Issue by Geethree** [balena-io/balena-cli#2723]
Not sure where else to post this. I'd love for the releases to include an apple silicon binary? 

I'd be happy to help do so if someone left me some breadcrumbs.

**Comment by otaviojacobi** [comment]
Hello, thanks for the request, as per https://github.com/balena-io/balena-cli/pull/2745 we now publish signed arm64 .pkg and unsigned arm64 standalones, you can check them at https://github.com/balena-io/balena-cli/releases/tag/v18.1.1
