### ISSUE TITLE
allow move device to accept an array of UUIDs

### ISSUE THREAD

**Issue by shaunmulligan** [balena-io/balena-cli#323]
It would be super useful it the `resin device move` could allow someone to move a batch of devices from one application to another.

**Comment by shaunmulligan** [comment]
`device rm`  as well as `env add` and `env rm` would also be awesome to have as batch actions.

**Comment by nwneisen** [comment]
I would like to take a look at adding this feature.

My fist thought was to change the `uuid` parameter of `move` to be a string array of uuids. This could end up breaking user's scripts and be a change for everyone used to the interface. 

My second thought is to have a second method that allows for multiple devices to be moved using a string array of uuids. I'm thinking `balena devices move [<uuid>, [uuid]]`. 

Let me know which interface is preferred and I will switch my code over accordingly.

**Comment by pdcastro** [comment]
> to change the `uuid` parameter of `move` to be a string array of uuids. This could end up breaking user's scripts [...]

Like `balena device move uuid1,uuid2,uuid3` ? Actually, if no spaces were allowed in the list, it would not necessarily be a breaking change, would it? From oclif's point of view, it would still be a single string argument, and our own code (`run()` function in `move.ts`) could split the string at the commas.

> to have a second method [...] `balena devices move [<uuid>, [uuid]]`

No!! :-) You mean we'd have `device move` and `devices move`, doing the same except for the number of arguments? Background: a common criticism of the CLI is that, as it is, it already has several commands that partially overlap in functionality, and this is considered confusing for users.

Additional option:
```
balena device move uuid1 uuid2 uuid3 -a newApp
```
This looks like backwards compatible with the present `balena device move uuid -a newApp`. I see that oclif mentions the possibility of "variable length arguments":
> For variable length arguments, disable argument validation with `static strict = false` on the command.
> https://oclif.io/docs/args It may require some testing / experimentation to check it works 

I don't think I ever tried it though. Also, we should test whether the position of the `-a` flag matters:
`balena device move uuid1 uuid2 uuid3 -a newApp`
`balena device move -a newApp uuid1 uuid2 uuid3`

Ideally the position of `-a` would not matter; if it does, it may still be acceptable, but we'd have to document it.

@srlowe, do you have any additional thoughts on this?

**Comment by srlowe** [comment]
I think either of the approaches @pdcastro outlined are fine. I think option B looks a bit nicer, but we can be sure option A works regardless of oclif quirks (because there remains only a singe arg), so it's probably the safer option (especially since oclif support for variadic arguments seems to be a bit in flux at the moment).

**Comment by srlowe** [comment]
For background, here's an open oclif PR which indicates that the approach to properly support this has not been decided upon.  (So, best to go with `balena device move uuid1,uuid2,uuid3` IMO)

**Comment by nwneisen** [comment]
I opened a PR for this change with the move command and comma separated UUIDs. If it looks good then I will open additional PRs for the `device rm`, `env add`, and `env rm` commands.
