### ISSUE TITLE
Can't use arrows on windows in 'quickstart'

### ISSUE THREAD

**Issue by Tryum** [balena-io/balena-cli#348]
I could not select wifi over ethernet in the configuration after downloading the image.

It worked during the 'resin config reconfigure' thought.

**Comment by jviotti** [comment]
Hi @Tryum ,

I'm aware of some https://github.com/SBoudrias/Inquirer.js quirks in Windows. What Windows version and terminal emulator are you using?

**Comment by Tryum** [comment]
It was on windows 10, and I was using the default terminal (cmd.exe).

Thibault Jochem
Software Engineer
EFREI Promo 2007

**Comment by jviotti** [comment]
Awesome, I'll try to reproduce and either create a ticket in Inquirer, or attempt to fix myself.

**Comment by LucianBuzzo** [comment]
Closing this issue as `quickstart` was removed in v10 https://github.com/balena-io/balena-cli/commit/6a9eeaaba2e9cc15d0801347105b3227f1064374
