### ISSUE TITLE
resin local push environment variables

### ISSUE THREAD

**Issue by lekkas** [balena-io/balena-cli#441]
Containers created with `resin local push` should have env vars that are expected to be found in resin.io apps as well, like:
```
RESIN_APP_NAME: container name
RESIN_APP_ID=0
RESIN_HOST_OS_VERSION=Resin OS Dev
RESIN_SUPERVISOR_ADDRESS=http://127.0.0.1:48484",
"RESIN_SUPERVISOR_HOST=127.0.0.1",
"RESIN_SUPERVISOR_PORT=48484",
RESIN_SUPERVISOR_API_KEY=
RESIN_API_KEY=deadbeef
RESIN=1
RESIN_SUPERVISOR_VERSION
```

**Comment by devxpy** [comment]
Any update on this?

Setting env variables in local dev mode seems impossible.

The `.env` file is usually in the `.gitignore`, so resin ignores it.

OTOH, If I use `--skip-gitignore` option, then I end up with un-necessary files on my device.

**Comment by pimterry** [comment]
@devxpy This issue isn't about setting custom env vars, it's about the default env vars that would exist in a Resin.io production deploy.

For your issue, you can pass env vars for a local push on the command line, like so:

```bash
resin local push ... --env VAR=a --env VAR2=b
```

Does that work for you?

**Comment by devxpy** [comment]
@pimterry  Thanks!

**Comment by krasi-georgiev** [comment]
I know it is an old thread but passing a file for all env would be quite nice.

Is this possible with the most recent cli version?

**Comment by pdcastro** [comment]
@krasi-georgiev, unfortunately this is not yet implemented. See [this comment](https://github.com/balena-io/balena-cli/issues/919#issuecomment-511610637) in a related issue #919, where a user shared a script that makes use of the `xargs` command to automate the expansion of variables defined in a file into `--env` arguments to the `balena push` command.

**Comment by pdcastro** [comment]
Actually, there were 2 separate issues discussed above:

1. Containers created with `resin local push` (obsolete, now `balena push <ip-address>`) should have env vars that are expected to be found in `resin.io` (balenaCloud) apps.
2. Setting custom / user environment variables, including a list of variables defined in a file.

For the 1st issue, as of CLI v11.18.2, I've just tested the `balena push <ip-address>` command and it looks like the "balenaCloud variables" are all there in the 'main' app container, so presumably this issue has already been fixed:

```
$ env | grep BALENA
BALENA_DEVICE_TYPE=raspberrypi3
BALENA_APP_ID=1
BALENA_APP_LOCK_PATH=/tmp/balena/updates.lock
BALENA_API_KEY=9ba...
BALENA_SUPERVISOR_API_KEY=914...
BALENA_SUPERVISOR_VERSION=10.2.2
BALENA_SUPERVISOR_HOST=127.0.0.1
BALENA_API_URL=https://api.balena-cloud.com
BALENA_HOST_OS_VERSION=balenaOS 2.43.0+rev1
BALENA_SUPERVISOR_ADDRESS=http://127.0.0.1:48484
BALENA_SUPERVISOR_PORT=48484
BALENA_SERVICE_HANDOVER_COMPLETE_PATH=/tmp/balena/handover-complete
BALENA_SERVICE_NAME=main
BALENA_DEVICE_UUID=5d3...
BALENA_DEVICE_NAME_AT_INIT=crimson-resonance
BALENA=1
BALENA_APP_NAME=localapp
```

For the 2nd issue (custom env vars from a file), there is another more specific Github issue about it: #919 [Environment variables file for "balena push <ip-address>"](https://github.com/balena-io/balena-cli/issues/919). That issue also includes an xargs-based workaround script shared by another user.

Therefore, I think this issue can be closed (in favour of #919).

**Comment by pdcastro** [comment]
I now realise that custom balenaCloud application and device environment variables (e.g. defined via the web dashboard) don't show up in app containers when using `balena push <ip-address>`. There is however another issue specifically for this: #656

**Comment by krasi-georgiev** [comment]
nice thanks!
