### ISSUE TITLE
Resin Sync: Child process exited with code 12

### ISSUE THREAD

**Issue by pimterry** [balena-io/balena-cli#460]
https://sentry.io/resinio/cli/issues/240477489/

```
Error: Child process exited with code 12
  File "...\AppData\Roaming\npm\node_modules\resin-cli\node_modules\resin-sync\build\shell.js", line 94, in null.<anonymous>
    throw new Error("Child process exited with code " + code);
```

**Comment by pimterry** [comment]
See https://www.flowdock.com/app/rulemotion/resin-frontend/threads/3mVRqk4wsDYouJYHmQP66lr-4PI. To quote @lekkas:

> it looks like it is a setup issue (prob. ssh keys)

> iirc resin code 12 can mean a general ssh error (rsync uses ssh to connect to the device) one thing we can do is return a more friendly message to the user when rsync exits with code 12

**Comment by pimterry** [comment]
I've managed to reproduce this myself locally. Device was working fine, but then the app container died (I synced some broken code and the app crashed). From then on all syncs consistently returning code 12. Example logs:

```
Getting information for device: d12d7bbfb1e5e6d4c5ee6ed3e2ce646c
Got application container info.
\ Syncing to /usr/src/app on d12d7bb...Application container must be active.
| Syncing to /usr/src/app on d12d7bb...rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at /BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-47/rsync/io.c(453) [sender=2.6.9]
Synced /usr/src/app on d12d7bb.
Application container started after failed 'sync'.
resin sync failed. Error: Child process exited with code 12
Child process exited with code 12
```

Restarting the application container and rerunning resin sync sorted that out fine. Could be that other users are hitting this similarly, and resin sync just needs to better handle the app container not running case.

**Comment by mietlicki** [comment]
Still have the same symptoms. Container is running normally. Restarting the application does not solve the problem.

**Comment by mietlicki** [comment]
I am running "resin sync <uuid> --verbose --source . --destination /usr/src/app" from a windows git bash administrator session. It seels that it wants to sync to "C:/Program Files/Git/usr/src/app" which is a Windows path that means nothing on the destination...

**Comment by pspelman** [comment]
@mietlicki Did you ever figure this out? I am having this issue currently.

**Comment by ericfode** [comment]
I am also having this issue. Strangely a sync will occasionally work, or work partially.

**Comment by pdcastro** [comment]
The `sync` command was removed in CLI v11, replaced with the ["live push" feature](https://www.balena.io/blog/living-on-the-edge-with-livepush-and-other-cli-improvements/) which is enabled by default with the `balena push` command.
