### ISSUE TITLE
Expose the list of supported device types and their aliases

### ISSUE THREAD

**Issue by emirotin** [balena-io/balena-cli#467]
With aliases.

And also mention that device types can have alternative names.

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_1da1)

**Comment by pimterry** [comment]
Basic support for this is already done, see `resin devices supported`. Closing.

**Comment by lekkas** [comment]
@pimterry just a heads up that the support conversation where this ticket originated from (https://app.frontapp.com/open/cnv_4c4n9h) suggested that we would look into presenting the users with any existing device type aliases as well (e.g. `raspberrypi` alias for `raspberry-pi`). 

I'm not sure where we stand about aliases now, do we ignore them completely? If not, are they documented somewhere?
