### ISSUE TITLE
Can't delete an app that has a dependent application

### ISSUE THREAD

**Issue by LucianBuzzo** [balena-io/balena-cli#469]
When trying to delete an app that has a dependent application I receive the error:
`ResinApplicationNotFound: Application not found: Virtuality9`

At the very least the error message should be accurate and explain why the app cannot be deleted.
Ideally, another dialogue should show, asking if the dependant application should be deleted.

**Comment by myarmolinsky** [comment]
Closing as dependent applications are no longer a thing
