### ISSUE TITLE
Don't require sudo when discovery is not needed

### ISSUE THREAD

**Issue by lekkas** [balena-io/balena-cli#477]
For instance, when running `resin local push [ip]` we could optimise the process and not require sudo

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_d903)

**Comment by emirotin** [comment]
Want to try it yourself or want me to work on it? The key is to offload the minimal task that requires sudo to an internal command and sudo-spawn it when needed - see the os init command and the internal.js for examples

**Comment by brownjohnf** [comment]
+1 on this. It also makes the .resin-sync.yml file owned by root, which is irritating.

**Comment by lekkas** [comment]
Hey @emirotin , it would be great if you have time to look into this.

**Comment by emirotin** [comment]
OK will do as soon as I have time

**Comment by zrzka** [comment]
As @brownjohnf said ...

> It also makes the .resin-sync.yml file owned by root, which is irritating.

👍

**Comment by lekkas** [comment]
Related to #542

**Comment by pdcastro** [comment]
Related to #385

**Comment by pdcastro** [comment]
The `resin local push` command was replaced with `balena push` and a new implementation in CLI v11. It no longer requires sudo.
