### ISSUE TITLE
Release standalone version (that ships with Node.js)

### ISSUE THREAD

**Issue by jviotti** [balena-io/balena-cli#484]
Various Etcher components that take care of the writing are going native. Since Etcher is also going to publish a CLI version, we sorted out a way to embed Node.js on the package,  code-sign it, and thus avoid any compilation need.

This will be part of Capitano in the future, but for now, take a look at the following Etcher scripts:

- Makefile target: https://github.com/resin-io/etcher/blob/master/Makefile#L253
- Bash script: https://github.com/resin-io/etcher/blob/master/scripts/build/node-package-cli.sh

The way it works is that we download a patched version of Node.js that locks its own entry point to an `index.js` file in the same file of the binary. 

In order to make use of this feature, we need to make sure the Resin CLI code can be concatenated into a single file.

**Comment by emirotin** [comment]
The updated plan is to use pkg (as ethcer does atm, too).

**Comment by cron410** [comment]
+1 I'm a n00b with NPM. I can't get it to work at all in the Windows 10 Bash environment. Yes I really should be using Linux for that.

**Comment by pimterry** [comment]
A standalone cross-platform version is definitely coming eventually, hopefully before the end of the year. Watch this space!

**Comment by pdcastro** [comment]
I think this issue has been implemented, no? What is missing?
https://www.balena.io/docs/reference/cli/#standalone-install
