### ISSUE TITLE
Ask for confirmation if the password is weak

### ISSUE THREAD

**Issue by emirotin** [balena-io/balena-cli#488]
As we add this feature to the UI we would also like to have it in the CLI where if the password is weak we would ask for the confirmation upon setting or changing it.

**Comment by 20k-ultra** [comment]
I haven't found anywhere in the documentation for the CLI which allows you to change your password. Also, the UI does not prompt for a confirmation of weak passwords.  Any info on this @pdcastro ? I'd say we can just close this issue if the CLI doesn't allow you to set your balenaCloud password.

**Comment by pdcastro** [comment]
You're right @20k-ultra, the CLI allows a password to be entered through the `balena login` command, but does not allow it to be set or changed. Where the user does not yet have a balenaCloud account, the CLI points them to the web dashboard:
```
$ balena login

Logging in to balena-cloud.com
? How would you like to login? I don't have a balena account!
Please sign up at https://dashboard.balena-cloud.com/signup
```
I don't know if the CLI allowed passwords to be changed in a distant past, but if so, it's no longer the case.
Closing this issue.
