### ISSUE TITLE
Print warning on `resin local push` with env vars if a `sync` is going to be performed

### ISSUE THREAD

**Issue by brownjohnf** [balena-io/balena-cli#492]
I find it confusing that if you 1) run `resin local push` with no env vars, change your application code to expect env vars, and then run `resin local push -e SOMEVAR=blah`, resin-cli will intelligently use `sync` (which is great), but silently ignore the env vars you've set (since the container is just restarted, not re-created). I understand *why* this is the behavior, but I think we should print a warning that your env vars will have no effect. It would have saved me some frustrated digging.

**Comment by pimterry** [comment]
This would potentially be solved by https://github.com/resin-io/resin-cli/issues/491. If we move to separate deploy/sync commands then you're explicitly opting in to one of those behaviours, and it's much less likely that this would unexpectedly bite you. It'd be very easy from there to always refuse `-e` arguments on `resin local sync` too for example, to make this totally impossible.

**Comment by pdcastro** [comment]
The `local push` and `sync` commands were removed in CLI v11, replaced with the ["live push" feature](https://www.balena.io/blog/living-on-the-edge-with-livepush-and-other-cli-improvements/) which is enabled by default with the new `balena push` command.
