### ISSUE TITLE
resin sync failing with up() in/out/err failed

### ISSUE THREAD

**Issue by lekkas** [balena-io/balena-cli#530]
```
Getting information for device: [uuid]
Got application container info.
\ Syncing to /usr/src/app on [uuid]...dup() in/out/err failed
rsync: read error: Connection reset by peer (104)
rsync error: error in rsync protocol data stream (code 12) at /usr/src/rsync/rsync-3.0.8/io.c(760) [sender=3.0.8]
Synced /usr/src/app on [uuid].
Application container started after failed 'sync'.
resin sync failed. Error: Child process exited with code 12
Child process exited with code 12
```

**Comment by pimterry** [comment]
Notably that's the same exit code as https://github.com/resin-io/resin-cli/issues/460

**Comment by pdcastro** [comment]
The `sync` command was removed in CLI v11, replaced with the ["live push" feature](https://www.balena.io/blog/living-on-the-edge-with-livepush-and-other-cli-improvements/) which is enabled by default with the `balena push <ip-address>` command. See also: [Deploy to your Fleet](https://www.balena.io/docs/learn/deploy/deployment/) documentation.
