### ISSUE TITLE
Display shared applications

### ISSUE THREAD

**Issue by jhermsmeier** [balena-io/balena-cli#531]
Currently when running `resin apps` only owned applications are displayed, while shared applications can only be seen when specifying their names explicitly through `resin app <name>`.

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_1ojb)

**Comment by myarmolinsky** [comment]
I can see all fleets I have access to when run `balena fleets` (whether I own them or have been added to them) so I think this has been fixed
