### ISSUE TITLE
Error: Child process exited with code 3221225781

### ISSUE THREAD

**Issue by pimterry** [balena-io/balena-cli#560]
https://sentry.io/resinio/cli/issues/257152385/

```
Error: Child process exited with code 3221225781
  File "C:\Users\flesler\AppData\Roaming\npm\node_modules\resin-cli\node_modules\resin-sync\build\shell.js", line 94, in null.<anonymous>
    throw new Error("Child process exited with code " + code);
  File "C:\Users\flesler\AppData\Roaming\npm\node_modules\resin-cli\node_modules\bluebird\js\release\util.js", line 16, in tryCatcher
    return target.apply(this, arguments);
  File "C:\Users\flesler\AppData\Roaming\npm\node_modules\resin-cli\node_modules\bluebird\js\release\promise.js", line 509, in Promise._settlePromiseFromHandler
    x = tryCatch(handler).apply(this._boundValue(), value);
  File "C:\Users\flesler\AppData\Roaming\npm\node_modules\resin-cli\node_modules\bluebird\js\release\promise.js", line 569, in Promise._settlePromise
    this._settlePromiseFromHandler(handler, receiver, value, promise);
  File "C:\Users\flesler\AppData\Roaming\npm\node_modules\resin-cli\node_modules\bluebird\js\release\promise.js", line 614, in Promise._settlePromise0
    this._settlePromise(promise, handler, receiver, value);
...
(15 additional frame(s) were not displayed)

Error: Child process exited with code 3221225781
```

**Comment by pimterry** [comment]
See https://www.flowdock.com/app/rulemotion/r-beginners/threads/3EaDsSkzSCdVrKukO3BJASxRwzd

Looks likely that this is caused by missing/broken Visual C++ redistributable - if confirmed, we should catch this and show some clearer instructions for that.

**Comment by flesler** [comment]
I'm running this on Git Bash, Windows 10. Using the `rsync` that you get when installing with [this installer](https://sourceforge.net/projects/mingw/files/Installer/).

My `.resin-sync.yml` is as follows (plus the `uuid`):
```yml
source: .
destination: /usr/src/app
progress: true
verbose: true
ignore:
  - .git
  - node_modules/
  - images
```

**Comment by pimterry** [comment]
@flesler Did you try installing the Visual C++ redistributable? I'm not sure if 2010 or 2015, but it looks very likely that one of those (or some other version) should solve this on your system, based on other reports for this error code in other applications.

**Comment by flesler** [comment]
I think the problem is with my `rsync`, I tried using it standalone and failed. I'll delve into this asap and let you know how it went

**Comment by pdcastro** [comment]
This error can no longer be found in Sentry.io. The `sync` command was removed in CLI v11, replaced with the ["live push" feature](https://www.balena.io/blog/living-on-the-edge-with-livepush-and-other-cli-improvements/) which is enabled by default with the `balena push <ip-address>` command. See also: [Deploy to your Fleet](https://www.balena.io/docs/learn/deploy/deployment/) documentation.
