### ISSUE TITLE
Support for resin local build, current resin build requires login

### ISSUE THREAD

**Issue by jacintoArias** [balena-io/balena-cli#578]
Current `resin build` requires  a successful `resin login`, as it might take application information to parse the `Dockerfile.template`, but I can think of some use cases where local builds could be used without logging, as in building intermediate containers in a private CI flow that would not be immediately deployed. 

I personally prefer to stick with resin cli for all my docker builds if I'm going to use it for the releases. And this use case is not covered by `resin local push` and `resin sync`  that build on the device.

This could be related to #491 in my opinion.

**Comment by pimterry** [comment]
We're definitely thinking about this, and as part of #491 something like this might well come to fruition. Right now though, I'm going to leave it, until we've sorted that out. Watch this space.

**Comment by pdcastro** [comment]
This issue has likely been fixed by pull request 835 (https://github.com/balena-io/balena-cli/pull/835/). Needs verification.

**Comment by pdcastro** [comment]
I have tested that `balena build` now works without the need for login if the `--arch` and `--deviceType` options are provided (as opposed to the `--application` option, which tells the CLI to fetch those details from balenaCloud):
```
$ balena build . --application test-rpi
BalenaNotLoggedIn: You have to log in

$ balena build . --arch armv7hf --deviceType raspberrypi3
[Info]    Creating default composition with source: /Users/paulo/balena/other/simple_container
[Info]    Building for armv7hf/raspberrypi3
[Info]    Docker Desktop detected (daemon architecture: "x86_64")
[Info]      Docker itself will determine and enable architecture emulation if required,
[Info]      without balena-cli intervention and regardless of the --emulated option.
[Build]   Built 1 service in 0:01
[Build]   main Image size: 929.52 KB
[Success] Build succeeded!
```
