### ISSUE TITLE
resin login issue in Git Bash on Windows 10

### ISSUE THREAD

**Issue by imrehg** [balena-io/balena-cli#598]
In Git Bash (recommended in the ReadMe) from Git for Windows v2.13.3, node 8.2.1 64 bit, on Windows 10, `resin login` behaves strangely. The options are not colorized, and pressing up-down buttons don't show any change, but it still selects the given option. Meaning: `resin login` starts on "Web authorization", if pressing the down button, the screen does not change, but hitting enter would bring up the correct "Credentials" steps.

The same thing when running in `cmd.exe` on the same machine works fine.

**Comment by imrehg** [comment]
@pimterry any update on this one? just been working in windows for a bit, and run into this again.

**Comment by pimterry** [comment]
@imrehg No, sorry. I don't really have any time to look at it for at least a few weeks either, as we run up to the billing release. After that though I'll hopefully have a bunch more time for CLI improvements.

I have done a load of workshops in the last few months, with hundreds of Windows users, and I haven't ever seen this in the flesh myself, so I don't think it's a widespread issue. It'd be really interesting to know if you can reproduce it on other machines, or perhaps in [a fresh VM](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/), to help narrow down the root cause.

**Comment by pdcastro** [comment]
I hadn't seen this issue before, but I believe it matches what I saw in a user's laptop in the 2018 Barcelona Hackaton when trying to help them get started with balena.

**Comment by pdcastro** [comment]
Potentially related to #348

**Comment by pdcastro** [comment]
**Short story:**
You can get around this issue by selecting ***Use Windows' default console window*** during a Git Bash installation, as shown in this screenshot:

![git_bash_console_choice](https://user-images.githubusercontent.com/15091591/69284890-9433e000-0be7-11ea-8877-5316c1caa373.png)

**Long story:**
From what I have gathered and with "an informed small jump to conclusions", Git Bash is derived from MSYS2 and suffers the same limitations, including this bug:  https://github.com/msys2/MINGW-packages/issues/1633

When I install MSYS2 directly, I get the same broken interactive menu as when installing Git Bash **and selecting the _"Use MinTTY"_ option** during the Git Bash installation. I can get around the issue in a MSYS2 installation by following the procedure described in this comment: https://github.com/msys2/MINGW-packages/issues/1633#issuecomment-240583890, but I could not find the mentioned file (msys2_shell.cmd) in a Git Bash installation. But by selecting "Use Windows' default console window", the MSYS2 bug is avoided.

**Comment by pdcastro** [comment]
Closed via PR #1521, which adds a Git for Windows installation note to the CLI's README file (section [Choosing a shell](https://github.com/balena-io/balena-cli#choosing-a-shell-command-promptterminal)) advising how to get around this issue (screenshot in my previous comment), with the understanding that it is ultimately a [MSYS2 bug](https://github.com/msys2/MINGW-packages/issues/1633).
