### ISSUE TITLE
Detect and better handle 137 code errors during local build

### ISSUE THREAD

**Issue by pimterry** [balena-io/balena-cli#681]
A 137 error generally means the build was killed by the supervisor, potentially due to failing to enable local mode (https://github.com/resin-io/hq/issues/923), not pushing before local mode (https://github.com/resin-io/hq/issues/817), and supervisor bugs/broken state. We should fix these issues, but in the meantime we should look at ways to ensure we give useful feedback to users to remind them that:

* Local mode must be enabled in the dashboard for this device
* Local mode will only work after the first successful push to this device
* If they're still seeing this issue, they should report it to us (so we can grab supervisor logs)

There are various other ways this issue can present itself: https://github.com/resin-io/hq/issues/782. We don't need to solve this perfectly, but any improvements we can make to give users useful hints here would be fantastic.

**Comment by pdcastro** [comment]
I believe this issue is now obsolete. As of CLI v11, the ["live push" feature](https://www.balena.io/blog/living-on-the-edge-with-livepush-and-other-cli-improvements/) is enabled by default with the `balena push <ip-address>` command.
