### ISSUE TITLE
Make it easier to avoid pushing the wrong content with local push

### ISSUE THREAD

**Issue by pimterry** [balena-io/balena-cli#683]
It's easy to local push some content that will cause problems, e.g. `node_modules` built for the wrong architecture. These issues can be hard to debug for new users, and it's fairly unlikely that this is the behaviour you want. We should find ways to avoid this issue.

One easy option is to add a blacklist of patterns that we warn users about.

Could automatically remove these files from the push (helpfully making the push faster en route!).

Could send only files that aren't in `.gitignore` - that would have the added benefit of making the result typically very close to a direct git push (some possible differences - e.g. if you git ignore a file that's already committed - but I think that's ok).

Could allow you to override that with a `--force-push-all` flag or a configurable white/blacklist of files to push, but I would probably skip that until somebody asks for it - it seems like a fairly unlikely use case. Most users shouldn't be doing that, they should:

* Generate generated/downloaded files (build output, dependencies) in the Dockerfile, rather than committing & pushing them
* Ignore secret files, and send them via environment variables (for both git & local push deploys)
* Commit & push all the rest

**Comment by pdcastro** [comment]
Much of what is suggested was implemented with the ["live push" feature](https://www.balena.io/blog/living-on-the-edge-with-livepush-and-other-cli-improvements/) in CLI v11. Other elements of it are described in issues #1032 and #1421, so I am closing this issue in favour of those.
