### ISSUE TITLE
Filter user data from Sentry error reports

### ISSUE THREAD

**Issue by lekkas** [balena-io/balena-cli#703]
- **resin-cli version:** Version independent
- **Operating system and architecture:** Architecture independent

For instance, directory paths can be omitted

**Comment by pimterry** [comment]
I'm assuming you're on top of this @izavits as part of the analytics updates, but let me know if there's anything I should be doing about this myself :+1:

**Comment by izavits** [comment]
@pimterry yes, I'll let you know when I need your help

**Comment by pdcastro** [comment]
Related work was carried out in multiple PRs since this issue was created. I am not aware of anything specific that is pending, but it would be a good idea to double check, perhaps as part of the work in issue #1523.

**Comment by pdcastro** [comment]
The following commit removed the sending of the full command line to [Sentry.io](https://sentry.io/) in the event of uncaught errors: https://github.com/balena-io/balena-cli/pull/1654/commits/36d3d1256ebd851e2edeab4380a97646126fb5ee
