### ISSUE TITLE
resin local push: Improve UX and/or document 'environment' and 'ignore' CLI option saving logic

### ISSUE THREAD

**Issue by lekkas** [balena-io/balena-cli#708]
- **resin-cli version: version independent**
- **Operating system and architecture: os independent**

See: https://forums.resin.io/t/local-mode-node-error/2097/10?u=lekkas

To make sure that the following report makes sense, let me start by pointing out that `resin local push` has two modes of operation:

- A full container rebuild. This happens when an app is first `resin local push`'ed to the device and/or when `--force-rebuild` option is passed
- A sync operation to the running container. Unless a trigger file (`Dockerfile` and `package.json` by default, others can be specified in `resin-sync.yml`) has changed, `resin local push` will attempt to rsync the local files over to the device instead of rebuilding the container.

Currently passed `environment` variables will only be saved to `.resin-sync.yml` if a container is being (re)created with `resin local push` and not when a 'sync' operation is performed. IIRC the reason was that environment variables only take effect when the container is (re)created and not when it is restarted, which is the case when a sync is performed.

Likewise, the `ignore` CLI option is only relevant when a syncing `resin local push` kicks in. The `ignore` option is not relevant when a container (re)build `resin local push` operation starts (if one wants to skip files from being sent over to the device docker daemon then these have to be included in the `.dockerignore` instead) therefore the `ignore` and for that reason `ignore` options are not saved into `.resin-sync.yml`

One possible solution to these issues would be to simply save all options unequivocally and have an 'info' message on whether or not they will have any effect depending on the `resin local push` operation that will be performed (sync or rebuild). In the (near?) future the sync operation might as well be completely removed if building containers is deemed to be fast enough.

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3u1d)

**Comment by pimterry** [comment]
This will come in as part of the CLI redesign work I think. The current plan is to remove the 2nd mode entirely, and _always_ do a build (since it's about as fast, and behaves way more predictably), which should eliminate this problem completely.

I'll leave this open as a separate issue anyway for now, to ensure we think about this as part of that redesign, but I don't think it needs any more immediate action.

**Comment by pdcastro** [comment]
Related to #441

**Comment by pdcastro** [comment]
The `local push` command was replaced in CLI v11 with the ["live push" feature](https://www.balena.io/blog/living-on-the-edge-with-livepush-and-other-cli-improvements/) which is enabled by default with the `balena push <ip-address>` command. Documentation was also much improved earlier this year, see: [Deploy to your Fleet](https://www.balena.io/docs/learn/deploy/deployment/) documentation.
