### ISSUE TITLE
SSH commands throw no errors and return success codes even on failure 

### ISSUE THREAD

**Issue by pimterry** [balena-io/balena-cli#716]
`resin promote` appears to have some bugs right now (https://github.com/resin-io/resin-cli/issues/710), which don't get reported to Sentry, and don't have the standard 'if you need help' error footer, because we don't check the exit code of the SSH subcommand at all. The same issue exists in `resin ssh`, and likely other places too.

It should be fairly easy to start checking responses here, and throwing an error if they're not successful, to help us spot issues earlier.

**Comment by pdcastro** [comment]
The `resin promote` command no longer exists.
