### ISSUE TITLE
Stop & remove app containers in parallel to local push, with better feedback

### ISSUE THREAD

**Issue by pimterry** [balena-io/balena-cli#723]
Right now, `local push` is fairly synchronous: https://github.com/resin-io-modules/resin-sync/blob/master/lib/capitano/resin-toolbox.coffee#L164-L198. We do some querying up front, and wait until the existing app has been killed and remove, and then we do the build etc.

This means for the normal cached development flow, the majority of time is spent on the initial 'Stopping and removing' step, with no feedback, followed by high speed build output.

We should do more of this in parallel, and with better feedback:
* Stop & remove existing containers in parallel to the build
* Query for the previous image id in parallel to the build
* Show a spinner when the uploading for the build itself starts
* Remove the old image in parallel to creating & starting the new container.

@lekkas I noticed this in my talk on Friday - it makes it a bit awkward to demo, because it just sits on 'stopping & removing' for ages (well, 10s or so), and it's not easy to explain to an audience what's going on. I think there's some nice UX tweaks and overall performance improvements here in some code people will be running pretty often. Are there any reasons not to do the above? Is there a specific reason we always stop & remove the existing container before we let any building start?

**Comment by lekkas** [comment]
@pimterry If we can safely parallelise the tasks

- build // stop&remove old containers, query image id 
- start container // remove old image 

with the new build let's go for it. There is no specific reason to keep the initial waterfall approach, it was the simplest to start with. I also agree on giving the user some feedback like the spinners you suggest because long, silent pauses can be awkward :)

**Comment by pimterry** [comment]
Related to #528

**Comment by pdcastro** [comment]
The `local push` command was replaced with the ["live push" feature](https://www.balena.io/blog/living-on-the-edge-with-livepush-and-other-cli-improvements/) which is enabled by default with the `balena push <ip-address>` command in CLI v11. The logic for stopping and restarting containers is now much cleverer. :-)
