### ISSUE TITLE
Move to TypeScript

### ISSUE THREAD

**Issue by pimterry** [balena-io/balena-cli#733]
We need to fix this so that we can more easily and safely update the SDK etc shortly, because there's a lot of that coming soon.

**Comment by pdcastro** [comment]
I was looking at some of the open issues in the balena-cli repo and I thought it would make sense to repurpose this year-old issue. I'm submitting a pull request that adds a note for contributors in the README file (mainly for contributions external to balena), to clarify the goal of migrating from CoffeeScript to TypeScript in any new development work. [Pull request 1077](https://github.com/balena-io/balena-cli/pull/1077) could close this issue.
