### ISSUE TITLE
Add command for enabling support access on a device or app

### ISSUE THREAD

**Issue by LucianBuzzo** [balena-io/balena-cli#766]
This can be done in the dashboard and the methods for this action are already available in the SDK:
- https://github.com/resin-io/resin-sdk/blob/master/DOCUMENTATION.md#applicationgrantsupportaccessnameorid-expirytimestamp--promise
- https://github.com/resin-io/resin-sdk/blob/master/DOCUMENTATION.md#devicegrantsupportaccessuuidorid-expirytimestamp--promise

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_7drt)

**Comment by srlowe** [comment]
@pdcastro How about:
`balena support <enable|revoke>`
with an option specifying the target type and id?

e.g.: 
```
balena support enable --device ab346f
balena support revoke --application 2222ae
```

**Comment by pdcastro** [comment]
@srlowe, enable/disable, grant/revoke, enable/revoke, on/off... Among these, my vote would go for enable/disable.

When enabling support, the dashboard and the SDK also allow specifying for how long, or an expiry timestamp. There could be an option like:
`--duration 12h` # 12 hours
`--duration 3d`  # 3 days
`--duration 2w` # 2 weeks

If `--duration` is not specified, the dashboard defaults to 3 hours, but I'm not sure this would be a good default for the CLI. With the web UI, the dropdown box makes it very easy to change the default, whereas with the CLI, I imagine many people would not bother changing the default, and we'd end up with support indeed being granted for only 3 hours, which often is not enough to diagnose issues, especially when specialist engineers are pinged. But to choose a different default for the CLI, say 24 hours, would introduce "disparity" with the UI. So I am inclined to suggest making `--duration` a mandatory option as well, and having no default duration.

```
balena support enable --device ab346f --duration 3d
balena support disable --application myApp
```

It would be good to allow a comma-separated list of app names or device UUIDs, like the `balena env add` command does:

```
$ balena support enable --application MyApp,MyApp2 --duration 1w

$ balena support disable --device 7cf02a6,d6f1433
```

The single-char options might be `-a` for `--application`, `-d` for `--device` and... `-t` for `--duration`? (t = time)

@LucianBuzzo, @shaunmulligan, any preferences / suggestions as to the form the command should take?

**Comment by srlowe** [comment]
@pdcastro I'm don't really mind re the on/off wording - just checked the dash and it's `grant`/`revoke` there.   I feel like we probably should include a duration default though, as every required option makes the command less convenient.  If 3hrs isn't long enough to solve many tickets, then perhaps we should consider increasing the default on the dash? (and match that).

**Comment by srlowe** [comment]
> With the web UI, the dropdown box makes it very easy to change the default, whereas with the CLI, I imagine many people would not bother changing the default, and we'd end up with support indeed being granted for only 3 hours,

Alternatively, we could not have a default, but present an interactive selector for duration (when it's not specified in options), like the dashboard.

**Comment by pdcastro** [comment]
> Alternatively, we could not have a default, but present an interactive selector for duration (when it's not specified in options), like the dashboard.

It could be done, but we would still have to handle the non-interactive case: either having a default value, or making the duration option mandatory. My preference is to make the option mandatory, and raise an error if it is not specified. Personally, I am not a fan of interactive prompts generally on a command line interface (not just balenaCLI), as prompts don't work in well in some environments (cursor in the wrong place and such) and all the complications associated with scripting.

**Comment by srlowe** [comment]
@pdcastro Ok, perhaps let's ask shaun to decide then.

**Comment by shaunmulligan** [comment]
@srlowe and @pdcastro I agree with Scott, I think we should just change the default option in the dashboard to 24hrs and then have the CLI default to that and also probably print out that duration is when the command is run, perhaps telling the user until what date and time support access will stay for.
