### ISSUE TITLE
Triggering resinOS update through the CLI

### ISSUE THREAD

**Issue by imrehg** [balena-io/balena-cli#788]
Not just through the dashboard. HQ: https://github.com/resin-io/hq/issues/1204

**Comment by thgreasi** [comment]
I guess that it should first make it to the SDK.

**Comment by thgreasi** [comment]
HQ: https://github.com/resin-io/hq/issues/1215
See: https://www.flowdock.com/app/rulemotion/resin-frontend/threads/sYrLPINqwDMg1t5Zb9-lcW9IAWi?filter=search&query=hup
See: https://www.flowdock.com/app/rulemotion/r-architecture/threads/lukg_hxfLkIRON5-TTAhmycEvxk
See: https://www.flowdock.com/app/rulemotion/resin-frontend/threads/m90nwXCsWvXikh2fHSM_uZToGoa
