### ISSUE TITLE
resin local push: simplify support of private Docker registries

### ISSUE THREAD

**Issue by lekkas** [balena-io/balena-cli#790]
- **resin-cli version: all**

Currently an extra step (`resin local ssh --host` and then `balena login`) is required before `resin local push` so that the on-device Balena daemon can authenticate with a private registry. 

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_8btl)

**Comment by lekkas** [comment]
Briefly checked for any quick workarounds here, it looks like dockerode does not support existing credentials files that are created from `docker login` out of the box - https://github.com/apocas/dockerode/issues/307

**Comment by pimterry** [comment]
@lekkas where has this request come from? If there's a related HQ/Front thread, can you add it here for context?

**Comment by pcarranzav** [comment]
@pimterry https://app.frontapp.com/open/cnv_ktr2t5

**Comment by hedss** [comment]
@pimterry I've updated this, we've another one as well now: https://app.frontapp.com/open/cnv_s4juv7

**Comment by pdcastro** [comment]
Issue #1015 implemented the `--registry-secrets` option for the `balena push` command, which works for local devices as well (by specifying an IP address instead of an app name). The `balena local push` command does not yet support it, though.

**Comment by CameronDiver** [comment]
This is supported via `balena push` and `balena local push` is deprecated.
