### ISSUE TITLE
Perform client side checking for application types and multicontainer releases

### ISSUE THREAD

**Issue by CameronDiver** [balena-io/balena-cli#803]
This will be blocked by the API, but having this information before a build completes will be useful, and will also provide a more understandable error message to the users.

**Comment by pdcastro** [comment]
@CameronDiver, do you remember the details of the desired client side checking? Some recent-ish work was done in this area, but I don't know if it covers what you had in mind:
* https://github.com/balena-io/balena-cli/issues/1421
* https://github.com/balena-io/balena-cli/issues/1619
* https://github.com/balena-io/balena-cli/pull/1571

And these other open issues mention some more specific points:
* https://github.com/balena-io/balena-cli/issues/1620
* https://github.com/balena-io/balena-cli/issues/1621
* https://github.com/balena-io/balena-cli/issues/1671

**Comment by CameronDiver** [comment]
It was mainly to avoid having to upload the entire build pack to the builder before it being denied, saving both time and bandwidth. It would also enable a much more specific error message ("You cannot push this release to this application type because it is multicontainer" or something like that).

**Comment by CameronDiver** [comment]
@pdcastro heads up Ive unassigned myself to this as it's unlikely I'll get to it soon.

**Comment by myarmolinsky** [comment]
Closing as all applications are now multicontainer and application types are no longer a thing
