### ISSUE TITLE
Build command ignores --tag argument

### ISSUE THREAD

**Issue by dfunckt** [balena-io/balena-cli#825]
- **resin-cli version: >=7.0.0**
- **Operating system and architecture: All**

It is currently completely ignored, but it's functionality overlaps with `--projectName`, so we need to either:

a) remove it
b) make it an alias to `--projectName`
c) replace `--projectName` with `--tag`

(c) is the most likely candidate given `--tag` existed in previous versions, but it's less accurate now with multi-container.

**Comment by pdcastro** [comment]
Fixed in CLI v12.48.11. The `--tag` flag specifies only the `:tag` portion of the image name. For example:
```
$ balena build . --projectName dronecontrol --tag v2.2.4
```
Images created (e.g. as listed by `docker images` on the workstation):
```
dronecontrol_service1:v2.2.4
dronecontrol_service2:v2.2.4
dronecontrol_service3:v2.2.4
```
The default if `--tag` is not specified is `:latest`.

Help output:

```
$ balena help build
...
OPTIONS
...
-n, --projectName <projectName>  Name prefix for locally built images. This is the 'projectName' portion
                                 in 'projectName_serviceName:tag'. The default is the directory name.

-t, --tag <tag>                  Tag locally built Docker images. This is the 'tag' portion
                                 in 'projectName_serviceName:tag'. The default is 'latest'.
```
