### ISSUE TITLE
Support multi-container local push

### ISSUE THREAD

**Issue by agherzan** [balena-io/balena-cli#836]
_From @cschroeter on March 28, 2018 15:0_

What an amazing project! Maybe you could help me with the following scenario

So as far as I understand, right now it is not possible to push a docker-compose.yml with 

```resin local push resin.local --source .```  as mentioned in https://github.com/resin-os/meta-resin/issues/414

So given the following docker-compose.yml I must create two different Dockerfiles and push them separately, or? What is the recommended way to realize local multi container deployments.

```version: "2"
services:
  app:
    build: .    
    command: npm start
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://username@postgres/database
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: username
      POSTGRES_DB: database
```

_Copied from original issue: resin-os/meta-resin#1046_

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_e80r)

**Comment by shaunmulligan** [comment]
Hey @agherzan and @cschroeter we are in the process of making `resin local push` compatible with multiple containers, but in the meantime the process I would recommend is to use the remote docker API with docker-compose on your machine. I have an example of that workflow here:

https://github.com/resin-io-playground/resinos-compose

**Comment by cschroeter** [comment]
@shaunmulligan thanks for the reply. i've seen ur project 👍 
I was able to push my composition but after i restart my raspy those two container can not be start, cause the "glue" the docker-compose.yml was not available. Or am I overlooking something?

**Comment by shaunmulligan** [comment]
Hey @cschroeter yeah unfortunately currently there isn't a good way to get a composition to persist over reboot. This is one of the main driving features of this OS feature: https://github.com/resin-os/meta-resin/issues/1025

In the near future, you will be able to use `resin push` to develop and run multiple containers on your device and these will automatically be brought up on each boot.

One thing you might be able to try currently with the docker-compose approach is to set: `restart: always` on each of the services in the composition, this I think may make the docker daemon automatically restart the containers when the device boots up.

**Comment by cschroeter** [comment]
@shaunmulligan thanks for your reply.

**Comment by shaunmulligan** [comment]
hey @tomasmigone yes, there are some updates actually. If you have a `balenaOS v2.26.0` or greater .dev device, set in localMode and you install `CLI v9.1.2`, then you can do the following to get multicontainer localmode:
```
balena push <DEVICE_IP> -s .
```
there are a few changes in the way we are doing localmode and lots of improvements coming over the next month or so around speeding up the experience and adding documentation, etc.

**Comment by thgreasi** [comment]
@shaunmulligan should we treat your suggestion as a solution and close this issue?

**Comment by tomasmigone** [comment]
@shaunmulligan thanks! It works great!

Just for reference, this also worked for me as per the cli documentation: `balena push <APP_NAME> -s .`

**Comment by mhazley** [comment]
@shaunmulligan I'm having a few issues with this:

Local device on network running `balenaOS 2.27.0+rev1`

```
$ ping 54c1bb4.local
PING 54c1bb4.local (10.56.90.102): 56 data bytes
64 bytes from 10.56.90.102: icmp_seq=0 ttl=64 time=3.795 ms
64 bytes from 10.56.90.102: icmp_seq=1 ttl=64 time=4.534 ms
```

Attempt the push above as you described:

```
$ balena push 10.56.90.102 -f -s .
Could not communicate with local mode device at address 10.56.90.102
```

Running CLI version:

```
$ balena version
9.3.6
```

Does it need to be `9.1.2` exactly?

**Comment by thgreasi** [comment]
@mhazley is that device running a dev image? Is local mode enabled on it?

**Comment by mhazley** [comment]
Yeah dev image and local mode - I can push a Dockerfile to it using local push.

Im not so worried though, I only wanted this to create a volume for logs in a single container but I realise that `/data` is persistent so I've just been using that.

**Comment by mschm** [comment]
@shaunmulligan The `--registry-secrets` option has no effect in my case. I'm trying to push a multi container app to a device running in localMode.

My development host is macOS with balena-cli version 9.12.2.

```
$ balena push 192.168.2.113 --registry-secrets secrets.yml -s .
[Info]    Starting build on device 192.168.2.113
[Info]    Compose file detected
Some services failed to build:
	service-1: (HTTP code 404) unexpected - pull access denied for <private-registry/image1>, repository does not exist or may require 'docker login' 
	service-2: (HTTP code 404) unexpected - pull access denied for <private-registry/image2>, repository does not exist or may require 'docker login' 
...
```

I'd expect that if I ssh into the device, `balena login <private-registry>` and `balena pull` all images by hand I could at least have a workaround – but the error remains.

Any suggestions, what might be wrong?
Thank you!

**Comment by pcgeek86** [comment]
@shaunmulligan  I have the following folder:

```
total 0
drwxrwxrwx 1 trevor trevor 512 Feb 21 17:39 ./
drwxrwxrwx 1 trevor trevor 512 Feb 21 16:01 ../
drwxrwxrwx 1 trevor trevor 512 Feb 21 17:06 bluetooth/
-rw-rw-rw- 1 trevor trevor 191 Feb 21 17:10 docker-compose.yml
drwxrwxrwx 1 trevor trevor 512 Dec  5 09:12 wifi-connect/
```

When I run the balena CLI to push to a local development device:

```
trevor@trevorxps:~/git/asdf$ sudo balena local push --source .
No Dockerfile found in the project directory: /home/trevor/git/harkai

If you need help, don't hesitate in contacting us at:

  GitHub: https://github.com/balena-io/balena-cli/issues/new
  Forums: https://forums.balena.io
```

**Comment by shaunmulligan** [comment]
@pcgeek86 can you switch to using `balena push <IP>` as we are deprecating `balena local push`

**Comment by shaunmulligan** [comment]
@mschm is your secrets.yml file in the root of your app folder and can you show the contents of that file (obviously replace your password with ***)

For my tests I used the following:
```
'https://index.docker.io/v2/':
  username: myusername
  password: mysecretpassword
```

I think the whitespace matters quiet a bit in that file, so make sure there aren't any stray spaces

**Comment by pcgeek86** [comment]
@shaunmulligan yup that worked. `balena push` not `balena local push`. We should probably add a deprecation message if that's the case.

**Comment by mschm** [comment]
@shaunmulligan it appears that this is no longer a problem after updating balena-cli to 9.14.2!

Thanks for your help!
