### ISSUE TITLE
User wants to execute commands non-interactively with resin local ssh

### ISSUE THREAD

**Issue by lekkas** [balena-io/balena-cli#837]
- **resin-cli version: all**
- **Operating system and architecture: all**
- See: https://github.com/resin-io/hq/issues/692

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_actv)

E.g. `sudo resin local ssh <ip> <command>`

**Comment by pdcastro** [comment]
Closing in favour of #1482 (`balena local ssh` was replaced with `balena ssh`)
