### ISSUE TITLE
If your ssh key requires a passphrase, resin sync spins forever

### ISSUE THREAD

**Issue by pimterry** [balena-io/balena-cli#840]
If your key requires a passphrase, and you're not using an ssh agent or similar, then it prompts for the phrase, but then our spinner hides, so you don't know about it.

We should really fix this, but we have also discussed just removing resin sync entirely, which might be better...

**Comment by srlowe** [comment]
@pdcastro Looks like `sync` has been removed? If so, does this affect other commands, or should this be closed?

**Comment by pdcastro** [comment]
@srlowe, indeed, this issue is obsolete. Closing it. Good job reviewing the issues! 👍
