### ISSUE TITLE
resin local ssh fails on Windows 10 with a syntax error

### ISSUE THREAD

**Issue by pcarranzav** [balena-io/balena-cli#876]
From the forums: https://forums.resin.io/t/resin-local-ssh-on-win10-syntax-error-near-unexpected-token-then/3066

> Local ssh ("resin local ssh ") fails with the following error when trying to connect, both to supervisor, and local app:

```
sh: -c: line 0: syntax error near unexpected token then' sh: -c: line 0:(if [ -f /usr/bin/balena ]; then echo \"balena\"; else echo \"docker\"; fi) exec -ti 748901cc1e35a844b777ca9d62126b8ebf19253873f4b75c0cc0edb24ef227b8 /bin/sh -c ‘if [ -e /bin/bash ]; then exec /bin/bash; else exec /bin/sh; fi’"’
```

- **resin-cli version: 7.3.8**
- **Operating system and architecture: Resin OS: 2.12.6+rev1 (dev)**

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_bi63)

**Comment by pdcastro** [comment]
I have just tested `balena ssh` on Windows with both an IP address and a device UUID, and it worked.  As of CLI v11 (currently 11.18.3), the `resin local ssh` command was replaced with `balena ssh`, and it now supports multicontainer devices as well, opening a shell directly in the container.
