### ISSUE TITLE
Add 'balena deploy' flag to specify a release tag

### ISSUE THREAD

**Issue by CameronDiver** [balena-io/balena-cli#892]
The problem (at least one scenario):
* User pushes the same project (their git repo) to different balena apps during deployment.
* When using git push, the local git commit is visible on the app in the balena dashboard in the release field.
* When using balena push the release shown in the app and the local commit differs.
* To see if two apps have the same release it's possible to compare the release ids in the app.
* There's no way to determine which local release (commit) matches a remote app release Id.

Add a `--release-tag` option on `balena push` so then you could do `balena push myApp --release-tag v1.0` which would then add 'v1.0' to the app's release page. Users could of course choose to use a git commit hash as the tag value instead of 'v1.0'.

This could also be extended to `resin deploy`.

EDIT: As of CLI v12.36.0 `balena push` supports --release-tag flag. Usage is shown in this [diff](https://github.com/balena-io/balena-cli/commit/34557e35eed227c22482b7fe91b7239c6e5908b9#diff-b97760d27de61e58afc3f3d964a7ef10b7360b90b036380e20e2db95d7c249e7). Future work is to add that same feature in `balena deploy`.

**Comment by pdcastro** [comment]
Anti-related to issue #825 (build command ignores --tag argument). I mention it because we want to improved flag consistency across the CLI commands.

**Comment by pdcastro** [comment]
"Known workaround": either manually add a release tag (see screenshot), or write some code (curl commands or SDK) to use the balena API to automatically do it (which is what the CLI would do):
* https://www.balena.io/docs/reference/sdk/node-sdk/#balena.models.release.tags.set
* https://www.balena.io/docs/reference/sdk/python-sdk/#function-setrelease_id-tag_key-value
* https://www.balena.io/docs/reference/api/resources/release/

![Screenshot 2019-05-07 at 13 21 13](https://user-images.githubusercontent.com/15091591/57299201-deca9080-70cb-11e9-8462-54522b693897.png)

**Comment by magiconair** [comment]
Can we somehow bump the priority on this? This seems like an obvious addition to the CLI since the UI already has the tagging support.

This is a real pain when deploying containers instead of source. The release number never matches anything we can relate to and the only way to set the release tag is manually through the GUI.

**Comment by magiconair** [comment]
I just ran into this again not realizing that the `--tag` parameter in `balena deploy` is not for setting release tags in the UI but for tagging the container itself. #1510

**Comment by pdcastro** [comment]
If it helps, let me quote a comment that @thgreasi added to issue #1060 (User would like to set tag when using balena deploy) :
> Keep in mind that since v11.15.0 (PR #1470) the CLI supports setting tags:
> `balena tag set mytag --release <commit_hash>`
> This is just a workaround though and doesn't resolve this issue.

**Comment by magiconair** [comment]
ok, I can get the commit hash with `balena app` and then use that.

**Comment by magiconair** [comment]
Since the functionality is there and the balena deploy command has the commit hash can't you just add a call that also sets the release tag?

**Comment by magiconair** [comment]
Quick warning that this does not work since by the time you call `balena tag` the release version may not have been updated. Also thinking that this might depend on the release policy whether this gets updated at all.

```
deploy:
	balena deploy uabrowse $(DOCKER_BASE):$(VERSION)-linux-amd64
	balena tag set "$(VERSION)" --release $(shell balena app uabrowse | grep COMMIT: | awk '{print $$2}')
```

**Comment by magiconair** [comment]
I will have to parse the output of `balena deploy` to get the correct commit hash ...

**Comment by magiconair** [comment]
Note that this doesn't work as well since `$(shell...)` seems to be executed eagerly, i.e. before the commands of the target are executed. So this will tag the previous release.

```
deploy:
	balena deploy uabrowse $(DOCKER_BASE):$(VERSION)-linux-amd64 | tee build/deploy
	balena tag set "$(VERSION)" --release $(shell grep Release: build/deploy | awk '{print $$3}')
```

**Comment by magiconair** [comment]
This seems to work:

```
deploy:
	balena deploy uabrowse $(DOCKER_BASE):$(VERSION)-linux-amd64 | tee build/deploy
	balena tag set "$(VERSION)" --release `grep Release: build/deploy | awk '{print $$3}'`
```

**Comment by Timple** [comment]
So it's been a while. Is this on any roadmap or should we use the workaround @magiconair was so friendly to provide?

**Comment by mbalamat** [comment]
The `--release-tag` flag was introduced in CLI release v12.38.0.

**Comment by thgreasi** [comment]
:tada:

**Comment by evanlesmez** [comment]
Thank you!

**Comment by evanlesmez** [comment]
Is there any plan to add this to `balena push` as well? 

```bash
 balena push App --release-tag
Unexpected argument: --release-tag
See more help with --help

```

**Comment by pdcastro** [comment]
> Is there any plan to add this to `balena push` as well?

@evanlesmez, `balena push` accepts the `--release-tag` flag since CLI `v12.36.0`. Could it be that you were testing with an older version? I've just tried using it to confirm:
```
$ balena version
12.38.8

$ balena push test-rpi --release-tag mytag '2020-02-03 21:13'
...
[Success]  Release successfully created!
[Info]     Release: 9015082bca846fedb320b519ab136a89 (id: 1684012)

$ balena tags -r 9015082bca846fedb320b519ab136a89
TAG KEY VALUE
mytag   2020-02-03 21:13
```

**Comment by evanlesmez** [comment]
> > Is there any plan to add this to `balena push` as well?
> 
> @evanlesmez, `balena push` accepts the `--release-tag` flag since CLI `v12.36.0`. Could it be that you were testing with an older version? I've just tried using it to confirm:
> 
> ```
> $ balena version
> 12.38.8
> 
> $ balena push test-rpi --release-tag mytag '2020-02-03 21:13'
> ...
> [Success]  Release successfully created!
> [Info]     Release: 9015082bca846fedb320b519ab136a89 (id: 1684012)
> 
> $ balena tags -r 9015082bca846fedb320b519ab136a89
> TAG KEY VALUE
> mytag   2020-02-03 21:13
> ```

You are absolutely right my apologies.
