### ISSUE TITLE
'getWindowSize Unknown system error -25' in local push

### ISSUE THREAD

**Issue by pimterry** [balena-io/balena-cli#922]
https://sentry.io/resinio/cli/issues/603243606/

```
Error: getWindowSize Unknown system error -25
  File "util.js", line 1018, in exports._errnoException
  File "tty.js", line 78, in WriteStream._refreshSize
  File "internal/process/stdio.js", line 16, in process.on
  File "events.js", line 91, in emitNone
  File "events.js", line 185, in process.emit
...
(1 additional frame(s) were not displayed)

Error: getWindowSize Unknown system error -25
```

Some quick googling suggests this is ENOTTY - we can't get the window size because you're not using a TTY. Perhaps if you run local push over SSH? We should handle failures in getWindowSize gracefully anyway - it certainly isn't critical information.

**Comment by pdcastro** [comment]
Also reported for `balena local ssh`: https://sentry.io/balena/cli/issues/741403146/
One of the roadmap features is tty auto detection, which would probably fix this issue.

**Comment by pdcastro** [comment]
The `local push` and `local ssh` commands have were removed / replaced in CLI v11, and the `getWindowSize` error can no longer be found in Sentry (past 90 days' search).
