### ISSUE TITLE
resin push <application> does not return error code on build failure

### ISSUE THREAD

**Issue by jarrodsinclair** [balena-io/balena-cli#947]
* Resin CLI v7.9.0, running on CircleCI Linux

When building on remote resin.io cloud builders, the push command does not return an error code when the build fails. Therefore, CircleCI thinks the step has completed successfully.

**Comment by Page-** [comment]
Hey, I think this is already fixed in v7.9.1 @jarrodsinclair, could you update and try again please

**Comment by jarrodsinclair** [comment]
Hi Page,

I just updated to v7.9.2 (standalone) and added a bug to my Dockerfile, but the ```resin push``` command did not return the error code. See the output from CircleCI below. The last line is the return code (using ```echo $?``` after ```resin push```).

```
...
[platform]  tar: TESTING_BROKEN_FILE.tar.gz: Cannot open: No such file or directory
[platform]  tar: Error is not recoverable: exiting now
[platform]  tar: Child returned status 2
[platform]  tar: Error is not recoverable: exiting now
[platform]  
[platform]  Removing intermediate container 135a89a7fc95
[platform]  The command '/bin/sh -c cd /root &&     tar -xzf TESTING_BROKEN_FILE.tar.gz' returned a non-zero code: 2
[Info]      Uploading images
[================>                                  ] 33%[================>                                  ] 33%[================>                                  ] 33%[=================================>                 ] 66%[=================================>                 ] 66%[Success]   Successfully uploaded images

[Error]     Some services failed to build:
[Error]       Service: platform
[Error]         Error: The command '/bin/sh -c cd /root &&     tar -xzf TESTING_BROKEN_FILE.tar.gz' returned a non-zero code: 2
[Error]     Not deploying release.
0
```

Maybe something related to the standalone install?

**Comment by Page-** [comment]
No, it's probably just a different thing than the bug I fixed.  cc @pimterry @CameronDiver

**Comment by CameronDiver** [comment]
Hey @jarrodsinclair thanks for bringing this to our attention! I've made a fix here: https://github.com/resin-io/resin-cli/pull/948
