### ISSUE TITLE
Malformed token

### ISSUE THREAD

**Issue by bakkerpeter** [balena-io/balena-cli#956]
- **resin-cli version: standalone resin-cli v7.9.3**
- **Operating system and architecture: debian:stretch-slim**

```
# resin login --token xxx
# resin env add EDITOR vim --application Print
```
Results into: 
```
ResinMalformedToken: Malformed token: xxx

If you need help, don't hesitate in contacting us at:

  GitHub: https://github.com/resin-io/resin-cli/issues/new
  Forums: https://forums.resin.io
```
Am I missing something in the docs?

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_drfn)

**Comment by pimterry** [comment]
API keys are now fully supported in all CLI commands, from balena-cli v9.0.0 onwards, so in future you shouldn't ever see this error. Thanks for the report!
