### ISSUE TITLE
Should support the oss flow

### ISSUE THREAD

**Issue by thgreasi** [balena-io/balena-cli#978]
Depends-on: https://github.com/resin-io/resin-sdk/issues/591
Depends-on: https://github.com/resin-io/resin-sdk/pull/594
HQ: https://github.com/resin-io/balena/pull/1140

**Comment by dfunckt** [comment]
@thgreasi @pimterry should we close this and create new issues going forward?

**Comment by pimterry** [comment]
Sounds sensible to me.
